reference/conanfile/tools/cmake.rst
Docs for https://github.com/conan-io/conan/pull/9009
Docs for https://github.com/conan-io/conan/pull/9024
=> skip_rpath and new blocks in CMakeToolchain

mastering/policies.rst, reference/commands/creator/export-pkg.rst
Docs for https://github.com/conan-io/conan/pull/8946
=> build_policy=never for conan export-pkg

creating_packages/package_information.rst
=> fix an spell error

reference/profiles.rst
Docs for https://github.com/conan-io/conan/pull/9147
=> profile templates

reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/meson.rst
docs for https://github.com/conan-io/conan/pull/8353
=> - improve docs on preprocessor_definitions

reference/conanfile/tools/cmake/cmaketoolchain.rst
Docs for:
- https://github.com/conan-io/conan/pull/9109
- https://github.com/conan-io/conan/pull/9115
=> cmaketoolchain cross-build + blocks customization

getting_started.rst, reference/commands/consumer/info.rst, reference/commands/output/info.rst
Docs for https://github.com/conan-io/conan/pull/9137
=> context info output

reference/conanfile/tools/gnu.rst, reference/conanfile/tools/gnu/pkgconfigdeps.rst, reference/generators/pkg_config.rst
Added documentation related to new conan/feature: conan-io/conan#9152
Added new `PkgConfigDeps` generator in `conan.tools.gnu.pkgconfigdeps.py`
=> Added PkgConfigDeps generator

developing_packages/editable_packages.rst, developing_packages/package_layout.rst, reference/conanfile/tools/layout.rst
Close https://github.com/conan-io/conan/issues/9246
=> clarify layout() support

reference/commands/misc/profile.rst
Docs for https://github.com/conan-io/conan/pull/9204
=> Minor help output update

reference/build_helpers/cmake.rst, reference/build_helpers/meson.rst, reference/config_files/global_conf.rst
Related to https://github.com/conan-io/conan/pull/9218
=> Skip build helper test method

reference/conanfile/tools/microsoft.rst
PR for https://github.com/conan-io/conan/pull/9230
NOTE: Contain a (still) broken link to the docs at https://github.com/conan-io/docs/pull/2151
=> vcvars generator

reference/conanfile/tools/gnu/pkgconfigdeps.rst
Docs for:
* https://github.com/conan-io/conan/pull/9228
=> Changed new pc file name for components

reference/conanfile/attributes.rst, systems_cross_building/windows_subsystems.rst
Docs for https://github.com/conan-io/conan/pull/9194
=> new win bash mechanism

reference/commands/consumer/install.rst, reference/profiles.rst
Docs for https://github.com/conan-io/conan/pull/9267
=> & to specify consumer packages

reference/conanfile/dependencies.rst
Docs for https://github.com/conan-io/conan/pull/9171
=> adding the test trait in new dependencies model

reference/commands/consumer/install.rst, reference/commands/creator/create.rst
Docs for https://github.com/conan-io/conan/pull/9195
=> --require-override docs

reference/commands/misc/inspect.rst
Docs for https://github.com/conan-io/conan/pull/9296
=> inspect alias

reference/conanfile/tools.rst, reference/conanfile/tools/cmake/cmakedeps.rst, reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/gnu/autotoolsdeps.rst, reference/conanfile/tools/gnu/autotoolstoolchain.rst, reference/conanfile/tools/meson.rst, reference/conanfile/tools/microsoft.rst
Docs for https://github.com/conan-io/conan/pull/9206
=> build context warnings

reference/commands/consumer/install.rst
Applying comment from the discussion: #2124 (comment)
=> Conf message improvement

.ci/Dockerfile, .ci/test.jenkins
Taking https://github.com/conan-io/docs/pull/2194 to develop
Also fixing enchant package name
=> Warn about linkcheck failed but do not fail

creating_packages/getting_started.rst, faq/using.rst, integrations/ci/jenkins.rst, reference/conanfile/tools/layout.rst, using_packages/conanfile_txt.rst
Docs for https://github.com/conan-io/conan/pull/9516
=> new Creating packages getting started

reference/commands/misc/remove.rst
Some people asked how to remove packages from remotes, but based only on revisions.
Related to PR: https://github.com/conan-io/conan/pull/9459
=> Remove packages based on revisions

integrations/build_system/make.rst
Close https://github.com/conan-io/docs/issues/2201
=> fix make generator docs

reference/conanfile/tools/files.rst
Docs for https://github.com/conan-io/conan/pull/9593
=> Recover base_path in patch

reference/generators/qmake.rst
Docs for: https://github.com/conan-io/conan/pull/9568
=> Update qmake vars

reference/conanfile/tools/files.rst
It's not clear how to import new `conan.tools`, let's try to keep it more explicit.
Related to https://github.com/conan-io/conan-center-index/issues/7377
=> Add import line to conan.tools examples

reference/conanfile/tools/cmake/cmake.rst, reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/gnu/autotools.rst, reference/conanfile/tools/gnu/autotoolstoolchain.rst, reference/conanfile/tools/google.rst
Docs for: https://github.com/conan-io/conan/pull/9688
=> Add docs about namespaces in build helpers and toolchains

reference/conanfile/attributes.rst
Docs for https://github.com/conan-io/conan/pull/9520
=> Docs for cpp_info.objects

reference/conanfile/tools/files.rst
Docs for https://github.com/conan-io/conan/pull/9715
=> adding docs for new download tools

reference/config_files/global_conf.rst
Closes: https://github.com/conan-io/docs/issues/2219
=> Remove quotes in conf docs

faq/troubleshooting.rst
Per issue [#9804](https://github.com/conan-io/conan/issues/9804) with PR [#10089](https://github.com/conan-io/conan/pull/10089) on conan.io/conan.
=> Updated troubleshoot.rst to have the updated error message for conan search

introduction.rst
This PR suggests a few wording changes that I think help the readability of the introduction documentation a little bit.
=> Grammar Upgrades to Introduction Documentation

reference/conanfile/tools/cmake/cmakedeps.rst
Docs for https://github.com/conan-io/conan/pull/9958
=> remove cmakedeps configurations

reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/config_files/settings.yml.rst
Docs for https://github.com/conan-io/conan/pull/10057 and (https://github.com/conan-io/conan/pull/10028, superseded)
=> fixed msvc versions

conan_v2.rst, reference/conanfile/tools/gnu/pkgconfigdeps.rst
Docs for: https://github.com/conan-io/conan/pull/10084
=> Added `pkg_config_name` and `pkg_config_aliases` information

reference/conanfile/tools/gnu.rst, reference/conanfile/tools/gnu/pkgconfig.rst
Docs for https://github.com/conan-io/conan/pull/10065
=> pkg_config new docs

conan_v2.rst
Docs for: https://github.com/conan-io/conan/pull/10016
=> add new import to 2.0 guide

reference/conanfile/tools/meson.rst
docs for https://github.com/conan-io/conan/pull/9990
=> Feature: add backend support to MesonToolchain

conan_v2.rst
Fix https://github.com/conan-io/docs/issues/2321
=> fix properties description in v2 migrate guide

versioning/version_ranges.rst
Closes https://github.com/conan-io/docs/issues/2335#issuecomment-1001908541
=> Remove ~= from versioning

reference/generators/json.rst
PR https://github.com/conan-io/conan/pull/10203
=> Add build_modules/build_modules_paths to docs

reference/conanfile/tools/cmake/cmaketoolchain.rst
Docs for https://github.com/conan-io/conan/pull/10213
=> CMakeToolchainBlock not necessary

reference/tools.rst
Docs for https://github.com/conan-io/conan/pull/10114
=> docs for Git.version property

integrations/cross_platform/yocto.rst
- Update Mosquitto version to offcial one from Conan Center
- Give option of using `-g deploy` instead of explicit method
- Add bitbake commands as alternative
=> Yocto: Update Mosquitto version

devtools/build_requires.rst, reference/commands/creator/create.rst
Docs for https://github.com/conan-io/conan/pull/10171
=> Explicit test package

conan_v2.rst, reference/conanfile/tools.rst, reference/conanfile/tools/files/symlinks.rst
Docs for https://github.com/conan-io/conan/pull/10154/files
=> Symlink tools

reference/conanfile/tools/microsoft.rst
Related to https://github.com/conan-io/conan/pull/10310
=> Document microsoft.is_msvc

creating_packages/define_abi_compatibility.rst, versioning/version_ranges.rst
Some good questions came up in https://github.com/conan-io/conan-center-index/pull/8831 and I could not find the answer in the docs. Since I dug in the GitHub issues and found my answer figured it was worth add to the docs
I picked the two obvious spot where I first looked
As always feedback is welcomed 🙏
=> Package id is not affected by version ranges

reference/conanfile/methods.rst, reference/conanfile/tools.rst, reference/conanfile/tools/system/package_manager.rst, reference/config_files/global_conf.rst
Docs for:
- https://github.com/conan-io/conan/pull/10469
- https://github.com/conan-io/conan/pull/10467
- https://github.com/conan-io/conan/pull/10380
=> New implementation for system package manager tools

reference/config_files/settings.yml.rst
Docs for: https://github.com/conan-io/conan/pull/10457
=> remove vs2022 as msvc

reference/conanfile/tools/microsoft.rst
Related to https://github.com/conan-io/conan/pull/10437
=> Add is_msvc_static_runtime

reference/conanfile/tools/google.rst
Docs for https://github.com/conan-io/conan/pull/10391
=> Docs for https://github.com/conan-io/conan/pull/10391

reference/conanfile/tools/files.rst
=> Docs for #10408

reference/commands/consumer/install.rst, reference/commands/development/editable.rst
Docs for https://github.com/conan-io/conan/pull/10274
=> doc --output-folder

reference/conanfile/tools/gnu/pkgconfigdeps.rst
Docs for: https://github.com/conan-io/conan/pull/10344 https://github.com/conan-io/conan/pull/10263
=> [PkgConfigDeps] Duplicated names order

reference/conanfile/tools/cmake/cmaketoolchain.rst
[#10186](https://github.com/conan-io/conan/pull/10186)
https://github.com/conan-io/docs/pull/2365 is also related
=> Docs for 10186

reference/conanfile/tools/meson.rst
Docs for: 
- https://github.com/conan-io/conan/pull/10174 
- https://github.com/conan-io/conan/pull/10405
=> Updating MesonToolchain information

.ci/test.jenkins
=> Send slack alert when broken links

extending/python_requires.rst
Close https://github.com/conan-io/conan/issues/10511
=> clarification about python_requires_extend

reference/conanfile/dependencies.rst
=> Remove warning about dependencies bug

reference/conanfile/tools/gnu/autotoolstoolchain.rst
When merged: https://github.com/conan-io/conan/pull/10631/files
=> Customize environment at AutotoolsToolchain

tutorial/consuming_packages/getting_started/build_simple_cmake_project.rst
Goes with this: https://github.com/conan-io/examples2/pull/4
=> Minor changes in Conan 2.0 tutorial

reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/gnu/autotoolstoolchain.rst
https://github.com/conan-io/conan/pull/10672
=> Docs for outputdirs in toolchains

conan_v2.rst
Closes https://github.com/conan-io/docs/issues/2416
=> Migration guide for removing settings

reference/conanfile/tools/cmake/cmake.rst
Docs for https://github.com/conan-io/conan/pull/10573
=> new CMake cli args

conan_v2.rst, reference/conanfile/tools/files.rst, reference/conanfile/tools/files/basic.rst, reference/conanfile/tools/files/checksum.rst
Docs for https://github.com/conan-io/conan/pull/10530
=> missing tools and copy

reference/conanfile/tools/apple.rst, reference/conanfile/tools/cmake.rst, reference/conanfile/tools/cmake/cmake.rst, reference/conanfile/tools/cmake/cmake_layout.rst, reference/conanfile/tools/cmake/cmakedeps.rst, reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/env.rst, reference/conanfile/tools/env/environment.rst, reference/conanfile/tools/env/envvars.rst, reference/conanfile/tools/env/virtualbuildenv.rst, reference/conanfile/tools/env/virtualrunenv.rst, reference/conanfile/tools/files.rst, reference/conanfile/tools/gnu.rst, reference/conanfile/tools/gnu/autotools.rst, reference/conanfile/tools/gnu/autotoolsdeps.rst, reference/conanfile/tools/gnu/autotoolstoolchain.rst, reference/conanfile/tools/gnu/pkgconfig.rst, reference/conanfile/tools/gnu/pkgconfigdeps.rst, reference/conanfile/tools/layout.rst, reference/conanfile/tools/meson/meson.rst, reference/conanfile/tools/microsoft.rst
Close https://github.com/conan-io/docs/issues/2351
=> modified experimental warning

reference/conanfile/tools.rst, reference/conanfile/tools/build.rst, reference/conanfile/tools/scm.rst, reference/conanfile/tools/scm/other.rst
Docs for https://github.com/conan-io/conan/pull/10536
=> Docs for 10536

tutorial/consuming_packages/getting_started.rst, tutorial/consuming_packages/getting_started/build_simple_cmake_project.rst, tutorial/consuming_packages/getting_started/build_tools_as_conan_packages.rst, tutorial/consuming_packages/getting_started/use_tools_as_conan_packages.rst
=> Tool requires docs

conan_v2.rst
use new conan import in example
=> remove "from conans" in conan 2.0 example

reference/commands/consumer/install.rst
Removing `[-sf SOURCE_FOLDER]` from arguments as it's not supported by the command.
=> Update install.rst, removing `[-sf SOURCE_FOLDER]`

reference/conanfile/tools/files/basic.rst
Docs for [#10874 ](https://github.com/conan-io/conan/pull/10874)
=> rmdir tool

reference/conanfile/tools/apple.rst
Docs for: https://github.com/conan-io/conan/pull/10799
=> Docs for support for different targets in XcodeBuild

reference/conanfile/tools/microsoft.rst
https://github.com/conan-io/conan/pull/10743
=> Docs for 10743

reference/conanfile/tools/meson/mesontoolchain.rst
Docs for https://github.com/conan-io/conan/pull/10908
=> [MesonToolchain] Cross-compilation for Android

reference/conanfile/tools/files/patches.rst
https://github.com/conan-io/conan/pull/10875
=> Docs for 10875

extending/template_system/command_new.rst
Docs for: https://github.com/conan-io/conan/pull/10760
=> Add docs for conan new --template=msbuild_lib|exe

reference/conanfile/tools/microsoft.rst
Docs for: https://github.com/conan-io/conan/pull/10898
=> Add docs for support for clang to msvc_runtime_flag()

migrating_to_2.0/recipes.rst
Docs for https://github.com/conan-io/conan/pull/10734
=> New from conan.errors import XXX namespace migration note

reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/gnu/autotoolstoolchain.rst, reference/conanfile/tools/meson/mesontoolchain.rst, reference/config_files/global_conf.rst
Docs for https://github.com/conan-io/conan/pull/10800 https://github.com/conan-io/conan/pull/10928
=> [conf] Global conf flags

reference/conanfile/attributes.rst, reference/profiles.rst
Close https://github.com/conan-io/docs/issues/2457
=> Docs for self.conf

reference/conanfile/attributes.rst, reference/conanfile/methods.rst
https://github.com/conan-io/conan/pull/10091
=> Docs for 10091

reference/conanfile/tools/cmake/cmake_layout.rst, reference/conanfile/tools/cmake/cmaketoolchain.rst
https://github.com/conan-io/conan/pull/11112
https://github.com/conan-io/conan/pull/11117
https://github.com/conan-io/conan/pull/11103
=> Docs for 11112 and 11117 and 11103

reference/conanfile/tools/microsoft.rst
Docs for https://github.com/conan-io/conan/pull/10972
=> [MSBuildToolchain][conf] Adding extra flags configurations to `MSBuildToolchain`

reference/conanfile/tools/env/envvars.rst
Docs for https://github.com/conan-io/conan/pull/11061
=> powershell env docs

reference/conanfile/tools/gnu/autotools.rst
Docs for: https://github.com/conan-io/conan/pull/11114
=> Some notes about relocatable libs

reference/conanfile/tools/gnu/autotoolstoolchain.rst
Docs for https://github.com/conan-io/conan/pull/11063
=> Docs: Add PKG_CONFIG_PATH to AutotoolsToolchain

tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/different_configurations.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst
Related to: https://github.com/conan-io/examples2/pull/14
=> Fix tutorial cmake commands without -DCMAKE_BUILD_TYPE

reference/conanfile/tools/cmake/cmake_layout.rst
Fixes a small copy/paste mistake in the docs.
=> Fix minor issue on cmake_layout doc page

README.md, introduction.rst, reference/python_api/api_warning.rst
Please check mainly the new ``Stable`` section
=> [develop2] Feature/introduction

tutorial/consuming_packages.rst, tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/cross_building_with_conan.rst, tutorial/consuming_packages/different_configurations.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst, tutorial/creating_packages/getting_started.rst
TODO: add some diagram depicting host and build context.
Goes with https://github.com/conan-io/examples2/pull/17
=> Tutorial cross building

developing_packages/package_layout.rst
This is a collection of minor
- improvements to grammar/wording
- indentation/whitespace fixes
for the Package Layout page.
=> Various minor tweaks to package_layout.rst

reference/conanfile_txt.rst
Docs for https://github.com/conan-io/conan/pull/11348
=> layout in conanfile txt 

creating_packages/getting_started.rst, integrations/cross_platform/android.rst, reference/conanfile/tools/cmake/cmake.rst, reference/conanfile/tools/cmake/cmakedeps.rst
Docs for https://github.com/conan-io/conan/pull/11294
=> docs for CMakeDeps build_type requirement

reference/conanfile/tools/files/basic.rst
Docs for https://github.com/conan-io/conan/pull/11330
=> copy tool symlinks

reference/conanfile/tools/cmake/cmaketoolchain.rst
Docs for https://github.com/conan-io/conan/pull/11147
=> add conf toolset_arch

reference/conanfile/tools/microsoft.rst
Docs for https://github.com/conan-io/conan/pull/11292
=> add check_min_vs()

reference/tools/build.rst
Docs for https://github.com/conan-io/conan/pull/11378
=> Added `can_run` function

reference/tools.rst, reference/tools/microsoft.rst, reference/tools/microsoft/helpers.rst, reference/tools/microsoft/msbuild.rst, reference/tools/microsoft/msbuilddeps.rst, reference/tools/microsoft/msbuildtoolchain.rst, reference/tools/microsoft/vcvars.rst, reference/tools/microsoft/visual_layout.rst
Related to https://github.com/conan-io/conan/pull/11283
=> Reference for `conan.tools.microsoft` classes and functions

reference/tools.rst, reference/tools/system.rst, reference/tools/system/package_manager.rst
Merge https://github.com/conan-io/conan/pull/11337 before this one
=> Add tools system package manager

reference/tools/files/basic.rst, reference/tools/files/downloads.rst, tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/different_configurations.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst, tutorial/creating_packages/create_your_first_package.rst, tutorial/creating_packages/handle_sources_in_packages.rst
Goes with: https://github.com/conan-io/examples2/pull/22
=> Creating packages - handling sources tutorial

reference/tools/build.rst, tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/creating_packages/add_dependencies_to_packages.rst
Examples: https://github.com/conan-io/examples2/pull/23
=> Add requirements to creating packages tutorial

index.rst, tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.rst
Note: Do not merge with squash
=> Update develop2 with changes in release branch

reference/tools/files/basic.rst, tutorial/creating_packages/preparing_the_build.rst
=> Merge release2 back to develop2

examples.rst, examples/extensions/commands/clean/custom_command_clean_revisions.rst, examples/extensions/commands/custom_commands.rst, reference/commands.rst, reference/commands/custom_commands.rst, reference/python_api/ConanAPIV2.rst
=> Merge beta release branch to develop2

migrating_to_2.0/recipes.rst
Close https://github.com/conan-io/docs/issues/2594
=> Usage of self.info in the validate() method

.ci/publish.jenkins, conan_v2.rst, index.rst
=> Master to develop

reference/tools/cmake/cmake_layout.rst, reference/tools/cmake/cmaketoolchain.rst, reference/tools/files/basic.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst
Merge with https://github.com/conan-io/conan/pull/11545
=> Docs from 1.50 introduced changes

tutorial/creating_packages/handle_sources_in_packages.rst
I think it is nice to do a better "patching the sources" read more to introduce first the conandata.
WIth https://github.com/conan-io/examples2/pull/32
=> Using conandata.yml to retrieve sources

examples.rst, examples/tools/files/files.rst, examples/tools/files/patches/patch_sources.rst, reference/tools/files/patches.rst, tutorial/creating_packages/handle_sources_in_packages.rst
https://github.com/conan-io/examples2/pull/33
=> Docs for Example patching sources

migrating_to_2.0/recipes.rst, reference/conanfile/tools/files/basic.rst
Close https://github.com/conan-io/docs/issues/2641
Close https://github.com/conan-io/docs/issues/2640
=> fix several issues

developing_packages/editable_packages.rst
Close https://github.com/conan-io/docs/issues/2645
=> fixing editable docs

reference/conanfile/tools/cmake/cmake_layout.rst
Same as https://github.com/conan-io/docs/pull/2649 to "master" 1.X docs
=> Fix build_folder_vars windows

migrating_to_2.0/recipes.rst, reference/conanfile/tools/system/package_manager.rst
Also maybe would be useful to add this to c3i docs
=> Some notes about migrating from SystemPackageTool to new tools

reference/conanfile/tools/cmake/cmaketoolchain.rst
https://github.com/conan-io/conan/blob/6a6ff6e07526b05d51998a5c5ed54936f0fd7ff9/conans/test/functional/toolchains/cmake/test_cmake_toolchain.py#L137-L139
=> Preset names are lowercase

examples/extensions/commands/clean/custom_command_clean_revisions.rst, reference/commands/custom_commands.rst
Linked examples2: https://github.com/conan-io/examples2/pull/37
=> [dev2] Updated CLI imports

.ci/publish.jenkins, changelog.rst, conf.py
Not merge with squash 
Wait until 1.50.1 is released
=> conan 1.50.1 docs

reference/conanfile/attributes.rst, reference/tools/microsoft/msbuilddeps.rst
=> MSBuildDeps components

reference/tools/meson.rst, reference/tools/meson/mesondeps.rst, reference/tools/meson/mesontoolchain.rst
Porting:
- https://github.com/conan-io/docs/pull/2654
- https://github.com/conan-io/docs/pull/2652
=> Update meson docs in develop2

reference/tools/system/package_manager.rst
Port https://github.com/conan-io/docs/pull/2663 to develop2
=> [develop2] Update changes with system.package_manager

reference/tools/build.rst, tutorial/creating_packages/add_dependencies_to_packages.rst, tutorial/creating_packages/preparing_the_build.rst
This pull request would add documentation for the tooling to check the max cppstd, as indicated by conan-io/conan#11080
=> Add docs for check_max_cppstd and valid_max_cppstd

.ci/publish.jenkins, changelog.rst, conf.py
Do not merge until 1.51.1 released
Merge without squash
=> Conan 1.51.1 docs

reference/conanfile/tools/scm/other.rst
Docs for https://github.com/conan-io/conan/pull/11823
Note if CI fails: Added URL `1.52.0 <https://github.com/conan-io/conan/releases/tag/1.52.0>` that it does not exist for now.
=> `tools.scm.Version` public properties

reference/conanfile/tools/microsoft.rst
From this question https://github.com/conan-io/conan/issues/11875
=> HOTFIX master: Clarify MSBuild helper attributes

reference/conanfile/tools/apple.rst, reference/conanfile/tools/scm/other.rst
Docs for: https://github.com/conan-io/conan/pull/11896
=> Add is_apple_os

reference/conanfile/tools/files/basic.rst
Maybe not appropriate in `basic` section of tools.files, but which one?
=> Document `conan.tools.files.collect_libs()`

uploading_packages/running_your_server.rst
This addresses https://github.com/conan-io/conan/issues/5758.
=> Document custom authorizers

reference/conanfile/tools/cmake/cmaketoolchain.rst
Docs for https://github.com/conan-io/conan/pull/11935
=> add BUILD_TESTING to cmake presets

reference/conanfile/tools/microsoft.rst
Close https://github.com/conan-io/conan/pull/11949
=> docs for is_msvc(build_context)

reference/conanfile/tools/apple.rst
Docs for: https://github.com/conan-io/conan/pull/11818
=> Document PACKAGE_ROOT_ in XcodeDeps

reference/conanfile/tools/scm/other.rst
Docs for: https://github.com/conan-io/conan/pull/11928
=> Add conan_version

migrating_to_2.0/recipes.rst
Docs for https://github.com/conan-io/conan/pull/11934
=> requirement traits

reference/conanfile/dependencies.rst
Docs for https://github.com/conan-io/conan/pull/11868
=> new dependencies interface

reference/commands/consumer/config.rst
Docs for: https://github.com/conan-io/conan/pull/11936
=> Support remotes.json in 1.X docs

reference/conanfile/tools/cmake/cmake_layout.rst
Docs for https://github.com/conan-io/conan/pull/11889
=> docs for cmake_layout(build_folder)

reference/conanfile/tools/apple.rst
Docs for: https://github.com/conan-io/conan/pull/11915
=> Add documentation for conan.tools.apple.to_apple_arch

reference/conanfile/tools/scm/git.rst
Add documentation for the new `args` function argument.
Docs for: https://github.com/conan-io/conan/pull/11921
=> Update reference for tools.scm.Git.clone()

migrating_to_2.0/recipes.rst
Closes: https://github.com/conan-io/docs/issues/2657
=> Add export_sources to v2 migration

reference/conanfile/tools/microsoft.rst
Docs for https://github.com/conan-io/conan/pull/11968
=> Add ``MSBuild.build(..., targets=[mytarget])`` targets argument

reference/config_files/global_conf.rst
Related to Conan issue: https://github.com/conan-io/conan/issues/11918
=> Configuration patterns

reference/conanfile/tools/env.rst, reference/conanfile/tools/env/environment.rst, reference/config_files/global_conf.rst, reference/profiles.rst
Closes: https://github.com/conan-io/docs/issues/2623
=> `[buildenv]` section

reference/conanfile/tools/gnu/pkgconfigdeps.rst
Docs for https://github.com/conan-io/conan/pull/11979
=> [PkgConfigDeps] Tool requires

creating_packages/define_abi_compatibility.rst, migrating_to_2.0/recipes.rst, reference/conanfile/methods.rst
Closes: https://github.com/conan-io/docs/issues/2481
=> Start documenting compatibility

reference/tools/files/basic.rst
To be merged in beta3
https://github.com/conan-io/docs/pull/2610
=> Port #2610 to develop2

conan_v2.rst
I was looking for this information I was not able to find it.
Let me know if there's a better place (this is just where I first looked)
=> Add a mention to the V2 beta remote

howtos.rst, howtos/using_rrev_and_lockfiles.rst, versioning/lockfiles/configurations.rst
This is currently the docs from ConanCenter but I felt it was so generic it would be easier to move it here.
This is mostly the bottom half of https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md#isolate-your-project-from-upstream-changes
=> How to use recipe revision and lockfiles

migrating_to_2.0/recipes.rst, reference/conanfile/tools/microsoft.rst
Closes: https://github.com/conan-io/docs/issues/2742
=> Some clarifications to v2 migration guide

integrations/ci/jenkins.rst
=> Hotfix for Jenkins DSL

reference/conanfile/tools/cmake/cmakedeps.rst
tried my best to capture the suggestions in https://cpplang.slack.com/archives/C41CWV9HA/p1660400359989449
//cc @SpaceIm
=> docs: How to disable CMakeDeps and provide your own find_package modules

reference/tools/files/basic.rst, reference/tools/microsoft/msbuild.rst
To merge after release beta3
Without squash
=> Merge develop2 to release/2.0.0-beta

reference/conanfile/tools/scm/git.rst
Docs: https://github.com/conan-io/conan/pull/12165
Note: take also to develop2!
=> Add git.run() docs

reference/conanfile/tools/apple.rst
Docs: https://github.com/conan-io/conan/pull/12172
Note: take also to develop2 docs!
=> Add xcrun docs

migrating_to_2.0/recipes.rst, reference/conanfile/attributes.rst
Docs for: https://github.com/conan-io/conan/pull/12094
=> Add rm_safe docs

reference/commands/creator/create.rst
Merge on master branch, as it's not a new stuff. 
closes #2737
/cc @SpaceIm
=> Update conan create command method list

migrating_to_2.0/recipes.rst, reference/conanfile/attributes.rst, systems_cross_building/cross_building.rst
=> When ANY option is None by default, None should be listed as options values

reference/conanfile/tools/microsoft.rst
Docs for: https://github.com/conan-io/conan/pull/12147
=> Add docs for MSBuildToolchain.properties

migrating_to_2.0/recipes.rst
Docs for: https://github.com/conan-io/conan/pull/12030
=> Document new cpp_info.libdir/bindir/includedir interface to libdirs[0]

reference/profiles.rst
Docs for https://github.com/conan-io/conan/pull/12230
=> Add docs for [runenv] profile section

reference/tools/files/basic.rst, tutorial/creating_packages/build_packages.rst
As this is not directly related with any feature in 2.0 we can merge it
=> Publish build() method 2.0 docs

reference/conanfile/tools/cmake/cmaketoolchain.rst
=> Take master to develop

_themes/conan/layout.html
Been a while since I've seen one, let me know if this is too much or just right (or too short).
=> Enable announcement banner for "cooking with Conan" event

reference/conanfile/tools/scm/git.rst
Docs for: https://github.com/conan-io/conan/pull/12295
=> new Git.included_files()

reference/conanfile/tools/gnu/autotoolstoolchain.rst
Closes: https://github.com/conan-io/docs/issues/2795
=> Fix --prefix default value in AutoolsToolchain docs

reference/conanfile/tools/gnu/autotools.rst, reference/conanfile/tools/microsoft.rst
Docs for https://github.com/conan-io/conan/pull/12193
=> Fix autotools install on Windows

reference/conanfile/attributes.rst, reference/tools.rst, reference/tools/apple/other.rst, reference/tools/cmake/cmaketoolchain.rst, reference/tools/gnu/autotoolstoolchain.rst, reference/tools/microsoft/helpers.rst, reference/tools/scm.rst
Needs: https://github.com/conan-io/conan/pull/12493
=> Add missing docs for develop2

versioning/version_ranges.rst
See discussion at https://github.com/conan-io/conan/issues/12519
=> Add caret version range semver example

reference/config_files/settings.yml.rst
Docs for: https://github.com/conan-io/conan/pull/12562
=> Update settings.yml in docs

reference/conanfile/tools/gnu/autotools.rst
Docs for: https://github.com/conan-io/conan/pull/12491
=> Add target argument to Autotools.install()

reference/conanfile/tools/cmake/cmakedeps.rst
Docs for: https://github.com/conan-io/conan/pull/12609
=> Docs for CMakeDeps properties from consumer

reference/conanfile/tools/meson/meson.rst
Docs for https://github.com/conan-io/conan/pull/12117
=> [Meson] Meson extra machine files

reference/conanfile/tools/meson/mesontoolchain.rst
Closes https://github.com/conan-io/docs/issues/2733
=> MesonToolchain: Add minimum meson version suitable for the generated file

reference/conanfile/tools/microsoft.rst
Docs for:
- https://github.com/conan-io/conan/pull/12599
- https://github.com/conan-io/conan/pull/12516
=> nmake new integration docs

reference/conanfile/tools/env/envvars.rst
Docs for https://github.com/conan-io/conan/pull/12517
=> allow template placeholder in EnvVars

reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/gnu/autotoolstoolchain.rst, reference/conanfile/tools/meson/mesontoolchain.rst
Docs for https://github.com/conan-io/conan/pull/12556 (and https://github.com/conan-io/conan/pull/12635)
=> Added `tools.build:compiler_executables` conf

README.md, developing_packages/package_layout.rst, devtools/build_requires.rst, extending/python_requires.rst, extending/template_system/info_graph.rst, integrations/cross_platform/ios.rst
These are some of the low hanging typos I've found today. I've committed them mostly to check that my setup is ok, and to learn workflow for these cases.
Should I now check if they are present in develop2 and merge there too? Or is the process different?
=> Fix some of the minor typos found while reading the docs

conan_v2.rst, installation.rst, migrating_to_2.0/commands.rst, migrating_to_2.0/properties.rst, migrating_to_2.0/recipes.rst
Next PR will be the things that I've found in the 2.0 docs, but this was some low hanging fruit I found while reading the migration docs
=> Improve some wording on Migration to Conan 2.0 docs

.ci/publish.jenkins, README.md, changelog.rst, conan_v2.rst, conf.py, developing_packages/package_layout.rst, devtools/build_requires.rst, extending/python_requires.rst, extending/template_system/info_graph.rst, installation.rst, integrations/cross_platform/ios.rst, migrating_to_2.0/commands.rst, migrating_to_2.0/properties.rst, migrating_to_2.0/recipes.rst
- Do not merge until released
- Merge without squash
=> Docs for 1.56.0 release

reference/conanfile/methods.rst
Fix https://github.com/conan-io/docs/issues/2866
=> fix layout() source folder description

reference/tools/build.rst, tutorial/creating_packages.rst, tutorial/creating_packages/other_types_of_packages/header_only_packages.rst, tutorial/creating_packages/test_conan_packages.rst
Goes with: https://github.com/conan-io/examples2/pull/54
=> Add basic test_package docs

reference.rst, reference/conanfile_txt.rst, reference/tools.rst
Docs for https://github.com/conan-io/conan/pull/12699
=> [develop2] conanfile_txt

tutorial/consuming_packages/intro_to_versioning.rst, tutorial/creating_packages/create_your_first_package.rst, tutorial/creating_packages/other_types_of_packages/header_only_packages.rst, tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.rst
changes in the conan list left the docs outdated, examples2 are already fixed
=> Fix tutorial conan list

reference/commands/list.rst
Docs for https://github.com/conan-io/conan/pull/12756
=> Added list reference

migrating_to_2.0/recipes.rst, reference/conanfile/methods.rst
follow up to https://github.com/conan-io/conan-center-index/pull/13896#discussion_r1061050561
=> docs: update usage of `self.info` for validate and package_id

reference/conanfile/tools/microsoft.rst
Docs for https://github.com/conan-io/conan/pull/12887
=> Add documentation for unix_path_package_info_legacy

reference/conanfile/tools/microsoft.rst
Adds info about the new argument for `check_min_vs` function
=> Add docs for new argument for `check_min_vs` function

reference/conanfile/tools/cmake/cmaketoolchain.rst, reference/conanfile/tools/gnu/autotoolstoolchain.rst, reference/conanfile/tools/meson/mesontoolchain.rst, reference/config_files/global_conf.rst
Documentation for conan-io/conan#12854
=> Add tools.build:linker_scripts conf variable

reference/conanfile/tools/gnu/autotoolstoolchain.rst
Docs for https://github.com/conan-io/conan/pull/12884 https://github.com/conan-io/conan/pull/12889
=> [AutotoolsToolchain] `update_xxxx_args` information

reference.rst, reference/conanfile.rst
We talked about this being a better ordering in some daily at some point.
=> Reorder Reference doc pages items

migrating_to_2.0/general.rst
=> docs: migration for hooks

reference/extensions/hooks.rst
Hiding all these from this page
=> [conan v2] docs: fix hook headings

reference/conanfile/tools/microsoft.rst
document https://github.com/conan-io/conan/pull/12665
=> [NMakeToolchain] Document new attributes, methods and behavior

reference/commands/config.rst, reference/tools/cmake/cmaketoolchain.rst, reference/tools/gnu/autotoolstoolchain.rst, reference/tools/meson/mesontoolchain.rst
- https://github.com/conan-io/docs/pull/2887/files
=> Port missing 1.57 docs to 2.0

reference/conanfile/attributes.rst, reference/conanfile/methods.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/creating_packages/build_packages.rst, tutorial/creating_packages/preparing_the_build.rst
https://github.com/conan-io/examples2/pull/67
=> [Conan2] remove .info from validate and others

conf.py
With this config, graphviz outputs svg by default. Works locally for me
=> Make Graphviz output svg

knowledge/faq.rst
For this: https://github.com/conan-io/conan/pull/13135/files
=> Start troubleshooting and add missing binary error help

reference/conanfile/tools/scm/git.rst
Docs for https://github.com/conan-io/conan/pull/13096
=> Git.fetch_commit

reference/conanfile/tools.rst, reference/conanfile/tools/android.rst
Docs for https://github.com/conan-io/conan/pull/12873
=> android_abi()

reference/tools.rst, reference/tools/android.rst
Needs: https://github.com/conan-io/conan/pull/13148 to be rendered correctly
=> Add android abi docs

installation.rst
This is important, for users that don't want to depend on Python for installing
=> pyinstaller

.ci/publish.jenkins, _themes/conan/versions.html, create_redirects.py
Removing en folder for the 2.0 docs
Making every html under https://docs.conan.io/en/latest redirect to the same under https://docs.conan.io/1
=> Redirect latest to 1

reference/commands/inspect.rst, reference/commands/list.rst
* conan inspect info added
* conan list ... --format=html info added
=> inspect and list command updated

reference/extensions.rst
Forgot to add it when I first added the deployers
=> Add sentence about deployers in extensions

.ci/publish.jenkins
To be merged after 2.0 release
=> Redirect main docs to 2

.ci/test.jenkins, common/experimental_warning.inc, examples/tools/cmake/cmake_toolchain/build_project_cmake_presets.rst, examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets.rst, reference/commands/inspect.rst, reference/config_files/profiles.rst, reference/config_files/settings.rst, reference/extensions/python_api/ConanAPI.rst, reference/extensions/python_api/ConfigAPI.rst, reference/extensions/python_api/DownloadAPI.rst, reference/extensions/python_api/ExportAPI.rst, reference/extensions/python_api/GraphAPI.rst, reference/extensions/python_api/InstallAPI.rst, reference/extensions/python_api/ListAPI.rst, reference/extensions/python_api/NewAPI.rst, reference/extensions/python_api/ProfilesAPI.rst, reference/extensions/python_api/RemotesAPI.rst, reference/extensions/python_api/RemoveAPI.rst, reference/extensions/python_api/SearchAPI.rst, reference/extensions/python_api/UploadAPI.rst, tutorial.rst, tutorial/cmake_presets_note.inc, tutorial/developing_packages/editable_packages.rst, tutorial/developing_packages/local_package_development_flow.rst, tutorial/developing_packages/package_layout.rst
... and minor ci fix
... and fixing rst includes --> changed to .inc
=> Remove warning about pre-release version

_themes/conan/layout.html, _themes/conan/versions.html
=> Warn in docs if we are not in 2.X branches

reference.rst, reference/environment.rst
Close https://github.com/conan-io/conan/issues/13206
=> env-vars docs

.ci/publish.jenkins
It was still redirecting to /1, changing to /2
=> Minor fixes in publishing docs 404 page

tutorial/consuming_packages/cross_building_with_conan.rst, tutorial/consuming_packages/intro_to_versioning.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/creating_packages/other_types_of_packages/tool_requires_packages.rst
Also in examples2: https://github.com/conan-io/examples2/pull/79
=> tool_requires in build_requirements method 

reference/commands/build.rst
Docu change for https://github.com/conan-io/conan/pull/13211
=> Change documentation from conan-io/conan#13211

reference/conanfile/methods/configure.rst, tutorial/creating_packages/configure_options_settings.rst
=> Use rm_safe in configure() where it would break

reference/commands/lock.rst, reference/commands/lock/add.rst, reference/commands/lock/create.rst, reference/commands/lock/merge.rst
Close https://github.com/conan-io/docs/issues/3062
=> reference-commands-lock docs

reference/commands/graph/info.rst
=> Add documentation about graph info

reference/config_files/global_conf.rst
For https://github.com/conan-io/conan/pull/13377
=> Add note about conan_version new in 1.60

reference/commands/profile.rst
Docs for https://github.com/conan-io/conan/pull/13423
=> Remove profile arguments from conan profile path docs

.ci/Dockerfile, .ci/publish.jenkins, .ci/test.jenkins
Same as https://github.com/conan-io/docs/pull/3094 for master
=> Dont build ci-docs image in ci

.ci/Dockerfile, .ci/publish.jenkins, .ci/test.jenkins
=> Sync master to develop

conan_v2.rst
=> fix broken link between v2 and v1

conan_v2.rst
Changes from: https://github.com/conan-io/docs/pull/3099
=> Take #3099 changes to master 

knowledge/guidelines.rst
=> Sync release/2.0 -> develop2

conan_v2.rst
=> Sync master and develop

reference/commands/export-pkg.rst
Docs for https://github.com/conan-io/conan/pull/13324
=> export-pkg new args

migrating_to_2.0/recipes.rst
=> Fix extra 's' for conan package 2.0 for master

tutorial/consuming_packages/intro_to_versioning.rst
https://github.com/conan-io/docs/issues/3116
=> Introduction to versioning: conanv2 to conancenter

reference/conanfile/methods/init.rst
Docs for https://github.com/conan-io/conan/pull/13487
=> document ``self.options.update()`` for ``init()`` base class extension

examples/extensions/deployers/sources/custom_deployer_sources.rst
For #3119 but does not necessarily closes it
=> Give some more info on the custom deployer

tutorial/consuming_packages/cross_building_with_conan.rst, tutorial/consuming_packages/intro_to_versioning.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst
To merge after examples2 PR in https://github.com/conan-io/examples2/pull/85
This is better, so docs can use pre-compiled binaries from ConanCenter otherwise it is building from source
=> update cmake to 3.22.6

reference/extensions/command_wrapper.rst
Docs for https://github.com/conan-io/conan/pull/13564
=> add conanfile arg to cmd_wrapper()

reference/conanfile/methods/package_id.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst
Close https://github.com/conan-io/docs/issues/3139
Close https://github.com/conan-io/docs/issues/3133
=> minor fixes

examples/extensions/deployers/sources/custom_deployer_sources.rst, reference/extensions/deployers.rst
Together with https://github.com/conan-io/examples2/pull/89
=> fix deploy()

reference/commands/graph/info.rst, reference/commands/install.rst, reference/commands/lock/create.rst
Docs for https://github.com/conan-io/conan/pull/13669
=> Extend --build-require to more commands and cases docs

reference/conanfile/attributes/binary_model.inc, reference/config_files/global_conf.rst
=> Sync develop2 with release/2.0

reference/commands/graph/info.rst
Gets conan graph info up-to-date with newer info
=> Update conan graph info output

reference/config_files/global_conf.rst, reference/config_files/profiles.rst
Close https://github.com/conan-io/conan/issues/13747
=> conf scopes explanation

knowledge/faq.rst
show how to debug http connections and hint netrc
This solves https://github.com/conan-io/docs/issues/3181
=>  add: AuthenticationException

tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/intro_to_versioning.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst
Close https://github.com/conan-io/docs/issues/3116
=> fix conanv2 repo references

reference/conanfile/methods.rst, versioning/introduction.rst
Docs for https://github.com/conan-io/conan/pull/13719
=> tracking host version

reference/tools/cmake/cmakedeps.rst
Adding one example of the set_property for components from the generate() method.
=> Complete set_property docs to cover components case

examples/tools.rst, examples/tools/autotools/autotools.rst, examples/tools/autotools/autotools_toolchain/build_project_autotools_toolchain.rst, knowledge/faq.rst, knowledge/guidelines.rst, reference/commands/config.rst, reference/commands/graph/info.rst, reference/commands/remove.rst, reference/conanfile/attributes/binary_model.inc, reference/conanfile/methods/requirements.rst, reference/conanfile_txt.rst, reference/config_files/global_conf.rst, reference/config_files/profiles.rst, reference/tools/cmake/cmakedeps.rst, tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/intro_to_versioning.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst, tutorial/creating_packages/other_types_of_packages/header_only_packages.rst
=> Update develop2 with release/2.0

reference/commands/inspect.rst
https://github.com/conan-io/conan/pull/13716
=> `conan inspect` improvements

reference/config_files/global_conf.rst
Docs for https://github.com/conan-io/conan/pull/13746
=> `global.conf` initialization

knowledge/faq.rst
Close https://github.com/conan-io/conan/issues/13616
=> git line endings FAQ

examples/extensions/commands/clean/custom_command_clean_revisions.rst, reference/extensions/custom_commands.rst
Close https://github.com/conan-io/conan/issues/13935
=> improve docs custom commands

changelog.rst
There were some issues missing in the changelog.
=> Fix 2.0.5 changelog

conan_v2.rst, migrating_to_2.0/commands.rst
Closes: https://github.com/conan-io/docs/issues/3245
=> Some improvements to v2 migration guide

migrating_to_2.0/commands.rst
Closes: https://github.com/conan-io/docs/issues/3227
=> Some notes about new --format argument in 2.X

examples/cross_build/android/android_studio.rst
Related to: https://github.com/conan-io/conan/issues/13912
=> Update Android Studio tutorial

reference/conanfile/methods.rst, versioning/introduction.rst
Follow up on https://github.com/conan-io/docs/pull/3254#issuecomment-1589919718 since I doubt there will be a new 1.x release :)
=> Link the cheatsheet to the blog post

_themes/conan/layout.html
=> conan 1 increase warn

reference/tools/gnu/pkgconfigdeps.rst
Docs for https://github.com/conan-io/conan/pull/13623
=> Mentioned bindir variable

reference/tools/meson/mesontoolchain.rst
Docs for https://github.com/conan-io/conan/pull/14124
=> meson wrap opt-out

reference/commands/upload.rst
Docs for https://github.com/conan-io/conan/pull/14002
=> upload dry-run

reference/extensions/python_requires.rst
Docs for https://github.com/conan-io/conan/pull/14120
=> python_require super

examples/graph.rst, examples/graph/requires/consume_cmake_macro.rst, examples/graph/tool_requires/use_cmake_modules.rst
Docs for https://github.com/conan-io/conan/pull/14264
Can go directly to release/2.0, nothing really new from the release.
=> added example with cmake module inside tool_requires

reference/commands/editable.rst, tutorial/developing_packages/editable_packages.rst
Docs for https://github.com/conan-io/conan/pull/14358
It needs https://github.com/conan-io/examples2/pull/108 from examples2 to be merged
=> --build=editable docs

README.md
Add description section in README about useful branches when contributing to docs.
It should be replicated to other docs branches after merging this one.
Related to #3318
=> Add branches description

reference/conanfile/methods.rst
there was some light copy paste ;)
=> Fix the source methods description

reference/commands/inspect.rst
For https://github.com/conan-io/conan/pull/14596
=> Conan inspect changes

reference/commands/create.rst
Docs for https://github.com/conan-io/conan/pull/14347
=> Add build-test docs

reference/commands/inspect.rst
For https://github.com/conan-io/conan/pull/14572
=> Add new inspect flags

reference/commands/formatters/graph_info_json_formatter.rst
Docs for https://github.com/conan-io/conan/pull/14530
=> fix serialize traits booleans

reference/conanfile/methods/build_requirements.rst
Docs for https://github.com/conan-io/conan/pull/14394
=> doc test_requires(..., force=True)

installation.rst
Closes: https://github.com/conan-io/docs/issues/3205
=> Add a note about installing with pipx

examples/tools/cmake/cmake_toolchain/inject_cmake_variables.rst, reference/commands/create.rst
Address mismatch in example and a reStructuredText syntax mistake
=> Fix minor typos

reference/tools/files/basic.rst
It was a copy&paste from update_conandata
=> Fix trim_conandata() example

reference/tools/system/package_manager.rst
Docs for https://github.com/conan-io/conan/pull/14728
=> Update default check value for package managers

reference/extensions/profile_plugin.rst
Docs for https://github.com/conan-io/conan/pull/14682
=> Add docs for support clang-cl in default profile plugin

reference/conanfile/methods/build.rst
Related with: https://github.com/conan-io/conan/issues/14747
=> Add note about building but not running tests in cross-building

reference/config_files/settings.rst
For https://github.com/conan-io/conan/pull/14781
=> Add Clang 17 entry in settings.yml

devops.rst, devops/resolve_prereleases.rst, devops/versioning.rst, devops/versioning/resolve_prereleases.rst, tutorial/versioning/version_ranges.rst
I'm not 100% sold on th text I just wrote, but as discussed before, it's better than nothing :)
The graph looks like this:
=> Add docu describing the basic usage of the prerelease resolve conf

reference/commands/remove.rst
https://github.com/conan-io/conan/pull/14760
=> Remove update help

reference/tools/env/envvars.rst
=> Fix wrong Environment() construction in examples

tutorial/consuming_packages/build_simple_cmake_project.rst
Adding a note for the moment, so we give more visibility to this, maybe we can add a full example in the near future...
=> Add a note in the tutorial about compiler_executables conf

tutorial/consuming_packages/use_tools_as_conan_packages.rst
Closes: https://github.com/conan-io/docs/issues/3420
=> Add note about tool_requires in "Using build tools as Conan packages" docs

tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst
Closes: https://github.com/conan-io/docs/issues/3422
=> Some clarifications to the tutorial section

devops.rst, devops/metadata.rst, reference/commands/download.rst, reference/commands/upload.rst, reference/conanfile/attributes/folders.inc
Supersede https://github.com/conan-io/docs/pull/3283
=> Metadata docs

examples/graph/tool_requires/using_protobuf.rst, reference/conanfile/methods/build_requirements.rst, reference/conanfile/methods/package_id.rst
examples2 pr: https://github.com/conan-io/examples2/pull/118
Closes https://github.com/conan-io/docs/issues/3431
=> Use host_version for protobuf tool requires

devops/metadata.rst
Related to https://github.com/conan-io/conan/pull/15007/
Add new paragraph explaining that is possible to skip metadata upload.
=> [metadata] Ignore metadata upload by command argument

reference/commands/build.rst, reference/commands/create.rst, reference/commands/graph/build_order.rst, reference/commands/graph/info.rst, reference/commands/install.rst, reference/commands/lock/create.rst, reference/commands/profile.rst, reference/commands/test.rst
For https://github.com/conan-io/conan/pull/14727 and https://github.com/conan-io/conan/pull/14967
=> Update help commands to newer versions

reference/conanfile/attributes/binary_model.inc, reference/config_files.rst, reference/config_files/conanrc.rst, reference/environment.rst, tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst, tutorial/creating_packages/add_dependencies_to_packages.rst
=> Update develop2 with release/2.0 branch

reference/commands/cache.rst, reference/commands/list.rst
Docs for https://github.com/conan-io/conan/pull/15011
=> conan list --format=compact docs

reference/tools/gnu/autotoolstoolchain.rst
Docs for https://github.com/conan-io/conan/pull/15005
=> Add note for precedence of AutotoolsToolchain extraflags priority

reference/tools/cmake/cmaketoolchain.rst
Docs for https://github.com/conan-io/conan/pull/14966
=> Docs for adding extra flags to CMakeToolchain

reference/config_files/settings.yml.rst
Docs for https://github.com/conan-io/conan/pull/14865 and https://github.com/conan-io/conan/pull/14915
and some other that were not updated in docs when updated in the client
=> Update settings for changes in 1.62

migrating_to_2.0/commands.rst
Also a note in 2.0 docs: https://github.com/conan-io/docs/pull/3468
=> Add note in migration guide about aliases

reference/conanfile/attributes.rst
Also a note in migration guide: https://github.com/conan-io/docs/pull/3467
=> Note about aliases in 2.0 docs

reference/conanfile/attributes/binary_model.inc, reference/conanfile/attributes/build.inc, reference/conanfile/attributes/folders.inc, reference/conanfile/attributes/requirements.inc, reference/conanfile/attributes/sources.inc, reference/conanfile/methods/build_requirements.rst, reference/conanfile/methods/package_id.rst, reference/conanfile/methods/requirements.rst, reference/tools/env/environment.rst
Saw there were some pages written before we had all the links ready, this PR links to most of them (Only 2 remaining now)
=> Fix MISSING PAGE leftovers

reference/conanfile/methods/generate.rst
For https://github.com/conan-io/conan/pull/15221
=> `in` support for `self.dependencies` docs

reference/commands/export.rst, tutorial/other_features.rst
Docs for https://github.com/conan-io/conan/pull/15266
=> Add pkglist formatter for conan export command docs

reference/tools/cmake/cmakedeps.rst
Docs for https://github.com/conan-io/conan/pull/15207
=> cmakedeps_legacy

reference/environment.rst
Docs for https://github.com/conan-io/conan/pull/15263
=> CONAN_LOG_LEVEL envvar

reference/commands/install.rst, reference/conanfile/methods.rst, reference/conanfile/methods/deploy.rst
Docs for https://github.com/conan-io/conan/pull/15172
=> deploy() method

reference/conanfile/attributes/sources.inc
Docs for https://github.com/conan-io/conan/pull/15319
=> Document change default for source_buildenv

changelog.rst, conf.py
=> Conan 2.0.17 docs

changelog.rst, conf.py, reference/conanfile/attributes/sources.inc, reference/config_files/profiles.rst
=> Release branch to develop2

changelog.rst
Picking changes from: https://github.com/conan-io/docs/pull/3513
=> Restore space-time continuum

reference/binary_model/dependencies.rst
That λ is causing some problems when generating the pdf
=> Remove unicode character

reference/config_files/profiles.rst
For https://github.com/conan-io/conan/pull/15535
=> Add pattern-to-pattern replace example

reference/config_files/profiles.rst
For https://github.com/conan-io/conan/pull/15435
=> Add `detect_msvc_update()` doc reference

reference/commands/new.rst
Close https://github.com/conan-io/docs/issues/3525
=> New templates docs

reference/tools/cmake/cmaketoolchain.rst
Docs for https://github.com/conan-io/conan/pull/15470
=> Add docs for presets_build/run_environment

reference/conanfile/attributes.rst, reference/extensions/binary_compatibility.rst
Docs for https://github.com/conan-io/conan/pull/15348
=> extension properties

reference/binary_model/extending.rst, reference/conanfile/attributes/binary_model.inc, reference/config_files/settings.rst
Docs for https://github.com/conan-io/conan/pull/15415
=> nested ANY settings

reference/commands/graph/build_order.rst
Docs for https://github.com/conan-io/conan/pull/15270
=> [build-order] Added --order xxx parameter

reference/commands/formatters/graph_info_json_formatter.rst
Docs for conan-io/conan#15553
Added the new fields in the output graph.
Not sure if there is anything else to update...
=> Docs for 15553: Add self.info information to serialized output in the graph

migrating_to_2.0/recipes.rst
document and close #3539
Not sure if this is the best place nor branch.
It appears that another PR for might be needed for a new HOWTO that should target the develop2 branch
=> Document the migration of the version variable for conan 2

tutorial/versioning/version_ranges.rst
Close https://github.com/conan-io/docs/issues/3566
=> clarify version lowercases

reference/tools/cmake/cmaketoolchain.rst
For https://github.com/conan-io/conan/pull/15572
=> Add documentation for tools.cmake.cmaketoolchain:toolset_cuda

tutorial/consuming_packages/build_simple_cmake_project.rst
=> Use quotes for `conan_toolchain.cmake`

_ext/autocommand.py, conf.py, tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/different_configurations.rst, tutorial/creating_packages/add_dependencies_to_packages.rst, tutorial/creating_packages/build_packages.rst, tutorial/creating_packages/configure_options_settings.rst, tutorial/creating_packages/create_your_first_package.rst, tutorial/creating_packages/preparing_the_build.rst
=> Merge release/2.0 to develop2

reference/commands/graph/build_order.rst
Docs for https://github.com/conan-io/conan/pull/15602
=> Documen order-by argument for conan graph build-order

reference/commands/graph/build_order.rst, reference/commands/graph/build_order_merge.rst
Docs for https://github.com/conan-io/conan/pull/15573
=> build-order --reduce

reference/conanfile/attributes/binary_model.inc
Docs for https://github.com/conan-io/conan/pull/15571
=> important! options!

reference/commands/install.rst
Addresses https://github.com/conan-io/docs/pull/3587#pullrequestreview-1882048233
=> Tiny examples for --upload

reference/config_files/profiles.rst
This goes to 2.1 to improve the current documentation
Thanks to Tim on slack for bringing it to our attention :)
=> Improve profile package pattern documentation

examples/tools/cmake/cmake.rst, examples/tools/cmake/cmake_toolchain/use_package_config_cmake.rst, reference/tools/cmake/cmaketoolchain.rst
=> Sync develop2 with release/2.1

examples/cross_build/android/ndk.rst
=> Sync release/2.1 with develop2 branch

examples/cross_build.rst, examples/cross_build/toolchain_packages.rst, reference/conanfile/methods/source.rst, tutorial/consuming_packages/cross_building_with_conan.rst, tutorial/creating_packages/other_types_of_packages.rst, tutorial/creating_packages/other_types_of_packages/toolchain_packages.rst
Example in https://github.com/conan-io/examples2/pull/138
Closes: https://github.com/conan-io/docs/issues/3208
=> Creating a toolchain package docs

reference/extensions/python_api.rst, reference/extensions/python_api/CommandAPI.rst
It's empty for now, as we don't want to document any of it until it stabilizes
For https://github.com/conan-io/conan/pull/15630
=> Add CommandAPI reference

reference/commands/graph.rst, reference/commands/graph/outdated.rst
Docs for https://github.com/conan-io/conan/pull/15838: Add `conan graph outdated` subcommand
=> Add conan graph outdated subcommand

knowledge/faq.rst, reference/binary_model/extending.rst, reference/conanfile/attributes/binary_model.inc, reference/conanfile/methods/requirements.rst, tutorial/versioning/conflicts.rst
Docs for https://github.com/conan-io/conan/pull/15876
=> options conflicts

reference/tools/cmake/cmaketoolchain.rst
Close https://github.com/conan-io/docs/issues/3651
=> fix cmaketoolchain blocks

changelog.rst, conf.py
=> Conan 2.2.2 docs

changelog.rst, conf.py, reference/tools/cmake/cmaketoolchain.rst
=> Sync develop2 with release branch

.ci/scripts/common.py, reference/commands/consumer/install.rst, reference/tools.rst, requirements.txt
=> Sync develop with master

reference/commands/creator/export-pkg.rst
Docs for https://github.com/conan-io/conan/pull/15741
=> export-pkg --output-folder

reference/conanfile/tools/meson/meson.rst, reference/conanfile/tools/meson/mesontoolchain.rst
Docs for https://github.com/conan-io/conan/pull/15706
=> [Meson] Added `--destdir` doc

.ci/scripts/common.py, changelog.rst, conf.py, reference/commands/creator/export-pkg.rst, reference/conanfile/tools/build.rst, reference/conanfile/tools/meson/meson.rst, reference/conanfile/tools/meson/mesontoolchain.rst
- Merge after release without squash
=> Conan 1.64.0 docs

examples/tools/autotools/autotools.rst, examples/tools/cmake/cmake.rst, examples/tools/files/files.rst, examples/tools/google/bazel.rst, examples/tools/meson/meson.rst, examples/tools/microsoft/msbuild.rst, examples/tools/scm/git/capture_scm/git_capture_scm.rst
Also fixes the titles in the sidebar for the rest of the examples
cf https://github.com/conan-io/examples2/pull/145
=> Use git helpers in scm example

examples/tools/autotools/autotools.rst, examples/tools/cmake/cmake.rst, examples/tools/files/files.rst, examples/tools/google/bazel.rst, examples/tools/meson/meson.rst, examples/tools/microsoft/msbuild.rst, examples/tools/scm/git/capture_scm/git_capture_scm.rst
=> Add new Git helpers to scm example

.ci/scripts/prepare_sources.py
Makes the actual build super duper fast, this was the slowest point in this step for me
=> Add --depth 1 to doc source clone

.ci/publish.jenkins, .ci/scripts/prepare_gh_pages.py, .ci/scripts/replace_html_tags.py, _themes/conan_theme/layout.html
Only if that same file is present in the newest docs version
=> Add warning for outdated 2.X versions

.ci/scripts/replace_html_tags.py
Testing locally I had different names!
=> Properly filter to v2 branches only

changelog.rst, conf.py
=> Sync develop2 with release/2.2 

reference/commands/install.rst, tutorial/versioning/version_ranges.rst
For https://github.com/conan-io/conan/pull/16110
=> Add clarification that `--update` does not shortcircuit

reference/commands/create.rst, reference/conanfile/attributes/folders.inc, reference/conanfile/methods/test.rst, tutorial/creating_packages/test_conan_packages.rst
Docs for https://github.com/conan-io/conan/pull/16013
Docs for https://github.com/conan-io/conan/pull/15999
=> test_package_folder

reference/tools/meson/mesontoolchain.rst
Docs for https://github.com/conan-io/conan/pull/16172
=> [MesonToolchain] Added tools.build:defines conf

changelog.rst, conf.py, examples/runners/docker/basic.rst, examples/runners/docker/configfile_build_args.rst
=> Sync develop2 with release/2.3

.ci/scripts/common.py, changelog.rst, conf.py
Merge without squash after release
=> Conan 1.64.1 docs

reference/config_files/settings.rst
=> Add GCC 13.3 to settings.yml

_static/css/conan.css
=> Make search highlight less hideous

reference/config_files/global_conf.rst
From https://github.com/conan-io/docs/pull/3735
=> fix conf patterns

reference/tools/cmake/cmaketoolchain.rst
Docs for https://github.com/conan-io/conan/pull/16335
=> Fix info on CMAKE_SYSTEM_VERSION for Apple systems

reference/tools/meson/mesontoolchain.rst
docs for: https://github.com/conan-io/conan/pull/16011
=> adding: sysroot property

reference/binary_model/package_id.rst, reference/tools/scm/version.rst
=> Update develop2 with release/2.3 branch

devops/devops_local_recipes_index.rst, examples/commands/pkglists.rst, examples/config_files/settings/settings_user.rst, examples/dev_flow/debug/debugging_visual.rst, examples/runners/docker/basic.rst, examples/runners/docker/configfile_build_args.rst, examples/tools/autotools/create_your_first_package.rst, examples/tools/autotools/create_your_first_package_windows.rst, examples/tools/meson/create_your_first_package.rst, knowledge/faq.rst, reference/binary_model/dependencies.rst, reference/binary_model/package_id.rst, reference/commands/cache.rst, reference/commands/list.rst, tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/intro_to_versioning.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst, tutorial/creating_packages/create_your_first_package.rst, tutorial/creating_packages/other_types_of_packages/header_only_packages.rst, tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.rst, tutorial/developing_packages/local_package_development_flow.rst, tutorial/versioning/revisions.rst, tutorial/versioning/versions.rst
=> Release 2.4 to develop2 branch

tutorial/consuming_packages/build_simple_cmake_project.rst, tutorial/consuming_packages/different_configurations.rst
Close https://github.com/conan-io/docs/issues/3776
=> Clarify presets and toolchain files

reference/config_files/settings.rst
For https://github.com/conan-io/conan/pull/16506 and https://github.com/conan-io/conan/pull/16494
=> settings.yml for 2.5.0

reference/tools/gnu/autotoolstoolchain.rst, reference/tools/meson/mesontoolchain.rst
Docs for https://github.com/conan-io/conan/pull/16502
=> [AutotoolsToolchain] `tools.android:ndk_path` conf

changelog.rst, conf.py
=> Sync develop2 with Release/2.5

reference/config_files/profiles.rst
=> Fix profile rendering uhm, rendering

devops/devops_local_recipes_index.rst, tutorial/conan_repositories/setup_local_recipes_index.rst
Docs for https://github.com/conan-io/conan/pull/16420
=> local-recipes-index python-requires

reference/tools/files/basic.rst
Synchronize with [`conan.tools.files.unzip`](https://github.com/conan-io/conan/blob/c55ab23/conan/tools/files/files.py#L285-L299)
=> Update compression formats

reference/config_files/profiles.rst
Close https://github.com/conan-io/docs/issues/3812
=> clarify [buildenv] with blank spaces

reference/conanfile/methods.rst, reference/conanfile/methods/finalize.rst
For https://github.com/conan-io/conan/pull/16646
=> Add first draft for finalize() method

tutorial/creating_packages/build_packages.rst, tutorial/creating_packages/configure_options_settings.rst
This fix two small errors on docs and 
close: https://github.com/conan-io/conan/issues/16881 
close: https://github.com/conan-io/conan/issues/16888
=> Fix small errors

reference/conanfile/methods/generate.rst
Close https://github.com/conan-io/docs/issues/3826
=> fixing generate() docs

reference/conanfile/running_and_output.rst
Add extra information about the output methods.
This was asked in https://github.com/conan-io/docs/issues/3832
=> Add extra information for the output methods

reference/commands/config.rst
Docs for https://github.com/conan-io/conan/pull/16876
=> conan config install-pkg --url

reference/commands/config.rst
Docs for https://github.com/conan-io/conan/pull/17000
=> config list pattern

reference/tools/env/virtualbuildenv.rst, reference/tools/env/virtualrunenv.rst
For https://github.com/conan-io/conan/pull/16935
=> Note for --env-generation=false

examples/tools/cmake/cmake_toolchain/inject_cmake_variables.rst, reference/tools/cmake/cmaketoolchain.rst
Docs for https://github.com/conan-io/conan/pull/17036
=> user_toolchain CMAKE_SYSTEM vars

reference/config_files/settings.rst
For https://github.com/conan-io/conan/pull/17092
=> Add settings.yml changes for 2.9

reference/commands/config.rst
For https://github.com/conan-io/conan/pull/17123
=> Add include pattern example for .conanignore

examples/tools/autotools/create_your_first_package_windows.rst
Docs for https://github.com/conan-io/conan/pull/16875
=> compiler=cl not necessary

changelog.rst, conf.py
=> Release 2.9.0 to develop2

changelog.rst, conf.py
=> Conan 2.9.1 docs to develop2

changelog.rst, reference/conanfile/attributes/consumers.inc, reference/conanfile/methods/package_info.rst, reference/extensions/custom_generators.rst
Closes: https://github.com/conan-io/docs/issues/3902
=> Fix generator_info docs

integrations/ros.rst
For got to add this change at https://github.com/conan-io/docs/pull/3917#discussion_r1860458075
=> ROS dockerfile: add nav2_msgs

reference/tools/env/envvars.rst
Related to: https://github.com/conan-io/conan/pull/17389
=> Fix powershell only windows exclusive in docs

reference/tools/cmake/cmake.rst, reference/tools/microsoft/msbuild.rst
Docs for https://github.com/conan-io/conan/pull/17301
=> max_cpu_count

incubating.rst, index.rst
Docs for https://github.com/conan-io/conan/pull/17272
=> incubating section

reference/runners/docker.rst
Docs for https://github.com/conan-io/conan/pull/17069
=> Add docker network docs

reference/commands/list.rst
Close https://github.com/conan-io/docs/issues/3936
=> fix quotes

changelog.rst, conf.py
To be merged after 2.10.3 release
=> 2.10.3 docs

changelog.rst, conf.py
=> 2.10.3 docs to develop2

reference/tools/gnu/autotoolstoolchain.rst
Docs for https://github.com/conan-io/conan/pull/17470
=> [AutotoolsToolchain] Android UX

changelog.rst, conf.py
=> Conan 2.11.0 to develop2 branch

reference/conanfile/methods/package_info.rst
Awesomely this is the only needed change
=> Moved conf model

changelog.rst, conf.py
=> Conan 2.12.0

changelog.rst, conf.py
=> Conan 2.12.1

reference/conanfile/methods/requirements.rst, tutorial/versioning/conflicts.rst
Closes https://github.com/conan-io/docs/issues/3970
=> More info con override and force traits to make their differences more explicit

reference/tools/sbom.rst
Related to: https://github.com/conan-io/conan/pull/17760
=> Fix 2.12 sbom changes

reference/binary_model/custom_compatibility.rst
Closes https://github.com/conan-io/docs/issues/3984
=> Mention package id changes when mode confs are changed

reference/commands/install.rst
Closes https://github.com/conan-io/docs/issues/3985
=> Mention negation patterns for `--deployer-package`

devops/metadata.rst
Close https://github.com/conan-io/docs/issues/3990
=> fix metadata note

reference/conanfile/attributes.rst, reference/conanfile/methods/generate.rst
For https://github.com/conan-io/conan/pull/17659
=> Transitive notice for extension_properties

reference/tools/scm/version.rst
https://github.com/conan-io/conan/pull/17658
=> Added in_range documentation

reference/commands/install.rst
Related to https://github.com/conan-io/conan/pull/17824
=> [runtime_deploy] Add note about deploying symlinks for conan install command

reference/tools/premake/premake.rst
https://github.com/conan-io/conan/pull/17398
=> Add docs for added features to the premake cli wrapper

incubating.rst
Docs for https://github.com/conan-io/conan/pull/17831
=> add CMakeConfigDeps

incubating.rst
Docs for https://github.com/conan-io/conan/pull/17688
Docs for https://github.com/conan-io/conan/pull/17675
=> update workspace docs

changelog.rst, conf.py
=> Sync develop2 with Release/2.13

ci_tutorial/products_pipeline.rst
=> Correct emphasized lines

incubating.rst
Docs for https://github.com/conan-io/conan/pull/17725
=> [incubating] Apple Frameworks

reference/tools/cmake/cmaketoolchain.rst
=> fix typo in CMakeToolchain

reference/conanfile/methods/export.rst, reference/conanfile/methods/export_sources.rst
* The text described export_sources(), not export().
* The equivalent attributes exports and exports_sources have correct documentation.
=> Fix incorrect statement at export() method

tutorial/versioning/version_ranges.rst
Docs for https://github.com/conan-io/conan/pull/18012
=> version range pattern

reference/conanfile/attributes/consumers.inc
For https://github.com/conan-io/conan/pull/17957
=> improve deprecated message

reference/commands/list.rst
For https://github.com/conan-io/conan/pull/18015/
=> Docs for graph-context

changelog.rst, conf.py
=> conan 2.15.0

examples/cross_build/android/ndk.rst
Close https://github.com/conan-io/docs/issues/4048
=> change android default libcxx to shared

reference/commands/profile.rst
Closes https://github.com/conan-io/docs/issues/4053
=> Fixes missing conan profile path help

reference/tools/scm/git.rst
The bullet points are now shown properly.
=> Fix rendering of bullet points in tools.scm.git

changelog.rst, devops/audit.rst, reference/commands/audit.rst
And adding it to the changelog.
=> Some improvements to cona audit docs

devops/audit.rst
Related to https://github.com/conan-io/conan/pull/18160
=> [audit] Add severity level information for conan audit scan

reference/tools/sbom.rst
By @ErniGH for https://github.com/conan-io/conan/pull/18108
=> Add cyclonedx 1.6 support

reference/config_files/settings.rst
https://github.com/conan-io/conan/pull/18175
=> Add gcc 15.1

reference/conanfile/attributes/requirements.inc, reference/conanfile/methods/requirements.rst
Docs for https://github.com/conan-io/conan/pull/18101
=> docs for no_skip=True new trait

changelog.rst, devops/audit.rst, reference/commands/audit.rst
=> Sync develop2 with release 2.15 branch

knowledge/faq.rst
maybe it'd also be better to narrow the example?
conanfile.* text eol=lf
=> [FAQ] fix .gitattributes code block

reference/commands/new.rst
For https://github.com/conan-io/conan/pull/18249
=> Add docs for header_lib template

reference/config_files/profiles.rst
For https://github.com/conan-io/conan/pull/18244
=> Add subprocess to Jinja profile rendering docs

reference/commands/cache.rst
For https://github.com/conan-io/conan/pull/18219
=> Add description for --list input in cache clean/check-integrity commands

reference/tools/cmake/cmaketoolchain.rst
Close https://github.com/conan-io/docs/issues/4111
=> adding missing CMakeToolchain blocks

changelog.rst
Fix incomplete 2.17.0 changelog
=> Sync develop2

reference/tools/gnu/pkgconfigdeps.rst
For https://github.com/conan-io/conan/pull/18439
=> Add `pkg_config_name` = `"none"` property docs

reference/config_files/profiles.rst
For https://github.com/conan-io/conan/pull/18383
=> Add profile context docs

reference/conanfile/methods/build_requirements.rst, reference/conanfile/methods/requirements.rst
For https://github.com/conan-io/conan/pull/18440
=> Wording for warnings

reference/commands/formatters/graph_info_json_formatter.rst, tutorial/creating_packages/handle_sources_in_packages.rst
Docs for https://github.com/conan-io/conan/pull/18661
=> adding serialzied conandata_yml

reference/config_files/profiles.rst
=> Note explaining profile determination order

knowledge/faq.rst, reference/commands.rst
To clarify situations such as https://github.com/conan-io/conan/issues/18685
=> Add stdout/stderr outputs to FAQ

reference/config_files/profiles.rst, tutorial/consuming_packages/use_tools_as_conan_packages.rst
Closes https://github.com/conan-io/docs/issues/4194
=> Add more explicit info on profile patterns

reference/extensions/custom_commands.rst
Resolves https://github.com/conan-io/docs/issues/4197
=> Fix custom command format example

reference/config_files/profiles.rst
Close https://github.com/conan-io/conan/issues/18867
=> clarify behavior of per-package compiler.runtime_type deduction

reference/conanfile/attributes/requirements.inc, tutorial/versioning/version_ranges.rst
Close https://github.com/conan-io/docs/issues/4215
=> fix version-ranges caret

reference/conanfile/methods/layout.rst
Close https://github.com/conan-io/docs/issues/4141
=> fix conf_info.define_path

examples/commands/pkglists.rst, reference/commands/download.rst, reference/conanfile/methods/requirements.rst
Closes https://github.com/conan-io/docs/issues/4231
Closes https://github.com/conan-io/docs/issues/4230
=> Improve docs

reference/tools/layout.rst
Docs for https://github.com/conan-io/conan/pull/18958
=> Docs for setting cpp.source.includedirs = ["include"] in basic_layout 

reference/conanfile/methods/requirements.rst
For https://github.com/conan-io/docs/issues/4231
=> More info on default traits of dependencies

reference/extensions/hooks.rst
Docs for https://github.com/conan-io/conan/pull/18960
=> post_package_id hook

reference/conanfile/attributes/binary_model.inc
Docs for https://github.com/conan-io/conan/pull/18869
=> clarify build-scripts -> library relationship
