conan-io/docs

installation.rst

Added git repository url and some formatting cleanups.

Tiny docs changes

---

manage_deps/conanfile_txt.rst

Hi guys! While I was going through the documentation, learning conan, I thought that I might as well do some proofreading and suggest some improvements. Let me know if you think this was a good idea. I could do the same for other chapters I go through...

Some improvements to Using conanfile.txt

---

getting_started.rst
installation.rst
manage_deps/conanfile_py.rst
manage_deps/conanfile_txt.rst

Proofreading from "Install" to "Managing your dependencies"

---

integrations/appveyor.rst
integrations/cmake.rst
integrations/git.rst
integrations/makefile.rst
integrations/qmake.rst
integrations/travisci.rst
integrations/visual_studio.rst
integrations/xcode.rst
manage_deps/workflows.rst

Please have a look to make sure I have not changed the meaning anywhere. I am still learning conan myself :)

Proofreading Integrations and Managing your dependencies > Workflows

---

examples.rst
examples/boost.rst

Sorry for the previous PR, it can be merged to master, working with release 0.5

added boost example, tested in Win

---

packaging/getting_started.rst
packaging/testing.rst
packaging/upload.rst

Once again, please make sure you're ok with what I've done here :)

Proofreading Creating packages

---

changelog.rst
examples/boost.rst
examples/go.rst
examples/gtest.rst
examples/zmq_protobuf.rst
faq.rst
reference/conanfile.rst
reference/config_files.rst

First reading done! Please pay particular attention to the FAQ section suggestions. I guess the FAQ is pretty important, so I hope I have not changed the meaning anywhere.

Proofreading from Reference > conanfile.py until the end of all docs

---

manage_deps/conanfile_py.rst
packaging/getting_started.rst
reference/commands.rst
reference/conanfile.rst

Fix #21, implemented in https://github.com/conan-io/conan/pull/66
Also:
- relative imports, implemented in: https://github.com/conan-io/conan/pull/53
- conan info

docs for 3 features: command info, conanfile_directory and relative imports

---

changelog.rst
manage_deps/conanfile_txt.rst
packaging/getting_started.rst
packaging/testing.rst
packaging/upload.rst
reference/commands.rst
reference/config_files.rst

Look and change what you see directly.

Release 0.8 ready

---

integrations/qbs.rst

See https://doc.qt.io/qbs/ for the intended name.

Fixed the qbs acronym expansion

---

conanfile_py.rst
getting_started.rst
howtos/copy_packages.rst
integrations/gcc.rst
integrations/other.rst
integrations/visual_studio.rst
manage_deps/conanfile_txt.rst

```
find -name '*.rst' -exec sed -i 's/1.7.2/1.7.3/g' {} \;
```
https://www.conan.io/source/Poco/1.7.3/lasote/stable

Bumped Poco

---

conanfile_py.rst
howtos.rst
howtos/create_installer_packages.rst
integrations.rst
integrations/virtualenv.rst
reference/conanfile.rst

The howto is extracted from the future blog post

virtualenvs, build policies and env_info

---

faq.rst

Howdy conan folks -- I was just reading your docs and came across this little typo.
Have a nice day!

fix little typo

---

reference/commands.rst

Docs for --update option (#63). Directly to master!

Update option documented

---

getting_started.rst
howtos/custom_cache.rst
manage_deps/conanfile_txt.rst
packaging/creating_in.rst
packaging/creating_out.rst
packaging/testing.rst
packaging/upload.rst
reference/commands.rst

fixing docs for search

---

integrations/virtualenv.rst
reference/commands.rst

Fixes https://github.com/conan-io/docs/issues/125

documenting env generator

---

changelog.rst

There is a small typo in the year.

Wrong year.

---

integrations/cmake.rst

Documentation for conan-io/conan#890.

Document the conan_target_link_libraries macro

---

howtos/create_installer_packages.rst
howtos/python_code_reuse.rst
reference/commands.rst
reference/conanfile.rst
reference/config_files.rst
reference/tools.rst

- Env fixes
- Some missing features

some env fixes

---

changelog.rst
conanfile_py.rst

Document CMake configure & build wrappers (#158)

---

conanfile_py.rst

Supplement to #159 for issue #158.

More CMake details

---

packaging/packaging.rst

Attribute incorrectly set as "export_sources" instead of "exports_sources". Tripped me up while copying and pasting.

Small but very confusing typo

---

mastering.rst
mastering/build_requires.rst

I think it would be good to add some "build-tool", like cmake example, also links to Android, etc.
Do you have cmake examples? Otherwise I will build them myself.

docs for build_requires

---

mastering/build_requires.rst

I hope this is useful.  I would like to help out with the readability of the docs from time to time.

Minor English tweaks.

---

server.rst

- Information about LDAP authenticator and project link.
Signed-off-by: Uilian Ries <uilianries@gmail.com>

Added LDAP authentication plugin

---

howtos.rst
howtos/collect_licenses.rst
reference/conanfile/methods.rst
reference/conanfile_txt.rst

Address: https://github.com/conan-io/docs/issues/229
And: https://github.com/conan-io/docs/issues/230

imports new arguments and examples

---

reference/tools.rst

This adds documentation for the functions added to `conans.tools` in conan-io/conan#1514.
See #254.

Document new public file utils

---

manage_deps/conanfile_txt.rst

Trying to use uniform package references and some minor English edits.

Minor editing improvements to Manage deps.

---

reference/build_helpers/cmake.rst

I changed to match line 118, which i think is the new variable name, not sure.

updated definitions to defs

---

reference/conanfile/methods.rst

- Added Chocolatey, Pkg and PkgUtil
Signed-off-by: Uilian Ries <uilianries@gmail.com>

Update information about SystemPackageTool (#281)

---

reference/conanfile/methods.rst

Hi!
I just updated the information about how to use Choco with `SystemPackageTool`
Regards.

Update info about Choco usage (#281)

---

reference/conanfile/methods.rst

https://github.com/conan-io/conan/issues/1594

adding note for source method settings/options

---

howtos/cross_building.rst

https://github.com/conan-io/conan/issues/1594

improved cross build toolchain docs

---

reference/commands/remote.rst

remote update --insert

---

reference/commands/profile.rst

Profile update/new reference

---

reference/env_vars.rst

I don't know if my changes are correct, so please make any changes necessary.  It seemed that what was documented was probably not clear or sufficient, so I figured this would get it improved one way or another.

Added clarity to CONAN_SYSREQUIRES_SUDO

---

reference/commands/user.rst

Hi!
I just added a simple example how to use `conan user -p`  -- [Ask for password when execute `conan user`](https://github.com/conan-io/conan/issues/1929)
And, I updated the user command reference, extracting from `--help` -- used develop branch at commit 4c448d82433dc92f795e1bc501b05e2f1c15c7b1
Regards.

Update command user (#345)

---

manage_deps/conanfile_txt.rst
mastering.rst
mastering/concurrency.rst
mastering/profiles.rst
reference/commands/consumer/install.rst
reference/env_vars.rst
reference/generators.rst
reference/generators/cmakemulti.rst
reference/generators/visualstudiomulti.rst
reference/tools.rst

docs for 0.28

---

reference/conanfile/attributes.rst

 Adds homepage attribute to reference 

---

howtos/header_only.rst

Adds no_copy_source to header only howto

---

reference/commands/consumer/info.rst

https://github.com/conan-io/docs/issues/394

updating conan info ref with install-folder

---

packaging/getting_started.rst

Just a review of Issue #385. No further improvements needed. Fixes #385

Review conan create getting started

---

howtos/shared/rpaths.rst
reference/generators/cmake.rst

Changed cmake variable SKIP_RPATH to KEEP_RPATHS

---

reference/conanfile/attributes.rst
reference/tools.rst

https://github.com/conan-io/conan/pull/2139

optional env automatic vars and no_op context manager

---

reference/conanfile/methods.rst

Extended explanation of package_id() method in reference

---

reference/conanfile/attributes.rst

Removes conanfile_directory from attributes in reference

---

integrations/visual_studio.rst
packaging/package_info.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Toolset compat

---

reference/tools.rst

- Added signature to all functions.
- Checked description and added examples if needed.
- Added parameters section to all functions.

Formated tools section in reference

---

reference/build_helpers/autotools.rst

- Added signature to methods and brief description.
- Added constructor section.
- Formatted attributes section.
- Default values to parameters and attributes (when possible).

Format autotools build helper

---

reference/env_vars.rst

- Added deafult values (when possible)
- Set examples in code-blocks
- Added `See also`, `Note` and `Warning` text boxes
- Changed headers highlight

Formatted reference/environment variables

---

reference/build_helpers/cmake.rst

- Added methods and constructor signatures.
- Added default value to attributes and parameters (when possible).
- Added brief explanation in methods

Formatted cmake build helper in reference

---

reference/build_helpers/meson.rst

- Description
- Constructor section
- Signatures in constructor and methods
- Added parameters with defaulted values

Format meson build helper

---

reference/tools.rst

tool.collect_libs warning about order

---

reference/commands/consumer/config.rst
reference/commands/consumer/get.rst
reference/commands/consumer/info.rst
reference/commands/consumer/install.rst
reference/commands/consumer/search.rst
reference/commands/creator/create.rst
reference/commands/creator/export-pkg.rst
reference/commands/creator/export.rst
reference/commands/creator/new.rst
reference/commands/creator/test.rst
reference/commands/creator/upload.rst
reference/commands/development/build.rst
reference/commands/development/package.rst
reference/commands/development/source.rst
reference/commands/misc/alias.rst
reference/commands/misc/copy.rst
reference/commands/misc/download.rst
reference/commands/misc/imports.rst
reference/commands/misc/profile.rst
reference/commands/misc/remote.rst
reference/commands/misc/remove.rst
reference/commands/misc/user.rst

Updated reference commands with params and ussage for conan 1.0.0-beta
- Help messages (#442)
- Ussage examples
- Formatting

Updated commands reference for conan 1.0.0-beta

---

reference/conanfile/methods.rst

Correct uses of `self.out`

---

creating_packages/package_local_dev_flow.rst
reference/commands/creator/export-pkg.rst
reference/commands/development/build.rst
reference/commands/development/package.rst
reference/conanfile/methods.rst

https://github.com/conan-io/docs/issues/481

fixed underscores

---

creating_packages/package_approaches.rst

https://github.com/conan-io/conan/issues/2328
The repo https://github.com/memsharded/hello_multi_config has also been updated.

improve multi-config packages docs and example code

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Removed config() method

---

systems_cross_building/cross_building.rst

Real and generic profiles to target Linux/android

Cross build profiles

---

auto.bat

make html every to 2 seconds.
Same as `auto.sh` but for Windows.
````
$ auto.bat
CALL make html
Running Sphinx v1.6.5
loading pickled environment... done
building [html]: targets for 31 source files that are out of date
updating environment: 0 added, 31 changed, 0 removed
...

Added auto batch script

---

conan1.0.rst

https://github.com/conan-io/cmake-conan/issues/66

explain in conan 1.0 migrate about gcc new versions

---

reference/commands/consumer/search.rst

https://github.com/conan-io/conan/pull/2348

docs for search --all

---

reference/conanfile/methods.rst

https://github.com/conan-io/conan/pull/2362

clarify build_id for conditional behavior

---

reference/tools.rst
systems_cross_building/cross_building.rst

Also, there is an additional change in the Android profiles that could be already merged to master, sorry.

Merge for 1.0.4: Feature/change default param vcvars

---

reference/commands/creator/create.rst

Added documentation for skip tests while creating the package.
fixes #507

Added conan skip test package in create command

---

changelog.rst
reference/env_vars.rst

https://github.com/conan-io/conan/issues/2249

Completed docs about CONAN_CMAKE_PROGRAM

---

reference/commands/misc/profile.rst

Updated profile help message

---

getting_started.rst
howtos.rst
howtos/manage_gcc_abi.rst
integrations/android_studio.rst

Libcxx and gcc abi explained

---

getting_started.rst
installation.rst

Includes work done in and closes #467 and closes #473

Introduction review

---

using_packages/using_profiles.rst

Fix typos on "using profiles" page

---

reference/commands/consumer/config.rst

Added example of --verify-ssl option in conan config install

---

reference/conanfile_txt.rst

Add build requires section for PR conan-io/conan#2395

Add build_requires section to conanfile.txt reference

---

changelog.rst
getting_started.rst
introduction.rst
reference/commands/misc/remote.rst
reference/config_files/registry.txt.rst
uploading_packages/bintray/uploading_bintray.rst
uploading_packages/remotes.rst

closes #536 
docs for conan-io/conan#2483

Removed conan-transit and added conan-community description

---

reference/conanfile_txt.rst

To complement https://github.com/conan-io/conan/pull/2395

clarifying purpose of [build_requires] in conanfile.txt

---

reference/conanfile/methods.rst
reference/conanfile_txt.rst

Documentation for PR conan-io/conan#2495

keep_path paramenter for copy inside imports()

---

uploading_packages/bintray/conan_center_guide.rst
uploading_packages/bintray/uploading_bintray.rst

Included description for inclusion requests image

---

reference/commands/consumer/install.rst
reference/commands/creator/create.rst

Added method execution order for conan create

---

reference/tools.rst

Improved description of tools.environment_append()

---

changelog.rst
faq/troubleshooting.rst

Package ID in the trace of package not found

---

changelog.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst

Doc for https://github.com/conan-io/conan/pull/2493

Added new env variable CONAN_SYSREQUIRES_MODE

---

integrations/visual_studio.rst

This is an attempt to write up the helpful advice given to me in conan-io/docs/issues/556
It would be better if someone could explain how to work around the current cmake limitations - or point to instructions on this.

Clarify Visual Studio integration docs

---

changelog.rst
integrations/other.rst
reference/generators.rst
reference/generators/json.rst

Document json generator

---

reference/conanfile/attributes.rst

Improve generators attribute description

---

uploading_packages/bintray/conan_center_guide.rst

Do NOT use version ranges in recipes for conan-center

Version ranges in conan-center guidelines

---

changelog.rst
reference/tools.rst

Docs for no-op tools.vcvars() out of windows

---

howtos.rst
howtos/use_tls_certificates.rst
reference.rst
reference/commands/misc/remote.rst
reference/config_files.rst
reference/config_files/client_certificates.rst
uploading_packages/running_your_server.rst

https://github.com/conan-io/conan/pull/2581/files

Client certificates

---

reference/build_helpers/cmake.rst
reference/env_vars.rst

Added internal link to cmake environment variables

---

changelog.rst
reference/commands/misc/download.rst

Changelog includes conan-io/conan#2634 and conan-io/conan#2633

Documentation of conan download --recipe and changelog

---

integrations/cmake/cmake_multi_generator.rst

Close https://github.com/conan-io/conan/issues/2623

clarify about cmake_multi not for package creation

---

changelog.rst
reference/env_vars.rst

For corresponding changes to Conan repo.

Fix disable login prompt environment variable.

---

howtos/custom_generators.rst

closes #602
Just an update of the content from here: https://github.com/memsharded/conan-premake
See PR opened: https://github.com/memsharded/conan-premake/pull/2

updated premake generator example

---

changelog.rst

Added changelog for conan-io/conan#2679
Issue conan-io/conan#2636

Changelog: Make conanfile templates PEP8 compliant and added ConanFile docstrings

---

changelog.rst
reference/commands/creator/upload.rst

Documentation and changelog for conan-io/conan#2672
Issue conan-io/conan#2472

Added conan upload --no-overwrite documentation and changelog

---

getting_started.rst

Improved getting started conanbuildinfo.cmake

---

changelog.rst
reference/commands/creator/create.rst
reference/commands/creator/export.rst

Documentation for conan-io/conan#2765
Issue conan-io/conan#2751

Added -ks for export and create

---

reference/commands/misc/remote.rst

Add documentation fo command line option 'remote rename'

Support for renaming a remote (#2618)

---

changelog.rst
reference/env_vars.rst

- Change CONAN_COLOR_DISPLAY
- default undefined
- set to 1 to force color

Allowing requiring color output with ``CONAN_COLOR_DISPLAY=1``

---

reference/config_files/conan.conf.rst

Documented no_proxy_match in conan.conf

---

reference/commands/creator/export-pkg.rst

 Added execution flow for conan export-pkg

---

changelog.rst

Changelog for PR conan-io/conan#2870 and conan-io/conan#2868

Added bugfixes to changelog

---

reference/tools.rst

Added extensions explanation for tools.which()

---

changelog.rst

Corresponding to conan-io/conan#2916.

Changelog update

---

changelog.rst

Includes changelog for:
- PR conan-io/conan#2909, Issue conan-io/conan#2897
- PR conan-io/conan#2921. Issue conan-io/conan#2912
- PR conan-io/conan#2922
- PR conan-io/conan#2908, Issue conan-io/conan#2904
- PR conan-io/conan#2887, Issue conan-io/conan#2821

Changelog 1.4 for different issues

---

changelog.rst
reference/tools.rst

Docs for PRs conan-io/conan#2941 and conan-io/conan#2948
Issue conan-io/conan#2934

Adds docs for vcvars improvements

---

howtos.rst
howtos/check_conan_version_in_conanfile.rst
reference/config_files/conan.conf.rst

Added how to check for conan client version inside recipe

---

conf.py
integrations/xcode.rst
reference/tools.rst
systems_cross_building/cross_building.rst

- Mention apple tools and new darwin toolchain.
- And little fix in the conf.py to work offline

Darwin toolchain changes

---

creating_packages/package_dev_flow.rst

Use same folder for install and build in dev flow

---

reference/generators/cmake.rst

Added CONAN_DISABLE_CHECK_COMPILER to cmake generator

---

creating_packages/package_dev_flow.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Clarify paths relative to src in self.copy() in package()

---

faq/using.rst

Add line endings answer to FAQ

---

mastering/conditional.rst

Constrain settings and options section

---

creating_packages/getting_started.rst
creating_packages/package_repo.rst
devtools/running_packages.rst
integrations.rst
integrations/other.rst

A handful of typos fixed and words rearranged. Introduction added to
Integrations and also emphasis changed for some variables and filenames.
Please let me know if these are good changes, I can make more while
going through the documentation.

Minor typos and wording fixes.

---

changelog.rst

User Agent update in changelog

---

reference/config_files/conan.conf.rst

Closes #446 
Documents PR conan-io/conan#3138
Updates the whole conan.conf with default configuration

Document cache_no_locks in reference

---

changelog.rst
reference/tools.rst

Docs for PR conan-io/conan#3187
Issue conan-io/conan#3127

Adds new filename parameter to tools.get()

---

creating_packages/define_abi_compatibility.rst

Review "Define ABI compatibility" section and documented requires modes

---

changelog.rst
reference/tools.rst

Docs for PR conan-io/conan#3221
Issue conan-io/conan#3140

Propagated keep_permissions and pattern parameters from tools.get() to tools.unzip()

---

changelog.rst
howtos/link_apple_framework.rst
reference/generators/xcode.rst

https://github.com/conan-io/conan/pull/3218

Framework search paths

---

conf.py
faq.rst
faq/conan1.0.rst
index.rst

Moved Conan 1.0 section to FAQ

---

changelog.rst
reference/commands/development/build.rst
reference/conanfile/attributes.rst

Docs for PR conan-io/conan#3212
Issue conan-io/conan#3060

Documents conan --test and should_test

---

reference/commands/creator/upload.rst

Updated conan upload examples in reference

---

reference/commands/consumer/config.rst
reference/conanfile/other.rst
reference/tools.rst

Missing changelog
closes #741 closes #740

Added tools.run_environment(), conan config install --type

---

reference/build_helpers/run_environment.rst
reference/build_helpers/visual_studio.rst

Added missing parameters to MSBuild() and fixed RunEnvironment link

---

reference/build_helpers/cmake.rst

This update is related to the issue #716 .

Added example subsection to _cmake_reference

---

changelog.rst
reference/tools.rst

print_errors parameter for tools.PkgConfig()

---

changelog.rst

Docs for PR conan-io/conan#3380
Issue conan-io/conan#3240

Changelog MSBuild quoted arguments

---

installation.rst
introduction.rst

Py2 Deprecation

---

developing_packages.rst
developing_packages/package_dev_flow.rst
developing_packages/workspaces.rst
videos.rst

- Developing packages (including subpages)
- Videos and links

Suggestions to the following pages in the documentation:

---

howtos/capture_version.rst
reference/tools.rst

howto for version from git

---

howtos/link_apple_framework.rst
installation.rst
reference/tools.rst

Added includedirs and cmake note in howto apple frameworks

---

conf.py

Avoid localhost links to be checked in CI

---

creating_packages/package_approaches.rst
creating_packages/understand_packaging.rst
howtos/vs2017_cmake.rst
reference/tools.rst
uploading_packages/bintray/conan_center_guide.rst
uploading_packages/running_your_server.rst

This PR does NOT change any content in the docs, just fixes warnings in headers & links, typos and little formatting.

Fixes warnings in docs and link checks with redirect

---

reference/conanfile.rst
reference/conanfile_txt.rst

Mostly formatting and completed some sentences. Almost no change in content.

Improve conanfile.txt reference

---

conf.py
getting_started.rst
reference/profiles.rst

Improved getting started:
* Moved warning about libcxx
* Fixed formatting
* Include reference to conan config install
* Improve refences links
Improved profile section:
* Tip for conan config install
* Grouped references
Added conan-jfrog logo to pdf

Getting started review and minor improvements

---

integrations/cmake/find_packages.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst
systems_cross_building/cross_building.rst

Fix escapement issues on Windows paths

---

integrations/pkg_config_pc_files.rst

Review of pc files integration

---

reference/build_helpers/meson.rst

Added depdenencies example and build folder to meson helper

---

reference/tools.rst

Improved tools.collect_libs() description

---

reference/build_helpers/cmake.rst

Docs for https://github.com/conan-io/conan/pull/3586

Document 'Cmake.get_version()'

---

integrations/qmake.rst

Review qmake integration section

---

howtos/link_apple_framework.rst

How to package an apple framework

---

howtos/custom_generators.rst
reference/conanfile/attributes.rst

To master. Missing user_info and deps_user_info docs and completed custom generators ref.

custom generators + user_info documented

---

changelog.rst
reference/tools.rst

for https://github.com/conan-io/conan/pull/3574

- document latest_visual_studio_version_installed

---

changelog.rst
reference/config_files/default_profile.rst
reference/env_vars.rst

Docs for https://github.com/conan-io/conan/pull/3615

Document CONAN_DEFAULT_PROFILE_PATH

---

changelog.rst
reference/tools.rst

Closes https://github.com/conan-io/conan/pull/3603

Docs gnu_triplet fix

---

changelog.rst
reference/tools.rst

Removed output parameter in latest_visual_studio_version_installed()

---

creating_packages/getting_started.rst
creating_packages/package_repo.rst
howtos/manage_shared_libraries/env_vars.rst
integrations/clion.rst
integrations/other.rst
mastering/conanfile_py.rst
mastering/conditional.rst
mastering/policies.rst
reference/build_helpers/autotools.rst
reference/conanfile/attributes.rst
reference/generators/compiler_args.rst

Docs for https://github.com/conan-io/conan/pull/3477

conanfile options and default_options documentation

---

changelog.rst
reference/build_helpers/autotools.rst
reference/build_helpers/cmake.rst

Includes warning with explanation and link from changelog.
Docs for PR conan-io/conan#3388
Issue conan-io/conan#3369

 Documentation for --libdir in AutoTools

---

conf.py

closes #873
Information is in this link: https://docs.readthedocs.io/en/latest/vcs.html#github

Recovered 'Edit on GitHub' button

---

mastering/conditional.rst
reference/conanfile/methods.rst

Do you think we should document exit error codes?

Minor changes regarding ConanInvalidConfiguration

---

reference/build_helpers/autotools.rst
reference/build_helpers/cmake.rst

Use 'share' for DATAROOTDIR

---

reference/build_helpers/autotools.rst

Fix docs about --sbindir and --libexecdir

---

reference/commands/misc/remote.rst

Document binary registry commands

---

reference/commands/output/install.rst

Docs for https://github.com/conan-io/conan/pull/3717

Add docs about new fields in json output

---

integrations/pkg_config_pc_files.rst
reference/conanfile/attributes.rst
reference/env_vars.rst
reference/tools.rst
uploading_packages/bintray/conan_center_guide.rst

Rules for using one the other: https://www.wikihow.com/Sample/An-A-Usage
"A user" respects the same rules as "a union".

Fix a/an grammar uses

---

developing_packages/package_dev_flow.rst
integrations/clion.rst
reference/commands/creator/export-pkg.rst

Docs for https://github.com/conan-io/conan/pull/3768

export-pkg using profile or settings by default

---

creating_packages/getting_started.rst
getting_started.rst
howtos/cmake_launch.rst
mastering/custom_cache.rst
reference/config_files/settings.yml.rst

Hello,
Here are some fixes for things I ran into while starting to learn conan.  I still got great value from the docs as-is, but this might help a little for the next user.  Thanks for all the hard work!
-Steve

Proposed doc changes

---

reference/generators/visualstudiomulti.rst
using_packages/conanfile_txt.rst
using_packages/using_profiles.rst
using_packages/workflows.rst

Fix #908 
Also some other minor improvements, like introducing the ``inspect`` command or more ``seealsos``

update and fix using packages

---

reference/commands/misc/inspect.rst
reference/conanfile/attributes.rst

Describe `tags` as new attribute and give some example.
closes #874

#874 Add tags attribute

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

Docs for https://github.com/conan-io/conan/pull/3846

Docs for CONAN_USE_ALWAYS_SHORT_PATHS

---

reference/commands/output/upload.rst

Updated upload json output

---

reference/build_helpers/visual_studio.rst

From https://github.com/conan-io/conan/pull/3860

VisualStudioBuildEnvironment constructor

---

getting_started.rst
howtos/manage_gcc_abi.rst
uploading_packages/remotes.rst

- Use real step-by-step guide
- Add search as a common flow
- Removed some warnings and extra information not needed for getting started (terminal with colors, conan user home....)
- Use a real example with new configuration output
- Use new inspect command
- Updated example repository https://github.com/memsharded/example-poco-timer/pull/6

Updated getting started with step by step instructions

---

changelog.rst
extending/plugins.rst
reference/build_helpers/autotools.rst
reference/conanfile/attributes.rst
spelling_wordlist.txt

Fixes #780.
Fixes some spelling issues too.

 Update short_paths documentation

---

installation.rst

Review python 2 deprecation notice text

---

faq/using.rst
reference/conanfile/attributes.rst

closes #928 
cc/ @rmam-spinworks

Added user and channel recommendations in FAQ

---

reference/conanfile/attributes.rst

This PR is related to https://github.com/conan-io/conan/pull/3702#discussion_r223982936 @memsharded asked to use tuple instead of list
Related issue: https://github.com/bincrafters/conan-protobuf/pull/18
Thanks to @Croydon

Update topics to use tuple

---

reference/conanfile/attributes.rst

- Use a real example
- Indicate it should be used as a tuple

Update topics attribute

---

reference/conanfile/methods.rst

From https://github.com/conan-io/conan/issues/3921

clarify system requirements install

---

reference/conanfile/methods.rst

Added note about string conversion for env_info and user_info values

---

getting_started.rst
reference/commands/misc/inspect.rst

Related Issue: https://github.com/conan-io/conan/pull/3914

#3883 Update inspect command

---

changelog.rst
reference/build_helpers/visual_studio.rst
reference/commands/misc/help.rst
reference/generators/premake.rst
spelling_wordlist.txt
videos.rst

Please use `make spelling` once in a while!

Fix a bunch of typos

---

reference/tools.rst

https://github.com/conan-io/conan/pull/4041

Get tool new parameters

---

mastering/version_ranges.rst

Add `include_prerelease` and `loose` option to version range expression

---

mastering/sharing_settings_and_config.rst
reference/commands/consumer/config.rst
reference/commands/misc/remote.rst
uploading_packages/remotes.rst
using_packages/using_profiles.rst

Small docs with changes for conan-io/conan#4083
Issue conan-io/conan#3656

 Update conan config install with new changes

---

reference/build_helpers/cmake.rst

Added missing references en CMake build helper and clarified CMAKE_BUILD_TYPE

---

reference/tools.rst

closes #977
feature: https://github.com/conan-io/conan/pull/4103

Document tools.apple_dot_clean ()

---

reference/commands/consumer/config.rst

Docs for issue conan-io/conan#4154
PR conan-io/conan#4158

verify_ssl is also stored in conan config install

---

reference/commands/creator/create.rst
reference/commands/creator/export.rst

Docs for: https://github.com/conan-io/conan/pull/4062

partial references for create and export

---

reference/conanfile/methods.rst
reference/generators/cmake.rst

docs for srcdirs

---

faq/troubleshooting.rst
make.bat
spelling_wordlist.txt

Fixes also some spelling mistakes

Enable spelling in make.bat for windows

---

reference/commands/consumer/config.rst

Adds important note about not sharing registry in conan config install

---

reference/conanfile/attributes.rst
reference/env_vars.rst

Remove CONAN_USER and its usage in test_package

---

reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/4207 (original issue: https://github.com/conan-io/conan/issues/4001)

Add notes about credentials being removed from URL in SCM/url attribute

---

installation.rst

Python 3.4 failure

---

reference/config_files/registry.txt.rst

Added information about registry.json config file

---

reference/config_files/settings.yml.rst

Docs for PR conan-io/conan#4195

Included settings.yml content with new archs

---

reference/tools.rst

Adding documentation in tools.rst to the feature suggested in https://github.com/conan-io/conan/issues/4168 and being proposed to be included in the corresponding PR.

Added ongoing modification on tools.env.environment_append

---

reference/conanfile/attributes.rst

Removed old version range scheme with comma.

Remove old version range scheme

---

creating_packages/external_repo.rst
creating_packages/package_repo.rst
reference/conanfile/attributes.rst

 Added experimental warning in SCM attribute

---

reference/build_helpers/cmake.rst

https://github.com/conan-io/conan/pull/4299

Feature: define environment variables for CTest 

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

https://github.com/conan-io/conan/pull/4309
https://github.com/conan-io/conan/issues/4314

- document CONAN_CACHE_NO_LOCKS

---

reference/build_helpers/cmake.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst

https://github.com/conan-io/conan/pull/4298
https://github.com/conan-io/conan/issues/3512

- document CONAN_CMAKE_PROGRAM

---

reference/tools.rst

https://github.com/conan-io/conan/issues/4323
https://github.com/conan-io/conan/pull/4324

- add clarification for unset behavior

---

reference/tools.rst

Mark SVN and Git helpers as experimental

---

mastering/policies.rst

Related issue https://github.com/conan-io/conan/pull/4305

Add full reference for build policies

---

reference/tools.rst

Docs for PR conan-io/conan#4306
Issue conan-io/conan#3987

Document method get_tag() for both Git and SVN

---

reference/generators/premake.rst

https://github.com/conan-io/conan/pull/4296
https://github.com/conan-io/conan/issues/4286

- update premake generator

---

extending/hooks.rst

closes #1000 
Removed also the ``[EXPERIMENTAL]`` from title to avoid braking auto-generated links

Fixed typo about extension of hooks

---

integrations/make.rst
reference/generators/make.rst

docs for PR conan-io/conan#4349
Issue conan-io/conan#4336

Update make generator reference and integration with CXXFLAGS and *DIRS

---

reference/build_helpers/cmake.rst

Document deprecated paramenters of CMake build helper

---

reference/commands/consumer/install.rst
reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/4197

install-ref docs

---

reference/conanfile/attributes.rst

Split folders into real attributes

---

mastering/custom_cache.rst
reference/commands/misc/remove.rst

- Update `conan remove` help
- Add description about cached system_reqs
Related issue: https://github.com/conan-io/conan/pull/4354

Add system reqs description

---

reference/conanfile/attributes.rst

Add tip about build helpers managing shared and fPIC options

---

reference/build_helpers/cmake.rst

fixes this https://travis-ci.org/conan-io/docs/builds/485876648

FIX MASTER: Fix cmake build helper formatting

---

extending/hooks.rst

Small fix related to config command on Hooks section.

fix conan config command

---

changelog.rst

Fix Conan version on changelog

---

reference/commands.rst
reference/commands/development/link.rst

link command

---

integrations/azure_devops.rst
systems_cross_building/cross_building.rst

Cherry-picked commit from @uilianries

Fix removed links

---

reference/tools.rst

closes #1063 
I could add a link, but I don't want users following a link outside our docs... I think it is so specific that if you are reading the docs of this function you already know what you are looking for.

Rephrase docs about `apple_dot_clean` tool

---

reference/conanfile/methods.rst

Fix wrong logic for Invalid configuration

---

reference/build_helpers/autotools.rst

I think we can use Conan tools here to avoid misspelling.

Use Conan tools to detect the platform

---

reference/commands/consumer/get.rst

Docs for https://github.com/conan-io/conan/pull/4494

Adapt docs to new preferred behaviour in 'conan get' command

---

creating_packages/define_abi_compatibility.rst

Fix typo minor_mode

---

reference/build_helpers/cmake.rst

Document parallel attribute of CMake build helper

---

reference/config_files/settings.yml.rst

https://github.com/conan-io/conan/pull/4260

armv5 archs

---

reference/conanfile/other.rst
reference/tools.rst

Docs for conan-io/conan#4673
Issue conan-io/conan#4304

Document with_login paramenter for run_in_windows_bash()

---

developing_packages/editable_packages.rst
reference/config_files/editable_layout.rst

Docs for https://github.com/conan-io/conan/pull/4596
There can be conflicts with https://github.com/conan-io/docs/pull/1086 (docs for workspaces)

Docs for Jinja2 in layout files (editable packages)

---

mastering.rst
mastering/revisions.rst
reference/commands/consumer/search.rst

https://github.com/conan-io/conan/pull/4462

Revisions Docs

---

changelog.rst

Add conan editable to 1.13 changelog

---

videos.rst

Signed-off-by: Uilian Ries <uilianries@gmail.com>

Add meeting embedded 2018 presentation

---

howtos/vs2017_cmake.rst
integrations/visual_studio.rst
reference/env_vars.rst

Will push the changes later to develop branch

Fix redirect and broken links

---

reference/tools.rst

Related issue: https://github.com/conan-io/conan/issues/4542
Related PR: https://github.com/conan-io/conan/pull/4761

Collect libs returns a sorted list

---

reference/commands/consumer/config.rst

Docs for https://github.com/conan-io/conan/pull/4709

multi-config-install docs

---

howtos/cmake_install.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Docs for https://github.com/conan-io/conan/pull/4748

avoid double package() calls

---

developing_packages/workspaces.rst
reference/config_files/editable_layout.rst

Docs for https://github.com/conan-io/conan/pull/4812

editable out of source layouts

---

using_packages/conanfile_txt.rst

closes #1132 (remember to close the issue when merged)

Clarify owner user name in the reference

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

Docs for https://github.com/conan-io/conan/pull/4835

Document general.cacert_path (CONAN_CACERT_PATH)

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst
using_packages/conanfile_txt.rst

Docs for https://github.com/conan-io/conan/pull/4771

Document general.error_on_override (CONAN_ERROR_ON_OVERRIDE)

---

creating_packages/package_approaches.rst
reference/generators/json.rst

Docs for https://github.com/conan-io/conan/pull/4657

Improve documentation about JSON generator

---

reference/build_helpers/cmake.rst
reference/generators/cmake_paths.rst

https://github.com/conan-io/conan/pull/4719

cmake paths ROOT paths

---

reference/config_files/settings.yml.rst

Docs for conan-io/conan#4810
Issue conan-io/conan#4688

Added documentation for s390 and s390x architectures

---

reference/commands/misc/profile.rst

Add a profile new --force example to the reference

---

mastering/revisions.rst

Set Artifactory version to 6.9 supporting revisions

Review revisions section and set artifactory version support

---

reference/config_files/conan.conf.rst

Docs for https://github.com/conan-io/conan/pull/4820

docs for allowing relative paths in conan.conf storage.path

---

reference/tools.rst

Docs for https://github.com/conan-io/conan/pull/4883

docs for gz

---

_templates/layout.html

Updated google tag manager ID 
Removed gtag script

Update google tag manager ID, remove gtag script

---

reference/commands/development/workspace.rst

Docs for https://github.com/conan-io/conan/pull/4941

Update workspace reference

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

- Add description for CONAN_DEFAULT_PACKAGE_ID_MODE
- Add default_pacakge_id_mode in conan.conf
related issue: conan-io/conan#4974

Update default package id mode

---

reference/config_files/settings.yml.rst

There can be used [None, ANY] within settings.yml file to point out that a setting can be set to any value or that it can be unset.

support [None, ANY]

---

reference/commands/development/workspace.rst

Docs for https://github.com/conan-io/conan/pull/4940

Commands reference: add workspace install --install-folder argument

---

reference/tools.rst

Coming from #1212 it seems some links have been permanently redirected

Fix redirect of links

---

howtos/cmake_install.rst

Added some arguments to use cmake.install() in package()

---

getting_started.rst

Added new link to conan-io/examples for getting started

---

faq/using.rst

Add new a section in FAQ to explain how to update the priority order for packages when searching or installing.
closes #1198

How to change remote priority

---

faq/troubleshooting.rst

Explain how to fix multiple workers and Conan server migration.
related issue: https://github.com/conan-io/conan/issues/4723

Conan server thoubleshooting

---

reference/build_helpers/cmake.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst

for https://github.com/conan-io/conan/issues/4707 https://github.com/conan-io/conan/issues/4755 https://github.com/conan-io/conan/pull/4708

- document CMAKE_GENERATOR_PLATFORM

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

https://github.com/conan-io/conan/pull/4991

Docs for skip broken symlinks

---

mastering/conditional.rst
reference/commands/return_codes.rst
reference/conanfile/methods.rst

closes #1237 
Pointed this to master as it is not specific to the release

Cross-reference Invalid Configuration with return code and mastering conditional

---

reference/tools.rst

Related PR: https://github.com/conan-io/conan/pull/5102

Add detected_os description

---

reference/config_files/conan.conf.rst

Corresponding to this conan pull request:
https://github.com/conan-io/conan/pull/4923

Adding docs for host-specific proxies

---

reference/build_helpers/cmake.rst

Docs for https://github.com/conan-io/conan/pull/5220

Change default for CMake.msbuild_verbosity (build_helper)

---

reference/hooks.rst

Docs for https://github.com/conan-io/conan/pull/5223

Add docs about pre/post_package_info

---

reference/commands/misc/remove.rst

Add an example of removing system requirements via a wildcard

---

reference/commands/creator/upload.rst
reference/config_files/conan.conf.rst
reference/tools.rst

Add notes about new config global variables

---

reference/commands/creator/upload.rst

Docs for https://github.com/conan-io/conan/pull/5224

Deprecated -p in conan upload

---

reference/commands/creator/test.rst
reference/commands/development/editable.rst
reference/commands/development/workspace.rst
reference/commands/misc/help.rst
reference/commands/misc/inspect.rst

Update help messages according to https://github.com/conan-io/conan/pull/4896

Update help messages of several commands

---

integrations/cmake/cmake_generator.rst

CMake typo review

---

reference/commands/creator/new.rst

https://github.com/conan-io/conan/pull/5267

conan new jinja template

---

installation.rst

Add know pip installation issue

---

reference/conanfile/attributes.rst

closes https://github.com/conan-io/docs/issues/1318
Also depends on https://github.com/conan-io/conan/pull/5371 (requires can be a list)

Add example with just one reference with further info using tuples

---

reference/commands/misc/copy.rst
reference/commands/misc/download.rst

Docs for PR https://github.com/conan-io/conan/pull/5293

--package argument deprecation

---

developing_packages/editable_packages.rst
integrations/ide/youcompleteme.rst

Mostly typos, commas and try to avoid sentences like `, sounds good?` that is mostly bullshit.

Some fixes in editable packages

---

creating_packages/package_approaches.rst

closes conan-io/conan#5341
closes #1325 
to be merged after https://github.com/conan-io/examples/pull/18

Update multiconfig package approach N configs -> 1 package

---

reference/config_files/conan.conf.rst

Related PR: https://github.com/conan-io/conan/pull/5438

Add deprecation warning for no_proxy

---

creating_packages/define_abi_compatibility.rst

Docs for https://github.com/conan-io/conan/pull/5363

new package id modes

---

reference/conanfile/methods.rst

Add new section explaining about setting parameter
Related issue: conan-io/conan#5026
Related PR: https://github.com/conan-io/conan/pull/5215

Update SystemPackageTool to support settings

---

reference/commands/misc/user.rst
reference/env_vars.rst

Close https://github.com/conan-io/conan/issues/5434

improving usage of env-vars in conan user

---

reference/conanfile/attributes.rst
reference/tools.rst

for https://github.com/conan-io/conan/pull/5514

Feature: shallow git clone

---

reference/commands/misc/user.rst

Docs for https://github.com/conan-io/conan/pull/5532
It will be completed with the reference update to be done at #1376

skip auth check

---

reference/generators/qbs.rst

Related to conan-io/conan#4730

Correct qbs generator example

---

reference/commands/consumer/search.rst

related PR: https://github.com/conan-io/conan/pull/5521

Search custom settings

---

reference/commands/consumer/search.rst

https://github.com/conan-io/conan/pull/5537

Lists Conan packages with revision

---

reference/commands/consumer/config.rst

related PR: https://github.com/conan-io/conan/pull/5613
related Issue: https://github.com/conan-io/conan/issues/5572

Conan config home

---

systems_cross_building/cross_building.rst

Instead build_require the correct term would be build_requires

There is a typo in a settings parameter

---

reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/5677

Document SCM shallow attribute

---

videos.rst

- add ABI compatibility is not a MAJOR problem

---

versioning/version_ranges.rst

Better docs for 'include_prerelease'

---

videos.rst

https://www.youtube.com/watch?v=h_5C_9hZIN0

Add video from IncludeOS

---

installation.rst

https://github.com/conan-io/conan/pull/5820

Drop python 3.4

---

reference/config_files/settings.yml.rst

Docs for https://github.com/conan-io/conan/pull/5650

Add GCC 9.2

---

reference/tools.rst

Related PR: https://github.com/conan-io/conan/pull/5466

Update cpu_count() with Docker

---

reference/generators.rst
reference/generators/virtualenv_python.rst

Documentation for `virtualenv_python`.
Related to [conan-io/conan#5157](https://github.com/conan-io/conan/issues/5157)

Create virtualenv_python docs

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

closes https://github.com/conan-io/docs/issues/1362
Should we close this one too: https://github.com/conan-io/conan/issues/5469 ?

#1362 Document CONAN_PYLINT_WERR env var

---

installation.rst

Add tip about bash autocompletion project in the installtion section

---

reference/conanfile/attributes.rst
reference/config_files.rst
reference/config_files/conandata.yml.rst

Documentation for conandata attribute and conandata.yml

---

reference/generators/b2.rst
reference/generators/boost_build.rst
reference/generators/cmake_find_package.rst
reference/generators/cmake_find_package_multi.rst
reference/generators/cmake_paths.rst
reference/generators/compiler_args.rst
reference/generators/custom.rst
reference/generators/gcc.rst
reference/generators/json.rst
reference/generators/premake.rst
reference/generators/qbs.rst
reference/generators/qmake.rst
reference/generators/scons.rst
reference/generators/text.rst
reference/generators/virtualenv.rst
reference/generators/virtualenv_python.rst
reference/generators/virtualrunenv.rst
reference/generators/visualstudio.rst
reference/generators/visualstudiolegacy.rst
reference/generators/visualstudiomulti.rst
reference/generators/xcode.rst
reference/generators/ycm.rst

closes #1428 and improves consistent formatting on all of the generators without modifying the contents

Review formatting of generators

---

developing_packages/workspaces.rst

Id should conanws_vs.yml and not conan_vs.yml
see https://github.com/conan-io/examples/blob/master/features/workspace/cmake/conanws_vs.yml

typo in  workspaces.rst

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

Notes changes made to resolve https://github.com/conan-io/conan/issues/5755

Notes changes disallowing short_paths_home to be a subdirectory of conan cache

---

integrations/cross_platform/qnx_neutrino.rst
reference/tools.rst

Fix https://github.com/conan-io/docs/pull/1445#discussion_r337037004
`operation system` --> `operating system`

Fix operating system

---

reference/commands/misc/profile.rst

Docs for https://github.com/conan-io/conan/pull/5954

Add --json option to profile doc

---

reference/tools.rst

docs for https://github.com/conan-io/conan/pull/5902 (https://github.com/conan-io/conan/issues/5840)

Feature: allow to specify encoding for load, save, replace_in_files 

---

reference/conanfile/attributes.rst
reference/env_vars.rst

Closes https://github.com/conan-io/docs/issues/1441

Add extra notes about CONAN_USE_ALWAYS_SHORT_PATHS

---

reference/conanfile/attributes.rst

Fix https://github.com/conan-io/docs/issues/1450

Rewording exports and exports_sources attributes

---

creating_packages/package_repo.rst

https://github.com/conan-io/conan/pull/5543

SCM feature

---

reference/commands/consumer/info.rst
reference/commands/creator/create.rst
reference/commands/creator/export-pkg.rst
reference/commands/creator/export.rst
reference/commands/misc/inspect.rst
reference/commands/misc/profile.rst
reference/commands/misc/remote.rst
reference/commands/misc/remove.rst

Commands help updated

---

faq/using.rst

Maybe could consider https://github.com/conan-io/conan/issues/2997 as closed when merged.

recipe hash faq

---

reference/conanfile/attributes.rst

Looks like it was erroneously copy/pasted from includedirs

Suggested improved description of bindir

---

integrations/custom.rst
integrations/linting/recipe.rst
reference/commands/creator/export.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst

Docs for https://github.com/conan-io/conan/pull/6152/files

remove pylint

---

creating_packages/define_abi_compatibility.rst

Docs for https://github.com/conan-io/conan/pull/6134

added note for compatible_packages w build=missing

---

reference/tools.rst

Related PR: https://github.com/conan-io/conan/pull/5996

Update tools patch to accept fuzz option

---

reference/generators/cmake_find_package_multi.rst

docs for https://github.com/conan-io/conan/pull/6063

Feature: generate ConfigVersion.cmake file 

---

reference/generators/cmake.rst

Document the intent of conan_output_dirs_setup()

---

creating_packages/define_abi_compatibility.rst
reference/conanfile/methods.rst

remove old CompatiblePackage from docs

---

reference/conanfile/other.rst

Minor change to update example to new python requires syntax

Update docs reference to new python requires

---

creating_packages/package_approaches.rst

Docs for https://github.com/conan-io/conan/pull/6230

More generators populate the `cpp_info.<config>` information

---

getting_started.rst
installation.rst

Use new package references (without namespace) on getting started to follow the structure than in PR https://github.com/conan-io/examples/pull/38
related comment: https://github.com/conan-io/examples/pull/38#issuecomment-564584878

Update Getting started with new package versions (Poco)

---

reference/conanfile/attributes.rst

fixes https://github.com/conan-io/conan/issues/6278

Fix conandata name attribute

---

installation.rst

related https://github.com/conan-io/conan/issues/6347
/cc @memsharded

- add warning about Python 3.8 compatibility

---

installation.rst

Added the link related to the issue for Python 3.8, so any user can follow our current progress.
/cc @memsharded @SSE4

Link Python 3.8 issue to install section

---

changelog.rst
conf.py

* add changelog
* change version
* remove duplicated
* minor changes
* minor changes

Merge 'master' into 'develop' (release 1.21.1)

---

integrations/build_system/cmake/cmake_generator.rst

#1529 Fix Poco target name

---

changelog.rst

some URLs in changelog are badly formatted.

Fix bad urls in changelog

---

integrations/ci/jenkins.rst

From https://github.com/conan-io/conan/issues/6400

adding a note about jenkins-git interaction

---

reference/conanfile/methods.rst

Docs for https://github.com/conan-io/conan/pull/6208

imports symbolic

---

reference/build_helpers/cmake.rst
reference/build_helpers/meson.rst

Docs for https://github.com/conan-io/conan/pull/6000

vcvars precedence docs

---

integrations/build_system/cmake/cmake_generator.rst
reference/generators/cmake.rst
reference/generators/cmakemulti.rst

related to: https://github.com/conan-io/conan/pull/6488

revert GLOBAL targets docs

---

reference/conanfile/methods.rst

Add options and package requirements as part of description

Enhancement for header only method

---

reference/tools.rst

#1562 Update tools.download

---

howtos/manage_shared_libraries/rpaths.rst
integrations/cross_platform/qnx_neutrino.rst
integrations/deployment/flatpak.rst
reference/env_vars.rst
systems_cross_building/cross_building.rst

Fix broken/moved links: https://travis-ci.org/conan-io/docs/builds/654527733?utm_source=github_status&utm_medium=notification

Fix missing links

---

versioning/lockfiles.rst

Docs for https://github.com/conan-io/conan/pull/6457

relax_lockfile

---

reference/build_helpers/meson.rst

- Added missing docs for conan-io/conan#3936.
- Added docs for conan-io/conan#6574.

[meson] Docs for conan-io/conan#3936 and conan-io/conan#6574

---

reference/commands/consumer/install.rst
reference/commands/creator/create.rst
reference/commands/creator/test.rst
reference/commands/development/workspace.rst
reference/commands/misc/graph.rst
reference/conanfile/attributes.rst

Documentation for changes from [PR #6681](https://github.com/conan-io/conan/pull/6681) and minor changes to `build_policy` explanations.

Update build_policy and --build option help text

---

conf.py

Cherry-pick https://github.com/conan-io/docs/pull/1597 to master

Less workers to check URLs

---

conf.py

Closes https://github.com/conan-io/docs/issues/1607

Do not check PR links

---

reference/config_files/conandata.yml.rst

closes https://github.com/conan-io/conan/issues/6697

Recomend 'str' values for conandata.yml version numbers

---

creating_packages/getting_started.rst
creating_packages/package_repo.rst
developing_packages/package_dev_flow.rst
devtools/running_packages.rst
howtos/custom_generators.rst

Update of the output after conan-io/hello#1

Update output of the hello library

---

creating_packages/define_abi_compatibility.rst
devtools/running_packages.rst
integrations/cross_platform/android.rst
integrations/cross_platform/emscripten.rst
integrations/deployment/appimage.rst
integrations/deployment/flatpak.rst
integrations/deployment/snap.rst
integrations/deployment/system_package_manager.rst
reference/build_helpers/visual_studio.rst
systems_cross_building/windows_subsystems.rst
videos.rst

Related to CI failing at #1619 and #1617

Fix broken links and remove trailing backlash

---

changelog.rst

Fix duplicated changelog between v1.22.2/1.22.3

---

reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/6723

document name and version in deps_cpp_info

---

reference/tools.rst

Update tools.download and tools.get description, using URL as optional list.
Related PR: https://github.com/conan-io/conan/pull/6679

Add mirror for download files

---

reference/commands/creator/export-pkg.rst

Related to PR https://github.com/conan-io/conan/pull/6720

Update export-pkg error description

---

deploy_gh_pages.py

Related to failing jobs at #1507 and #1605

Remove linkcheck from master jobs

---

reference/conanfile/attributes.rst

Related to PR: https://github.com/conan-io/conan/pull/6739

Add optional return for get_safe

---

reference/tools.rst

docs for https://github.com/conan-io/conan/pull/6744

Feature: expose cppstd_flag tool #6744

---

reference/conanfile/methods.rst
reference/env_vars.rst

Docs for https://github.com/conan-io/conan/pull/6677

Add docs for CONAN_SYSREQUIRES_MODE default_mode

---

reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/6741

Short paths using Cygwin

---

reference/generators/markdown.rst

Close https://github.com/conan-io/docs/pull/1645

Remove unicode char

---

howtos/makefiles.rst

Closes https://github.com/conan-io/docs/issues/1658
The source code is already available in the examples repository https://github.com/conan-io/examples/pull/57

Update examples about makefiles

---

reference/conan_v2_mode.rst

Docs for https://github.com/conan-io/conan/pull/6782

[conan_v2_mode] 'self.version' is always a string

---

reference/commands/creator/new.rst

Docs for https://github.com/conan-io/conan/pull/6821

'conan new', doc the 'package_name' variable

---

creating_packages/define_abi_compatibility.rst

Close https://github.com/conan-io/conan/issues/6855

clarify default_package_id_mode

---

reference/config_files/settings.yml.rst

https://github.com/conan-io/conan/pull/6911

Add GCC-10 to match conan

---

reference/generators/deploy.rst

Related to https://github.com/conan-io/conan/pull/6922

symliks are not copied for deploy gen

---

reference/config_files/settings.yml.rst

https://github.com/conan-io/conan/pull/6993

Add missing gcc versions: 6.5, 7.5, 8.4, 10.1.

---

conf.py
requirements.txt

use sphinx-sitemap to generate sitemap.xml

---

reference/commands/consumer/info.rst
reference/commands/consumer/install.rst
reference/commands/consumer/search.rst
reference/commands/creator/create.rst
reference/commands/creator/export-pkg.rst
reference/commands/creator/export.rst
reference/commands/creator/new.rst
reference/commands/creator/test.rst
reference/commands/development/build.rst
reference/commands/development/editable.rst
reference/commands/development/package.rst
reference/commands/misc/imports.rst
reference/commands/misc/inspect.rst
reference/commands/misc/profile.rst
reference/commands/misc/remote.rst
reference/commands/misc/remove.rst

Instead of https://github.com/conan-io/docs/pull/1695

Merge master to develop

---

creating_packages/package_repo.rst
reference/commands/creator/upload.rst
reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/7048
Require https://github.com/conan-io/conan/pull/7107 to be merged

Docs about scm with missing fields

---

integrations/build_system/ninja.rst

close https://github.com/conan-io/docs/issues/1712

Set cmake_generator in conan.conf

---

reference/commands/consumer/config.rst
reference/config_files/settings.yml.rst

https://github.com/conan-io/conan/pull/6959

`conan config init` - update doc

---

developing_packages/editable_packages.rst

closes https://github.com/conan-io/conan/issues/7103

Note about editable packages and collect_libs

---

reference/config_files/settings.yml.rst

closes: https://github.com/conan-io/conan/issues/7002

- document libcxx

---

reference/tools.rst

docs for https://github.com/conan-io/conan/pull/7080

- add doc for tools.remove_files_by_mask

---

reference/tools.rst

docs for https://github.com/conan-io/conan/issues/7061

- docs for tools.msvs_toolset

---

reference/conanfile/methods.rst

Docs for https://github.com/conan-io/conan/pull/6945

export methods

---

reference/config_files/conan.conf.rst

related PR https://github.com/conan-io/conan/pull/7183

Add required_conan_version config

---

reference/config_files/conan.conf.rst

PS: Not sure why the last line was edited. Didn't touch it :\\

Added `revisions_enabled` to `conan.conf`

---

versioning/revisions.rst

Activate revisions **either by**: config or envvar (commented here: https://github.com/conan-io/conan/issues/7220#issuecomment-650343795)

Notice those are different ways to activate revisions

---

reference/tools.rst

Docs for https://github.com/conan-io/conan/pull/7178

Document "fix_symlinks" tool

---

installation.rst
systems_cross_building/cross_building.rst

Fixes CI errors in open PRs like https://github.com/conan-io/docs/pull/1754

Fix links with permanent redirect

---

devtools/build_requires.rst
reference/conanfile/attributes.rst
reference/profiles.rst

Docs for https://github.com/conan-io/conan/pull/7266

Document around user_info_build

---

reference/env_vars.rst

This adds documentation for the new environmental variables in https://github.com/conan-io/conan/pull/7154

Add docs for CLICOLOR/CLICOLOR_FORCE/NO_COLOR

---

reference/conan_v2_mode.rst
reference/conanfile/attributes.rst

Docs after https://github.com/conan-io/conan/pull/7174

Docs related to cpp_info

---

howtos/manage_shared_libraries/env_vars.rst

Just have seen this minor error while reading and think it should be corrected.

Adjusted comment to match copied file type

---

reference/conanfile/methods.rst

Documentation for https://github.com/conan-io/conan/pull/7389 regarding the https://github.com/conan-io/conan/issues/7347 issue

Document the return value of self.copy() in the package method

---

reference/conanfile/attributes.rst

https://github.com/conan-io/conan/issues/7251
https://github.com/conan-io/conan/pull/7399

Feature: add deprecated attribute

---

reference/commands/consumer/info.rst
reference/commands/consumer/install.rst
reference/commands/creator/create.rst
reference/commands/creator/test.rst
reference/commands/development/workspace.rst
reference/commands/misc/graph.rst

Docs for: https://github.com/conan-io/conan/pull/7167

Update --update help

---

extending/custom_settings.rst
reference/config_files/settings.yml.rst

https://github.com/conan-io/conan/pull/5705

Feature: add settings for clang-cl (clang on Windows)

---

reference/conanfile/attributes.rst

Document recipe_folder

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Docs for: https://github.com/conan-io/conan/pull/7404

Document load attributes in init() from data file

---

reference/config_files/client_certificates.rst
reference/config_files/conan.conf.rst

Docs for https://github.com/conan-io/conan/pull/7435

Document client_cert_path and client_cert_key_path conf variables

---

reference/conan_v2_mode.rst

https://github.com/conan-io/conan/pull/5740
https://github.com/conan-io/conan/issues/4322

Feature: improve compiler detection 

---

reference/conanfile/other.rst
reference/config_files/conan.conf.rst

Docs for https://github.com/conan-io/conan/pull/7360

Document required_conan_version for recipes

---

reference/conanfile/attributes.rst

https://github.com/conan-io/conan/pull/7337
https://github.com/conan-io/conan/issues/7252

[feat] Recipes declare what they provide (and this can create a conflict)

---

reference/conanfile/attributes.rst

Docs for: https://github.com/conan-io/conan/pull/7359

Document conditional generators

---

reference/conanfile/methods.rst
reference/tools.rst

Conan docs already explains it, but let's enforce if it's not clear.
closes #1779

Enforce build and patch togheter

---

reference/conanfile/methods.rst

Add warning about `distro` usage under the hood. Related to PR https://github.com/conan-io/conan/pull/7461

Add warning about 'distro'

---

reference/commands/consumer/config.rst

Related to https://github.com/conan-io/conan/pull/7583

Update config install types

---

integrations/cross_platform/android.rst
integrations/cross_platform/qnx_neutrino.rst
reference/tools.rst

Docs for https://github.com/conan-io/conan/pull/7534

Add docs about PkgConfig.version

---

faq/using.rst
reference/commands/consumer/info.rst

Closes: https://github.com/conan-io/docs/issues/1814

Fix deprecation messages for conan info

---

_themes/conan/footer.html
getting_started.rst

- Fix link
- Add onetrust to footer

Updating master with changes from develop

---

reference/config_files/settings.yml.rst

For: https://github.com/conan-io/conan/pull/7722

Add apple-clang 12

---

reference/generators/qbs.rst

Added a `REQUIRE3` which depends on `REQUIRE1` and `REQUIRE2`. This should show the usage of transitive dependencies.

Added example which shows transitive dependencies

---

_themes/conan/footer.html

Co-authored-by: Daniel <danimanzaneque@gmail.com>
Add changes in https://github.com/conan-io/docs/pull/1855 to master branch

add one trust footer on docs (#1855)

---

howtos/custom_generators.rst

Added docs for local cache generators feature

---

reference/conanfile/methods.rst

Related to https://github.com/conan-io/conan/pull/7704

Update self.copy ignore_case=True

---

reference/commands/creator/upload.rst

Related to changes in https://github.com/conan-io/conan/pull/7781
https://github.com/conan-io/conan/pull/7785

Update parallel help message and docs

---

uploading_packages/artifactory_ce.rst

The indentation of the Python snippet was wrong.

Fixed incorrect indentation

---

reference/tools.rst

https://github.com/conan-io/conan/issues/7820

Prefix intel function names with intel_

---

faq/troubleshooting.rst

Issue : https://github.com/conan-io/conan/issues/6802

feat: add section for contrained settings

---

deploy_gh_pages.py

Some parts of 404.html has been updated to look into "en/latest". I checked locally and it's working the search page and all menu links.
fixes #1690

Fix side menu for 404 page 

---

reference/generators/deploy.rst

see  conan-io/conan#7655
(corrected user compared to #1829 to accept CLA)

Update deploy for copying symlink to folders

---

reference/commands/misc/user.rst
reference/env_vars.rst

Docs for https://github.com/conan-io/conan/pull/7958

Docs about CONAN_LOGIN_ENCRYPTION_KEY

---

creating_packages/toolchains/cmake.rst
integrations/cross_platform/android.rst

Docs for https://github.com/conan-io/conan/pull/7843

Docs about Android toolchain

---

creating_packages/toolchains/msbuild.rst

https://github.com/conan-io/conan/pull/7941

msbuild toolchain helper

---

reference/commands/consumer/config.rst

Do not merge before: https://github.com/conan-io/conan/pull/7973
Docs for https://github.com/conan-io/conan/pull/7840

Add docs for config install single file

---

creating_packages/define_abi_compatibility.rst
faq/troubleshooting.rst

Docs for https://github.com/conan-io/conan/pull/7970

Docs for conan search suggestion to missing binary message

---

reference/conanfile/methods.rst

Recipe folder attribute has no method restrictions

---

integrations/build_system/cmake/cmake_find_package_generator.rst

shorter and does not mention a variable twice -> easier to understand

Use list instead of set

---

reference/commands/misc/remote.rst

Docs for: https://github.com/conan-io/conan/pull/8094

Document conan remote list_ref/list_pref --no-remote

---

creating_packages/toolchains/msbuild.rst

Docs for: https://github.com/conan-io/conan/pull/8073

Update MSBuildToolchain props file to conantoolchain

---

reference/config_files/conan.conf.rst
reference/env_vars.rst

Docs for: https://github.com/conan-io/conan/pull/8070

Add docs for keep_python_files

---

faq/troubleshooting.rst

Docs for https://github.com/conan-io/conan/pull/7996

Update case-sensitive error message

---

reference/config_files/conan.conf.rst

Some missing info from: https://github.com/conan-io/docs/pull/1942

Add keep_python_files to conf docs

---

reference/commands/consumer/install.rst
versioning/lockfiles/build_order.rst

Document https://github.com/conan-io/conan/pull/8077

doc --lockfile-node-id

---

reference/conanfile/methods.rst

Related to https://github.com/conan-io/conan/pull/7779

Add SystemPackageTool.install_packages

---

howtos/cmake_install.rst
reference/build_helpers/cmake.rst

Help with https://github.com/conan-io/conan/issues/8235

change boolean cmake.definitions

---

reference/tools.rst

Docs for https://github.com/conan-io/conan/pull/8116

tools.download - file is removed if checksum doesn't match

---

reference/generators/cmake_find_package.rst
reference/generators/cmake_find_package_multi.rst

CMake build modules are injected right after the targets are created

---

commands_help_update.py
reference/commands/consumer/config.rst
reference/commands/consumer/info.rst
reference/commands/consumer/install.rst
reference/commands/creator/create.rst
reference/commands/creator/export-pkg.rst
reference/commands/creator/export.rst
reference/commands/creator/new.rst
reference/commands/creator/test.rst
reference/commands/misc/lock.rst
reference/commands/misc/remove.rst

closes #1987
Docs for https://github.com/conan-io/conan/pull/8350

Update commands reference section

---

reference/config_files/settings.yml.rst
reference/tools.rst

on top of #1981 
docs for https://github.com/conan-io/conan/pull/8264

Add catalyst

---

reference/conanfile/tools/cmake.rst
reference/conanfile/tools/microsoft.rst
reference/config_files.rst
reference/config_files/conan_cfg.rst

https://github.com/conan-io/conan/pull/8266/files

new conf docs

---

integrations/cross_platform/buildroot.rst

buildroot.rst: Fix a typo

---

reference/config_files/settings.yml.rst

Docs for https://github.com/conan-io/conan/pull/8389

Change Catalyst to lowercase in docs

---

reference/conanfile/tools/meson.rst

docs for https://github.com/conan-io/conan/pull/8384

Fix: meson : add target and jobs arguments

---

creating_packages/define_abi_compatibility.rst
creating_packages/getting_started.rst
devtools/running_packages.rst
howtos/makefiles.rst
integrations/custom.rst
mastering/envvars.rst
reference/build_helpers/cmake.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst
reference/generators/b2.rst
reference/generators/cmake.rst
versioning/version_ranges.rst

From https://github.com/conan-io/tribe/pull/17#issuecomment-772314445
It makes sense to use lowercase packages everywhere in our docs.

fix lowercase package names

---

versioning/lockfiles/configurations.rst

This fixes a minor spelling mistake.

Fix spelling

---

reference/generators/cmake.rst
reference/generators/cmakemulti.rst

Document CONAN_SYSTEM_INCLUDES

---

versioning/revisions.rst

Re-submitting from my own fork, incorporating feedback from @memsharded : https://github.com/conan-io/docs/pull/2024

add note about revisions and line endings

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst
reference/conanfile/other.rst
reference/conanfile/tools/cmake.rst
reference/conanfile/tools/meson.rst
reference/conanfile/tools/qbs.rst
reference/generators/pkg_config.rst
reference/tools.rst

Add Conan version required for some popular features used on CCI.
My code editor hates extra spaces.
closes #2046

List required Conan version for features

---

reference/conanfile/tools.rst
reference/conanfile/tools/files.rst

Docs for: https://github.com/conan-io/conan/pull/8650

Document add tools (conan.tools) to apply patches

---

faq/using.rst

Close https://github.com/conan-io/conan/issues/8607
Close https://github.com/conan-io/conan/issues/6102

faq git servers

---

reference/profiles.rst

Related to https://github.com/conan-io/conan/pull/8685

Add relative path for profiles

---

reference/commands/consumer/config.rst
reference/config_files/conan.conf.rst

Related to https://github.com/conan-io/conan/pull/8769

Update config_install_interval description

---

mastering/policies.rst
reference/commands/consumer/install.rst
reference/commands/creator/create.rst
reference/commands/creator/test.rst

Related to https://github.com/conan-io/conan/pull/8483

Add --build=!skip for install command

---

reference/commands/consumer/config.rst
reference/config_files/global_conf.rst

Related to https://github.com/conan-io/conan/pull/8821
/cc @memsharded

Add conan config list command

---

creating_packages/package_approaches.rst

Docs for: https://github.com/conan-io/conan/pull/8767

warning to deprecate multi-config cpp_info

---

devtools/build_requires.rst
reference/commands/creator/test.rst

Docs for: https://github.com/conan-io/conan/pull/8787

test build_require

---

reference/conanfile/methods.rst

Close https://github.com/conan-io/docs/issues/2086

generate() docs

---

faq/troubleshooting.rst

Fix bad code block in troubleshooting.rst 

---

reference/config_files/global_conf.rst

Docs for https://github.com/conan-io/conan/pull/8895

configuration from build_requires
