conan-io/docs

examples/zmq_protobuf.rst

I tried the example and had problems. Turns out that the option block needs to be named "requires" instead of "requirements"

This needs to be called "requires" in conan 0.7.2

---

examples/boost.rst
examples/openssl.rst
getting_started.rst
integrations/cmake.rst
manage_deps/conanfile_py.rst
packaging/testing.rst

Cmake <2.8.12 fails in conanbuildinfo.cmake. It was probably undetected because even if we declare minimum 2.8, in practice we always use at least 2.8.12. @maitesin realized it was failing in travis, cause travis is cmake 2.8.7. 
I dont think we should change to support such old cmake syntax, so I have updated the minimum in the docs.

fixed minimun cmake

---

integrations/qbs.rst

We internally decided not to call it "Qt build suite" anymore.
See https://codereview.qt-project.org/#/c/161228/ and https://doc.qt.io/qbs/

Fix name of Qbs - it's now just "Qbs"

---

packaging/testing.rst

Hi,
I saw a few places where "test" was still used instead of "test_package"

Replace test by test_package

---

installation.rst

When installing conan manually from AUR, a user reports needing to install python-monotonic (see comments in https://aur.archlinux.org/packages/conan/) which is an AUR dependency of python-fasteners. It would be good to have this documented explicitly.

AUR - also install python-monotonic

---

howtos/custom_cache.rst

Replace incorrect ``//`` comments with ``#`` in bash examples

Fix comments in custom_cache.rst

---

integrations/appveyor.rst

* Change AppVeyor install instructions to use ```python-pip``` instead of Windows installer
* Improves reliability and generally works better
* Lack of Python won't be an issue in AppVeyor
See https://github.com/conan-io/conan/issues/706#issuecomment-263323890

Change AppVeyor install to use python-pip

---

installation.rst

Since version 0.16.0 conan requires the python port of node-semver. For Arch Linux it is packaged on AUR as python-node-semver.

Conan 0.16.0 requires node-semver

---

reference/commands.rst
reference/env_vars.rst
reference/tools.rst

Every command following the same structure:
- Command execution line help
- Command explanation
- Command complete parameter help
- Command examples
And unified with conan command help messages.
Changed command order, first the consumer commands, then the package creator commands and the conanfile methods invocation (package, imports, build) less used than others.

Reestructured commands and added missings docs

---

reference/commands.rst

Some rephrases.
Split long verbatim lines, because otherwise the end cannot be seen on
the docs.conan.io website (need to horizontal scroll).
Add link to JWT.

Review of reference/commands.rst

---

installation.rst

python-distro was missing from the list of AUR dependencies for Arch Linux, add it to the instructions.

Add python-distro to the list of AUR dependencies

---

installation.rst

python-pluginbase was missing from the list of AUR dependencies for Arch Linux, add it to the instructions.

Add python-pluginbase to the list of AUR dependencies

---

howtos/use_gtest.rst

- Updated GTest example tree to latest project version
- Added conan test_package approach to build the project
- Added step-by-step approach to build the project
- Preserved simple CMake approach to build the project
Please, consider this update after this [pull request](https://github.com/lasote/conan-gtest-example/pull/3)

3 ways to build GTest example

---

manage_deps/conanfile_txt.rst

Needs a space at least, otherwise `**` won't work. But backticks make more sense here.

Fix formatting

---

mastering/scopes.rst
reference/commands/info.rst
reference/commands/install.rst
reference/commands/package_files.rst
reference/commands/test_package.rst

Related to https://github.com/conan-io/conan/issues/1076#issuecomment-307995115
This ensures the command line is always identical for both ```test_package`` and ``install``

adding PkgName prefix to all options

---

integrations/gitlab.rst
packaging/bintray/conan_center_guide.rst
reference/commands/new.rst

This PR includes:
* Updated `conan new` reference to support Gitlab CI.
* Added step-by-step how to create a new Conan project in Gitlab.

#233 Update Gitlab integration

---

installation.rst

python-fasteners was moved from AUR to the official Arch Linux community repo. It can now be fetched automatically by pacman and makepkg.

Remove python-fasteners from AUR dependencies

---

manage_deps/conanfile_txt.rst

Make description of 'requires' section consistent with example: package owner should be 'pocoproject' instead of 'lasote'.

Update conanfile_txt.rst 'requires' description

---

getting_started.rst

- The document was referring to two different users for the Poco package; updated.
- Updated references from conan.io to Bintray repositories.
- Some minor English edits.

Minor editing improvements to Getting started.

---

reference/conanfile/attributes.rst

The settings paragraph jumped straight to the corner cases of header-only libraries and then customizing the settings and options, without first explaining the basis of the hash process and the "standard" values of `   settings = "os", "compiler", "build_type", "arch"` .  Seemed an easy place to add some clarity. Hope its correct :)

Added explanation of most common settings

---

reference/conanfile/attributes.rst
reference/env_vars.rst

After some experimentation and research I found that earlier Python versions can't take advantage of the long paths feature in newer Windows 10 builds. First version to support it is Python 3.6. I think it's important to note this in the docs.
https://stackoverflow.com/questions/46488118/win32-long-paths-from-python/46489473#46489473
https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

Added note about Win10 long paths feature only working with Python3.6

---

howtos/define_abi_compatibility.rst

Missing blank leads to wrong inline code highlighting

minor formatting fix

---

server.rst

Added example configuration for running Conan server installed from pip behind Apache as discussed in conan-io/conan#1986

Added example Apache configuration for using Conan installed from pip.

---

getting_started.rst

When trying the getting started guide from Ubuntu, the output of `conan` is hard to read due to conan-io/conan#456. The sentence added here mentions explicitly how to solve this issue.

Mention CONAN_COLOR_DARK in getting started guide

---

reference/build_helpers/cmake.rst
reference/build_helpers/meson.rst

- Renamed `cache_build_dir` to `cache_build_folder`
- Changed `build_dir` to `build_folder` in meson and cmake configures
- Changed `source_dir` to `source_folder` in meson and cmake configures

Fix build_dir and  source_dir in meson and cmake

---

reference/build_helpers/msbuild.rst

- Constructor section
- Methods and Constructor signature
- Defaulted values in properties
- Fix `build_env `variable
- Adds build description

Formatted MSBuild helper in reference

---

reference/commands/consumer/install.rst
reference/commands/creator/create.rst
reference/commands/creator/test.rst

**Do not use ' in bash code blocks**
Fixes warning generarintg docs: `WARNING: Could not lex literal_block as "bash". Highlighting skipped.`

Fix warnings in bash code blocks

---

index.rst
reference/commands/consumer/search.rst
reference/commands/misc/remote.rst
repositories.rst

Conan docs need to link to active repositories, or else people will look at the official repositories and see only 21 active packages, and will rightly assume that the community has abandoned Conan and it's not long for this world. For now I added bincrafters. Does anyone know any other active repositories?

Add a Repositories page

---

uploading_packages/bintray/uploading_bintray.rst

Saw that it said to get your repo to the top of the priority order you have to remove conan-center and conan-transit and then add the remote and re-add them.  Much simpler to just use --insert.

Updating note on remote prioritization

---

creating_packages/define_abi_compatibility.rst
creating_packages/package_approaches.rst
integrations/git.rst
integrations/other.rst
integrations/visual_studio.rst
mastering/conditional.rst
mastering/envvars.rst
mastering/virtualenv.rst
reference/conanfile.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst
reference/generators/cmake.rst
reference/tools.rst
systems_cross_building/cross_building.rst
uploading_packages/bintray/uploading_bintray.rst

Added:
- Broken link references.
- References to methods starting with *method*
- Better param explanation with default values.
- Descrition of build()
- SystemPackageTool small section.
- Formatting
Removed:
- conan_info() method.

Review of methods page in reference

---

conan1.0.rst
creating_packages/package_local_dev_flow.rst
getting_started.rst
using_packages/using_profiles.rst

Some bug fixes while using doc.
Only two warnings detected
```
13:04 $ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.6
making output directory...
loading pickled environment... not yet created
building [html]: targets for 156 source files that are out of date
updating environment: 156 added, 0 changed, 0 removed
reading sources... [100%] videos                                                                                                                      
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/pedro/git_projects/conan.io/docs/howtos/use_gtest.rst: WARNING: document isn't included in any toctree
done
preparing documents... …
```

Bugfixes 1.0.3

---

creating_packages/define_abi_compatibility.rst
creating_packages/package_approaches.rst
devtools/create_installer_packages.rst
devtools/running_packages.rst
howtos/manage_shared_libraries/env_vars.rst
mastering/virtualenv.rst
uploading_packages/bintray/uploading_bintray.rst
uploading_packages/remotes.rst
uploading_packages/uploading_to_remotes.rst

Output for html target:
```bash
13:20 $ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.6
making output directory...
loading pickled environment... not yet created
building [html]: targets for 156 source files that are out of date
updating environment: 156 added, 0 changed, 0 removed
reading sources... [100%] videos                                                                                                                                                         
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/pedro/git_projects/conan.io/docs/howtos/use_gtest.rst: WARNING: document isn't included in any toctree
done
preparing …
```

More fixes/enhancement

---

howtos/visual_studio_packages.rst

Not assigned to milestone, should be merged soon to master, as it is broken right now.

update how-to VS packages to 1.0

---

howtos/header_only.rst
reference/env_vars.rst
reference/tools.rst

fixes #511 
references conan-io/conan#2427
```
17:41 $ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.7
making output directory...
loading pickled environment... not yet created
building [html]: targets for 156 source files that are out of date
updating environment: 156 added, 0 changed, 0 removed
reading sources... [100%] videos
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/pvicente/git/conan/docs/howtos/use_gtest.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] videos
/Users/pvicente/git/conan/docs/integrations/android_studio.rst:90: WARNING: Could not lex literal_block …
```

Added references to CONAN_RUN_TEST in doc

---

getting_started.rst

The @ sign in "Poco/1.8.0.1@pocoproject/stable" was detected as being part of an email address and incorrectly converted to a mailto link.

doc: Fix conan requires converted to mailto link

---

using_packages/workflows.rst

`rm -rf *` may be dangerous if the `cd` before failed.
`rm -rf example-hello-build/*` might be dangerous if a space is added before the `*`.
Other danger is the user calling that from bash history but from the wrong directory.
A possible improvement would be:
`cd example-hello-build && rm -rf *`
As a bonus, I added a fix for a bash comment.

Avoid dangerous rm -rf

---

creating_packages/package_dev_flow.rst

Git through ssh links can't be resolved by a browser.

Fix link target, improve link text

---

howtos/python_code_reuse.rst

Missing `exports = "base_conan.py"` y the how-to example.
closes #591

Added exports for base class example

---

creating_packages/package_dev_flow.rst

Using $ as a prefix when you're describing a prompt is ok, as it's a reminder.
It helps knowing the command should be (in that specific context) called as a user ($ prefix) and not as root (# prefix).
However, sprinkling it everywhere adds more noise than information, and makes it harder to read.

Don't use $ for command names, improve bincrafter's blog link

---

reference/conanfile/attributes.rst

Added an explicit example on how to specify the default_options for a conditional requirement.

Default options on conditional requirements

---

reference/tools.rst

Add documentation to explain how to filter paths when decompressing files.
This explains the implementation for conan-io/conan#2938.

Explain wildcard filter for unzip and untargz

---

howtos/custom_generators.rst
howtos/manage_shared_libraries/env_vars.rst
reference/conanfile/methods.rst

Updated virtualrunenv generator and some fixes

---

reference/conanfile/methods.rst

removed links paramenter from copy in package()

---

reference/commands/consumer/config.rst

Fixes https://github.com/conan-io/docs/issues/697
Aside from what's advertised in the title, also added a bit to the discussion about `registry.txt`.

Document format of remotes.txt for conan config install

---

faq.rst

Is it OK in the TOC page? WDYT?

Slack in FAQ

---

installation.rst

The python-distro dependency has been moved into the community repo and does not have to be installed manually anymore.
pacaur has been unmantained for a while now: https://bbs.archlinux.org/viewtopic.php?pid=1755144#p1755144 . We should encourage use of other AUR helpers which are being kept up-to-date.

update installation docs for Arch Linux

---

reference/commands/consumer/config.rst

`code-block` directive without a language specification doesn't seem to work properly in sphinx. [The official documentation](https://docs.conan.io/en/latest/reference/commands/consumer/config.html) is missing that line completely. I couldn't find a version in the repo that has that error, so I assume it's not generated correctly.

Line from config.rst missing in official docs. (second try)

---

reference/commands/consumer/info.rst

Option name uses an hyphen, not an underscore:
--build-order, not --build_order
Fixes the documentation part of https://github.com/conan-io/conan/issues/3414

Fix `conan info` build order long option name

---

reference/conanfile/attributes.rst
reference/env_vars.rst

Windows 10 & 2016 Server MAX_PATH limit can be bypassed even with python 2.7

---

uploading_packages/running_your_server.rst

The previous suggested configuration works OK for search, but for me it fails on
upload.
Without a trailing slash in the remote, the urljoin implementation drops the
subdirectory from the URL created for http PUTs.
The suggested nginx configuration did not work for upload either. It fails to
preserve the query string, meaning the jwt token is lost. I'm no nginx expert, but the technique here worked for me to preserve all relevant information.

Fix docs for running conan_server in a subdirectory

---

reference/build_helpers/cmake.rst

In order to be taken into account, `cmake.definitions` must be set before calling `cmake.configure()`.

[fix] CMake definitions must be assigned before calling cmake.configure()

---

requirements.txt

closes #826 
Looks this is an already reported issue in sphinx-doc/sphinx#5460
Pinning sphinx version to 1.7.9 seems to solve the issue. This also explains why it worked locally first aand then it didn't: I run pip install again
Also sphinx 1.8.0 was released ton September 12th (https://pypi.org/project/Sphinx/#history), just few days before the issue was reported.

Fix search: pin sphinx version to 1.7.9

---

changelog.rst
reference/conanfile/methods.rst
uploading_packages/bintray/conan_center_guide.rst

Documentation for https://github.com/conan-io/conan/pull/3517

Document ConanInvalidConfiguration, fix some indentation issues

---

reference/conanfile/attributes.rst

Encourage use of SPDX licenses in the "license" attribute of ConanFile

---

reference/tools.rst

tools.collect_libs now use self.cpp_info.libdirs

---

reference/config_files/default_profile.rst

There was a linting warning in the spell check for "*overrid**d**en*"

Fix typo and structure in default profile section

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Separated attribute sections of ``options`` and ``config_options``.
Cross-referenced sections.
closes #816

Setting conditional default options

---

reference/build_helpers/cmake.rst

The table was not displayed in the docs page

Fix CMake definitions table

---

howtos/capture_version.rst

Add `howto` to use subversion to generate version string. See #861 for related issue.
closes #861

Example for SVN versioning

---

Makefile
conf.py
deploy_gh_pages.py
make.bat
make_mac.sh
reference/build_helpers/autotools.rst

This PR enables warnings as errors only for `make html` command
```
(conan_docs) λ make html
Running Sphinx v1.7.9
Initializing Spelling Checker
loading pickled environment... done
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] reference/build_helpers/autotools
Warning, treated as error:
C:\Users\danimtb\conan_docs\reference\build_helpers\autotools.rst:304:Malformed table.
+--------------------+-------------------------------------------------------------------------------------+
| NAME               | DESCRIPTION                                                                         | …
```

Raise error with malformed table warning (with test)

---

integrations/gitlab.rst

If the Gitlab CI runner is installed with default settings ON WINDOWS, it may run under the service/system account which has no %HOME% directory.  The Gitlab CI configuration should set CONAN_USER_HOME so that the local cache can be used correctly.

Gitlab CI runner may need CONAN_USER_HOME set on Windows.

---

extending.rst
extending/hooks.rst
reference.rst
reference/commands/consumer/config.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst
reference/hooks.rst

Docu changes for PR conan-io/conan#3867

Renamed Plugins to Hooks

---

videos.rst

closes #929 
I have included the JFrog Conan Playlist in youtube (does not contain all videos of Conan) and added the ones missing from SwampUP

Included swampUP 2018 videos, jfrog conan playlist and reviewed section

---

integrations/premake.rst

Seems this was the last bit to make the Premake Poco example work: Propagating the defines.
There are other flags missing (`conan_cppflags`, `conan_cflags`, `conan_sharedlinkflags `& `conan_exelinkflags`) but it is a small starting example, not a full one...

Propagate defines in Premake example

---

reference/env_vars.rst

Responsible code: https://github.com/conan-io/conan/blob/d9a75eff01098338d4d242d8591a704e75bf3a9c/conans/client/userio.py#L105

Explicitly mention that remote name is uppercased

---

.github/settings.yml

Has to be merged to develop branch for changes to take effect
After merge we need to activate the app here: https://probot.github.io/apps/settings/

Adds github settings file for portable labels

---

reference/conanfile/attributes.rst

Some additional information and rephrasing.
closes conan-io/conan#3956

Clarifies builddirs and build_paths in package info

---

reference/generators/cmake_find_package.rst

Added a missing colon to the name of the target.

Fixing a target name typo at the cmake_find_package generator reference

---

reference/build_helpers.rst
reference/generators.rst

Description about build helpers and generators

---

changelog.rst

Add `include_prerelease` and `loose` option to version range expression

Update changelog: Add include_prerelease and loose option

---

howtos.rst
howtos/extract_licenses_from_headers.rst
uploading_packages/bintray/conan_center_guide.rst

Hi!
This PR is related to #968 
I moved the section the explain how to extract a license from a header file to "Howtos" tree.
closes #968

#968 Move how to extract license

---

faq/troubleshooting.rst
reference/conanfile/attributes.rst

Related issue: https://github.com/conan-io/conan/issues/4036
- Add note about conan 1.8 restriction and default options as dict
- Add FAQ about known error related to outdated conan version and default_options

#4036 Add info about default options as dict

---

extending/hooks.rst
reference/commands/consumer/config.rst

Docs for PR https://github.com/conan-io/conan/pull/4106
Issue related conan-io/conan#3593

Added hooks management documentation

---

reference/build_helpers/visual_studio.rst

https://github.com/conan-io/conan/pull/4113

Document MSBuild changes

---

creating_packages/package_repo.rst
reference/conanfile/attributes.rst
reference/tools.rst

Related to https://github.com/conan-io/conan/pull/4088
As SCM are evaluated in the user workspace where the ``conanfile.py`` is located before exporting it to the cache, it accepts arbitrary complex functions to compute the value of its attributes (it is needed to ensure consistency of some SVN workflows).

Docs related to the evaluation of SCM attributes

---

devtools/build_requires.rst

At least comment it in the docs.
Is it something that we want to deprecate? I think so.
Maybe even remove in Conan 2.0 the automatic injection of PYTHONPATH from the dependencies, for all methods?

deprecating old python reuse

---

integrations/premake.rst
reference/generators/premake.rst

docs for PR conan-io/conan#3945

 Premake conan_basic_setup() and example update

---

changelog.rst
howtos/header_only.rst
integrations/pkg_config_pc_files.rst
integrations/visual_studio.rst
integrations/xcode.rst
mastering/logging.rst
mastering/virtualenv.rst
reference/build_helpers/autotools.rst
reference/build_helpers/cmake.rst
reference/build_helpers/run_environment.rst
reference/build_helpers/visual_studio.rst
reference/config_files/conan.conf.rst
reference/env_vars.rst
reference/tools.rst
systems_cross_building/windows_subsystems.rst

This PR does not modify the content of any section in the docs.
Tasks done:
- Fromatting: Line lenght, text style and casing
- Hyperlinks for every entry in now starting with **tools_**
- Environment variables hyperlinks also renamed starting with **env_vars_**
- Cross-reference to environment variables
- Use of hyperlinks in the rest of the documentation to avoid writing titles again:
Instead of using
```
:ref:`tools.cpu_count()<tools_cpu_count>`
```
now it is
```
:ref:`tools_cpu_count`
```
⚠️ ❗️  Please remember to merge this PR to **develop** too once it is merged to avoid last minute conflicts in the next release

Refactor/review of the Tools section

---

reference/profiles.rst
using_packages/using_profiles.rst

Docs for https://github.com/conan-io/conan/pull/4308

profile composition

---

reference/build_helpers/cmake.rst
reference/generators/cmake.rst

Related PR: https://github.com/conan-io/conan/pull/4509
Hi!
This PR reverts the documentation about default CMake generator on Windows.

conan-io/conan#4265 Revert default cmake gen on Windows

---

uploading_packages/bintray/conan_center_guide.rst

After copying/pasting one of these snippets, I noticed that I was getting the error:
```
ERROR: 
TypeError: package() takes 0 positional arguments but 1 was given
```

Fix code snippets

---

reference/build_helpers/autotools.rst

Missing import tools in autotools build helper

---

integrations/other.rst
reference/build_helpers/visual_studio.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst
reference/generators/compiler_args.rst
reference/generators/make.rst

Docs for https://github.com/conan-io/conan/pull/4611
As we are deprecating member `cppflags` of `CppInfo` in favor of `cxxflags` all the references to it should be changed.

All references to cpp_info.cppflags are being changed to cxxflags

---

howtos/manage_shared_libraries/rpaths.rst

closes #1002 
Pointing this to develop as the issue was assigned to the 1.13 milestone

Adds CMAKE_BUILD_WITH_INSTALL_RPATH to RPATH how to

---

creating_packages/define_abi_compatibility.rst
developing_packages/workspaces.rst
howtos/custom_generators.rst
reference/config_files/conan.conf.rst

explain package_id_modes WIP

---

reference/config_files/editable_layout.rst

Jinja2 engine requires double braces.

Fix typo in docs related to editable layout files

---

reference/config_files/conan.conf.rst
reference/generators/cmake.rst
reference/generators/cmakemulti.rst

Before writing the docs for conan-io/conan#4721, I took a look at the cmake generator one and found some missing pieces.
This PRs documents the missing parts and structures and homogenizes the whole section similarly to the build helpers one.

 Refactorize and complete cmake generator section

---

reference/conanfile/methods.rst

How does SystemPackageTool use sudo when CONAN_SYSREQUIRES_SUDO is not defined?
related issue: https://github.com/conan-io/conan/issues/4770
related PR: https://github.com/conan-io/conan/pull/4774

Explain about SystemPackageTool and sudo

---

mastering/revisions.rst
reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/4767

Document ConanFile::revision_mode attribute

---

integrations/cmake.rst
integrations/cmake/cmake_find_package_multi_generator.rst
reference/generators.rst
reference/generators/cmake_find_package_multi.rst

https://github.com/conan-io/conan/pull/4714

find package multi generator

---

changelog.rst

Typo: v1.13.3 was not identified in the changelog

Version 1.13.3 was not identified in the changelog

---

reference/commands/misc/inspect.rst

Docs for https://github.com/conan-io/conan/pull/4903

Update documentation of 'inspect' command with '--raw' attribute

---

reference/tools.rst

Docs for https://github.com/conan-io/conan/pull/4963

Docs for tools.Version()

---

reference/build_helpers/visual_studio.rst

Docs for https://github.com/conan-io/conan/pull/5052

MSBuild: Added False value to toolset

---

integrations/travisci.rst

- sudo is no longer required since xenial is available as distro
- Xenial contains GCC 5.4 and CMake installed
- Fix generator name
You can see the result of this file here:
https://travis-ci.com/uilianries/conan-hello-openssl/builds/110174951

Fix Travis file example

---

howtos/manage_cpp_standard.rst
reference/build_helpers/cmake.rst
reference/build_helpers/visual_studio.rst
reference/conanfile/methods.rst
reference/config_files/settings.yml.rst

Doc for https://github.com/conan-io/conan/pull/4917

Docs for compiler.cppstd subsetting

---

reference/tools.rst

- Both tools.Git and tools.SVN are able to retrieve the latest
commit message aka log message
Related PR: https://github.com/conan-io/conan/pull/4877

Get commit message

---

howtos/custom_generators.rst
integrations/other.rst
reference/generators.rst
reference/generators/custom.rst
reference/generators/deploy.rst
reference/tools.rst

Docs for PR conan-io/conan#4972
Issue conan-io/conan#4847
- Added section for generator class reference
- Removed duplicated info in how-to about generator packages
- Updated custom integration in the integration section

Docs for deploy generator and review of existing info

---

creating_packages/external_repo.rst
creating_packages/getting_started.rst
creating_packages/package_approaches.rst
creating_packages/package_repo.rst
reference/commands/creator/export-pkg.rst
reference/commands/development/build.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Docs for PR conan-io/conan#5069
Issue conan-io/conan#4916

Updated hello link to conan-io/hello repo

---

reference/commands/creator/export-pkg.rst

Update docs according to: https://github.com/conan-io/docs/pull/1232#discussion_r289292757

Clarify behavior of package()

---

creating_packages/package_repo.rst

Rewrite of the SCM optimization tip box

---

reference/config_files/settings.yml.rst

related issue conan-io/conan#5328
related PR conan-io/conan#5357

Add apple-clang 11 to settings.yml

---

reference/generators/cmake.rst

Bring back CONAN_DISABLE_CHECK_COMPILER for cmake generator

---

reference/profiles.rst

Modify docs according to the changes here https://github.com/conan-io/conan/pull/5373

Note about using only forward slashes for PROFILE_DIR variable

---

howtos/vs2017_cmake.rst
reference/conanfile/attributes.rst

Failed in https://github.com/conan-io/docs/pull/1355

[FIX MASTER] Fix windows path limitation link

---

reference/build_helpers/cmake.rst

There was a mistake in the docs as build_type does not have effect when using CMake multi-configuration generators such as Visual Studio or XCode.
Related to conan-io/conan#5448

correct setting of CMAKE_BUILD_TYPE explanation 

---

getting_started.rst
installation.rst
using_packages/conanfile_txt.rst
using_packages/using_profiles.rst

* Some small fixes of typos and grammar
* Added note about 'venv' for Python 3
* Linked example repository
* Fixed outdated content (conan output, md5 example etc.)
* Added mandatory path ("..") to full "conan install" invocation examples
where missing
* Changed "." to ".." for "conan install" where present, because
out-of-tree builds should be done.

Improve documentation intended for package consumers

---

creating_packages/existing_binaries.rst

I think existing_binaries.rst was missing a variable name in the HelloConan build() method.

fix typo in def build(self)

---

reference/commands/misc/graph.rst
versioning/lockfiles.rst

Docs for https://github.com/conan-io/conan/pull/5533

remove clean-modified command

---

devtools/running_packages.rst

The hello world project doesn't store the binary "greet" (or "greet.exe") in the build directory hello/bin. I think it stores it directly in the directory bin.
So in order for the recipe to work this change has to be made. After it, the console shows 
Hello/0.1@user/testing package(): Packaged 1 file: greet
but before the fix that line it's not shown.

Correct binary build path in doc

---

developing_packages/editable_packages.rst

The domain for jinja documentation changed a probably there was some downtime of the domain.
Now it is redirected (that's why the CI in master branch is green), but better add the new link

[FIX DEVELOP] Fix jinja URL

---

devtools/running_packages.rst

The paragraph describing virtualenvs contained the following sentence: "By default, Conan does not modify by default the environment (...)". The second redundant "by default" was removed.

Remove redundant "by default" from virtualenv section

---

reference/commands/misc/remote.rst

This PR documents the `enable` and `disable` subcommands commented in https://github.com/conan-io/conan/issues/5544 and https://github.com/conan-io/conan/pull/5623

add enable and disable subcommands

---

reference/commands/consumer/info.rst

The command `info --paths` is not examplyfied in the docs.

Add info --paths example

---

reference/config_files/settings.yml.rst

Add clang version 9 to default list of compilers now that llvm 9 is officially released

Add clang 9

---

reference/conanfile/methods.rst

Docs for https://github.com/conan-io/conan/pull/5893/files

shared_library_package_id()

---

howtos/capture_version.rst

The notes about returning None to force reading the version information
from the package metadata don't seem correct. From experience the
version always comes from the package metadata once it has been
exported.
Simple correction, please let me know if something more elaborated is desired.

Review extract version documentation

---

reference/tools.rst

docs for https://github.com/conan-io/conan/pull/5904 (https://github.com/conan-io/conan/issues/5870)

Feature: allow to skip x86_64 -> x86 in cross_building (same os)

---

reference/config_files/conan.conf.rst

The link for the requests library appears to have changed from:
http://docs.python-requests.org/en/latest/user/advanced/#proxies
to
https://requests.kennethreitz.org/en/latest/user/advanced/#proxies

Fix requests library proxies link in docs

---

getting_started.rst

both
`conan search 'Poco*' --remote=conan-center`
and 
`conan search Poco --remote=conan-center` 
would work here, but the latter is more straight-forward and the page explains the Search command further later on

remove * from the first search example

---

extending/hooks.rst
howtos/sanitizers.rst
reference/env_vars.rst
reference/hooks.rst

Fix https://github.com/conan-io/docs/issues/1418
My main objective here was to differentiate the contents of the _Extending_ and the _Reference_ sections in the first paragraph of each page (I'm not sure if I've been able to do it). There are also some minor changes

Some changes related to hooks documentation

---

reference/conanfile/methods.rst
reference/config_files/conan.conf.rst

As commented on https://github.com/conan-io/conan/pull/5791 for Fedora starting with Fedora 31 yum will be removed. This PR adds documentation for the DnfTool

Add DnfTool to the SystemPackageTool docs

---

reference/config_files/conan.conf.rst

Removes the paragraph that says that removing the `[proxies]` section makes _requests_ not to use the system proxies.
Closes #1448

Fix docs about proxies section

---

creating_packages/define_abi_compatibility.rst
reference/conanfile/methods.rst

Docs for https://github.com/conan-io/conan/pull/5837

compatible ids

---

installation.rst

Conan 1.20 depends on patch-ng instead of patch. patch-ng is now packaged for Arch Linux as python-patch-ng.

List python-patch-ng as a dependency on Arch Linux

---

getting_started.rst

I noticed you can't access remotes by default with conan search and added a note about it to that section in getting started. #[6093](https://github.com/conan-io/conan/issues/6093) I will take a look at updating the docs on the search command in the hopes that putting the words default and remote will let google find it.

Mentioned needing to specify remotes in search

---

reference/commands/creator/create.rst

As explained in https://github.com/conan-io/conan/pull/6131 the --build policy help message was the same for the commands create, test, install and workspace but the behavior for the create command by default was not to behave as `--build=never` but as `--build=package name` which could be misleading.

Change create command build policy documentation

---

faq/troubleshooting.rst

typically --> typical
occurs in sentence: The settings.yml file is just a mechanism so users agree on a common spelling for typically settings.

spelling mistake fix

---

reference/commands/misc/conan_build_info.rst

conan_build_info --v2 `--multi-module` and `--skip-env` arguments are removed in 1.20.5 by https://github.com/conan-io/conan/pull/6169 to simplify the command.

Remove arguments from conan_build_info --v2 as fixed in release 1.20.5

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst
reference/generators/cmake.rst
reference/generators/cmake_find_package.rst
reference/generators/cmake_find_package_multi.rst
reference/generators/cmake_paths.rst
reference/generators/pkg_config.rst

Document changes introduced by https://github.com/conan-io/conan/pull/6033
Now a different name can be specified for each generator that supports the `cpp_info.name` property.

Documents cpp_info.names["generator_name"] feature

---

howtos/manage_cpp_standard.rst
reference/tools.rst

Related PR: https://github.com/conan-io/conan/pull/5997

Add tools.cppstd_minimum_required

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Biten again by some corner and weird case of private requirements abuse. I think at least we should discourage their use in the docs.

discourage private requirements

---

reference/build_helpers/visual_studio.rst

At first glance, the `use_env` parameter seems to imply the intuitive idea that no environment variables will be used in a build (but it doesn't).  I was the one who originally requested the feature, and a year later, even I thought this would be the case.  It's not Conan's fault, the parameter directly maps to the equivalent `MSBuild` flag/parameter and that makes sense.  The confusion comes from believing this flag maps to some internal Conan behavior, in which case one might expect the `MSBuild` helper to skip the application of the environment variables to the process.  But, since it doesn't, this clarification should be helpful to those trying to understand what's happening while debugging.

MSBuild use_env parameter: Clarify behavior

---

creating_packages/package_repo.rst
reference/conanfile/attributes.rst
reference/config_files/conan.conf.rst
reference/config_files/conandata.yml.rst

Docs for https://github.com/conan-io/conan/pull/6334

Docs about 'scm_to_conandata'

---

installation.rst

Docs for https://github.com/conan-io/conan/pull/6336

Update py2 deprecation notice

---

installation.rst

Docs for https://github.com/conan-io/conan/pull/6355

Remove warning about py38 introduced in #1519 and #1517

---

mastering/custom_cache.rst
reference/env_vars.rst

Based on follow commands:
```
$ conan --version
Conan version 1.21.1
$ export CONAN_USER_HOME=/tmp/foo
$ conan profile new default --detect
Found gcc 9.2
Found clang 9.0
gcc>=5, using the major as version
Profile created with detected settings: /tmp/foo/.conan/profiles/default
```
As you can see, `CONAN_USER_HOME` determines the base folder for conan cache folder, not the conan cache itself.
I didn't check on Windows, but I presume the result will be the same.
Related on issue https://github.com/conan-io/conan/issues/6407

Update Conan cache folder description

---

integrations/build_system/cmake/cmake_generator.rst
reference/generators/cmake.rst
reference/generators/cmakemulti.rst

For Conan 1.22 we'll set the generated targets as `GLOBAL` so that they can be added as `ALIAS`: https://github.com/conan-io/conan/pull/6438

Add GLOBAL for targets

---

configuration.rst
configuration/download_cache.rst
index.rst
reference/config_files/conan.conf.rst

Docs for https://github.com/conan-io/conan/pull/6287

configuration section and download cache docs

---

configuration/download_cache.rst

Docs for https://github.com/conan-io/conan/pull/6475

remove note v1-v2 cache

---

reference/commands/misc/graph.rst
versioning/lockfiles.rst

This reverts commit e5f252712b67d4d37d8c0c512b97810f4c08a4f0.

Put back graph clean-modified subcommand

---

conf.py
howtos/generic_ci_artifactory.rst
integrations/ci/jenkins.rst
uploading_packages/remotes.rst

Continuation of #1570
This is required in order to merge #1569 and #1568

Fixed links and improved linkcheck

---

howtos/run_conan_in_docker.rst
integrations/cross_platform/android.rst

We are using and maintaining the images in Conan Docker Tools for open source usage and we'd like to clearly state that in the documentation and warn people to not use them in production or do it at their own risk.
Please provide feedback about the text and I will open a PR later to the readme on the conan-docker-tools repo.

Warning for conan-docker-tools images

---

configuration/download_cache.rst
reference/commands/consumer/install.rst
reference/commands/creator/create.rst
reference/config_files/conan.conf.rst

Docs for https://github.com/conan-io/conan/pull/6632

parallel download

---

conf.py

We are getting some 429 errors from GitHub because of too many requests

Less workers to check URLs

---

faq/troubleshooting.rst

Update missing package warning message:
- Using CCI package czmq for demonstration;
- Added the new information: Requirements;
- There is only one occurrence of that warning message in docs;
- As semver_direct_mode is not affected by minor and patch version, all requirements show placeholders.
Related issue: https://github.com/conan-io/conan/pull/6700

Update build missing warning message

---

getting_started.rst
reference/commands/consumer/info.rst
reference/commands/output/info.rst

Related PR: https://github.com/conan-io/conan/pull/6724

Add description to info output

---

reference/config_files/settings.yml.rst

docs for https://github.com/conan-io/conan/pull/6740

Feature: on Mac, Intel C++ is based on Apple Clang

---

reference/tools.rst

Related PR: https://github.com/conan-io/conan/pull/6548

Raises ConanException for check_min_cppstd

---

integrations/build_system/cmake/cmake_find_package_generator.rst

There is a typo in the example code where the `build()` method contains a `CMake` object instantiation without the module being imported appropriately in the beginning of the example.

Fixing typo for cmake_find_package generator example

---

reference/env_vars.rst

Documentation was inconsistent about which name was correct. Per [discussion in #conan](https://cpplang.slack.com/archives/C41CWV9HA/p1587398710012500) and [uses in conan-center-index](https://github.com/conan-io/conan-center-index/search?q=CONAN_RUN_TESTS&unscoped_q=CONAN_RUN_TESTS) the plural is correct.

Fix typo: it's CONAN_RUN_TESTS, not CONAN_RUN_TEST

---

creating_packages.rst
creating_packages/package_information.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Add component requires information

---

reference/commands/consumer/config.rst
reference/config_files/conan.conf.rst

- Add config_install_interval description in conan.conf
- Add conan config install scheduler details
related PR: https://github.com/conan-io/conan/pull/6824

Add info about config_install_interval

---

devtools/build_requires.rst
reference/tools.rst
systems_cross_building/cross_building.rst

Docs for https://github.com/conan-io/conan/pull/6769 and https://github.com/conan-io/conan/pull/6916

Documentation related to settings_build and settings_target

---

404.html

After trying some experiments, I just realized the redirection problem is related to Github pages, not sphinx.
The github documentation says to add a 404.html file for a custom "Not Found Page": https://help.github.com/en/enterprise/2.13/user/articles/creating-a-custom-404-page-for-your-github-pages-site
Thus, this new 404.html in this PR will redirect to https://docs.conan.io/en/latest/404, which is our custom page.
/cc @memsharded

Add 404 page for gh-pages

---

reference/conanfile/methods.rst

PR https://github.com/conan-io/conan/pull/6940 changes the order of execution of `set_name/version` and the assignment of these values from the command line. Some users rely on this behavior, we should document it.
If merged, we should update the comment for `Docs` in the PR.

Document order of execution of 'set_name' and 'set_name' regarding CLI

---

reference/tools.rst

docs for https://github.com/conan-io/conan/pull/7082

- add docs for tools.stdcpp_library

---

reference/tools.rst

docs for https://github.com/conan-io/conan/pull/6735 and https://github.com/conan-io/conan/pull/7135

- add docs for compilervars

---

reference/generators.rst
reference/generators/msbuild.rst

Docs for https://github.com/conan-io/conan/pull/7035

msbuild generator

---

creating_packages/package_approaches.rst

Now with components, this syntax abuse should no longer be in the docs.

Remove 'cpp_info.<config>' syntax abuse

---

creating_packages/package_information.rst
reference/conanfile/attributes.rst
reference/generators/cmake_find_package.rst

Docs for https://github.com/conan-io/conan/pull/7108

Documentation for components and cmake_find_package generator

---

howtos/capture_version.rst

The example to capture the package version from a CMakeLists.txt contains a wrong string suffix.
Executing the example will result in `TypeError: cannot use a bytes pattern on a string-like object`.
Replace with 'r' prefix.

Fix exception in capture package version example

---

devtools/build_requires.rst
devtools/create_installer_packages.rst
reference/profiles.rst
systems_cross_building/cross_building.rst

The feature is working great, we are not planning to remove or change anything about it, but we need to warn people that new functionalities are features/fixes and not bugs that we can solve right away. We need to evaluate the requirements before adding new functionality.

Add some experimental warnings to the xbuild feature

---

reference/generators/cmake_find_package_multi.rst

Docs for https://github.com/conan-io/conan/pull/7259

Add components reference to cmake_find_package_multi generator

---

creating_packages/package_repo.rst
reference/conanfile/attributes.rst
versioning/revisions.rst

This PR removes from experimental two conan features:
- Revisions
- The use of scm mode but only when used with `scm_to_conandata`

Remove experimental warning

---

reference/commands/creator/new.rst

Docs for the following feature: https://github.com/conan-io/conan/pull/7215
Note: command line `--help` output was not updated, because it appears that it's heavily outdated for a lot of files anyway (i.e. `commands_help_update.py` changes a lot of files).

Updated docs for conan new --template

---

howtos/generic_ci_artifactory.rst
reference/commands/misc/conan_build_info.rst

Do not recommend the use of the BuildInfo until problems are solved.

Add warnings for BuildInfo

---

reference/conanfile/attributes.rst

This documents the new `filename` attribute as described by
[issue 7254](https://github.com/conan-io/conan/issues/7254).

adds notes on `filename` attribute

---

reference/conan_v2_mode.rst

Docs for: https://github.com/conan-io/conan/pull/7327

Document fail if build_type or compiler is not defined for build helpers CONAN_V2_MODE

---

reference/generators/pkg_config.rst

Docs for conan-io/conan#7413
Issue conan-io/conan#7330

Explanation about components in the pkg_config generator

---

reference/tools.rst

Robustly rename a file or folder to avoid 'Access is denied' on Windows.

robust rename a file or folder to avoid 'Access is denied' on Windows.

---

reference/config_files/settings.yml.rst

Corresponding docs PR to conan-io/conan#7601.
Updates the `settings.yml` page to include Xcode 12 as a supported compiler.

Add Xcode 12

---

integrations/ide/clion.rst

First PR was not totally clear according @BraverO suggestion.
This one uses HTML metadata only for CLion Plugin and its description.
The HTML pages doesn't show the metadata content, it is only displayed when reading the HTML source.
/cc @BraverO
Current result:

Add metadata for CLion plugin

---

reference/commands/creator/export.rst

It is not clear how to export a recipe that does not contain the name/version but without specifying a user/channel. I had to dig into the code, make changes, finally see that there are tests covering failing and I finally managed to learn the syntax from the tests themselves.

Instruction for exporting a package without user/channel

---

creating_packages/package_information.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Docs for https://github.com/conan-io/conan/pull/7644

Document 'cpp_info.requires'

---

reference/config_files/settings.yml.rst
reference/env_vars.rst

Related to https://github.com/conan-io/conan/pull/7871

Add Clang 11

---

howtos/custom_generators.rst

There was one actual error on this doc which has been corrected (the class had uppercase characters but the instructions with the reference was all lowercase. Made class name lowercase to match recommended convention.  Also, updated several other items in the document to be lowercase and/or add cosmetic improvements.

change all generator names/refs to lowercase

---

deploy_gh_pages.py

When running deploy process, the internal 404.html file will be copied to root level, and internal paths will be updated. By default, it uses en/latest as reference, because we can have only one file at root level.
fixes #1690

Generates 404 HTML by CI job

---

deploy_gh_pages.py

I hope this should be our last fix ...
So far, the URL https://docs.conan.io/foobar works well, 404 intercepts the bad address and shows https://docs.conan.io/404.html instead.
However, it doesn't work for https://docs.conan.io/en/latest/foobar, but why? All references in 404.html points to en/latest/404.html, including theme folder, thus the result is the current url + the url in 404.html = https://docs.conan.io/en/latest/en/latest/404.html (same for theme)
As I can't reproduce it locally, because requires some configuration for redirection, so I uploaded to my personal github pages: https://uilianries.github.io/en/latest/dasdadasd. As you can see, now it works.
As 404.html is an unique file, I forced to en/latest, so it points now to the absolute URL for docs.conan.io instead of …

Add prefix url for 404

---

README_DEPLOY.txt

This PR add more details how to execute test related to gh-pages.
Running 'make html' and take a look on the result is pretty easy, but if you want to check the deployment result, it requires more steps.
Related to #1898

Add details how to test gh-pages

---

conan1.0.rst
conf.py

Two minor fixes to release:
* An indent typo in the format.
* Problem in `conf.py` file, fails if building out of sources.

Fix release/1.5.2

---

creating_packages/toolchains.rst
creating_packages/toolchains/cmake.rst
creating_packages/toolchains/make.rst
creating_packages/toolchains/msbuild.rst
integrations/build_system/make.rst

Docs for https://github.com/conan-io/conan/pull/8101 and https://github.com/conan-io/conan/pull/8096

Document generate for toolchains and deprecate toolchain and write_toolchain_files

---

reference/generators/cmake_find_package.rst
reference/generators/cmake_find_package_multi.rst

Docs for https://github.com/conan-io/conan/pull/8114

Add note about shared global target in CMake components

---

versioning/lockfiles/evolving.rst

Docs for https://github.com/conan-io/conan/pull/8054

documentation for --build unlock of lockfiles

---

creating_packages/toolchains.rst
creating_packages/toolchains/meson.rst

docs for https://github.com/conan-io/conan/pull/7662

Feature: meson toolchain

---

mastering/conditional.rst
reference/conanfile/methods.rst

Docs for https://github.com/conan-io/conan/pull/8053

validate docs

---

integrations/build_system/make.rst

There is no "Make" in scope, this is also consistent with docs/creating_packages/toolchains/make.rst.

Fix conanfile.py in make.rst

---

creating_packages/toolchains.rst
creating_packages/toolchains/qbs.rst
reference/build_helpers.rst
reference/build_helpers/qbs.rst

Documentation for https://github.com/conan-io/conan/pull/8125

Add documentation for qbs build helper and qbs toolchain

---

reference/config_files/settings.yml.rst
reference/tools.rst

docs for https://github.com/conan-io/conan/pull/8263

- docs for os.sdk (apple)

---

reference/config_files/settings.yml.rst

docs for https://github.com/conan-io/conan/pull/8032

- add e2k (Elbrus) architectures

---

reference/conanfile/attributes.rst
reference/conanfile/methods.rst

Docs for build modules per generator in cpp_info

---

systems_cross_building/cross_building.rst

closes: #1973 
update information about Android usage:
- standalone toolchain is deprecated, remove mention
- GCC is deprecated, remove mention

- update information about Android

---

installation.rst

Comes from https://github.com/conan-io/conan/issues/8252
Running from sources docs is outdated, ``pip install -e .`` is much better

fix docs about running from sources

---

devtools/create_installer_packages.rst
howtos/other_languages_package_manager/go.rst
howtos/run_conan_in_docker.rst
integrations/build_system/cmake/find_packages.rst
integrations/ci/jenkins.rst
integrations/cross_platform/buildroot.rst
reference/commands/output/user.rst
systems_cross_building/cross_building.rst
uploading_packages/remotes.rst

As Conan Community is officially deprecated, it should not be listed in the official documentation.
Some examples in docs are still present in Conan Community (because we didn't have conan-io/examples when they were created). Thus, this PR is linked to https://github.com/conan-io/examples/pull/74 and https://github.com/conan-io/examples/pull/75

Remove conan community from docs

---

.ci/test.jenkins
integrations/cross_platform/buildroot.rst

We only fail the CI job if the linkcheck fails when the commit is merged to master. That avoids some spurious fails when the PR is made but is making that sometimes we do not detect broken links in the PR and after merging to master the job fails and the docs are not published. 
Temporary we could disable that check so that the PR's fail (I think it's better to fail the PR even if it's caused by spurious fails). 
IMHO in case that after the merge to master the job fails because we have spurious fails, or a link changed in between the PR was checked and the PR was merged, we should let the documentation be published and create an active alert system (slack, dashboard...) to fix the problem as soon as possible. We could also let the job fail and don't publish the docs, then through the …

Make CI fail when the linkcheck of PR's fail

---

getting_started.rst

Just a minor improvement.
I think it's useful to give the link to the section describing the cmake integration when mentioned in the getting started

[getting started] add reference to cmake section

---

_themes/conan/layout.html

Clean the banner. We will add it back when we have news, the CI/CD training is launched, or similar announcements.

remove training banner

---

creating_packages/define_abi_compatibility.rst

This should fix some broken code blocks in https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema.

Fix incorrect indentation in define_abi_compatibility.rst

---

reference/conanfile/methods.rst

From https://github.com/conan-io/conan-center-index/issues/1609
We know that the current graph model needs improvements and the different package ID modes and helpers can improve some of those like the cases shared_library_package_id() is covering.
However, the text added there is misleading given the fact that we did not update the recipes with that for different reasons. I believe it is better to wait for Conan 2.0 and remove the confusion around it

Remove misleading message about ConanCenter in shared_library_package_id()

---

integrations/cross_platform/yocto.rst

- Removed note about incompatibility with revisions enabled.
- Fixed sentence. closes #1989

Update yocto docs

---

faq/troubleshooting.rst

This FAQ comes from:
https://stackoverflow.com/questions/66078352/conan-error-incompatible-requirements-obtained-in-different-evaluations-of-req
I can't remember if we have such solution in docs, but when looking for ` Incompatible requirements obtained in different evaluations of 'requirements'` I find anything.

Troubleshooting: How to fix incompatible requirements

---

reference/conanfile/tools/qbs.rst

Document changes from https://github.com/conan-io/conan/pull/8537

Rename QbsToolchain to QbsProfile

---

faq/troubleshooting.rst

Update the example message in the docs with a real recipe from conan-center-index.
Issue: conan-io/conan#8557

feature: add recipe name to constrained settings error

---

getting_started.rst
howtos/manage_gcc_abi.rst

When trying out conan, I also ran into the issue documented here:
https://github.com/conan-io/examples/issues/40
I interpreted the existing text in the note as if I had the choice which ABI to use. While that's true in theory ( I could set the corresponding gcc flag in the cmake configuration), no further instructions are provided and it really doesn't make much sense in the context of the Getting Started tutorial to go with the compatibility profile.
Therefore I want to suggest the following changes:
* More explicit instructions on the Getting Started page
* Provide a command to check gccs default configuration value on the Manage gcc >= 5 ABI page.

More explicit instructions in the note about gcc libcxx ABI compatibility

---

reference/conanfile/methods.rst

In response to github question/issue where combination of `version` attribute and `set_version` method caused unexpected behavior with lockfiles: https://github.com/conan-io/conan/issues/8646

Warn about set name and version methods

---

reference/generators/cmake_paths.rst

The text said "and declares two variables" - but there seems to be three variables in the table.
This PR changes the text to "and declares these variables" - to remove the need to update the number in future...

Remove need to update an out-of-date number

---

reference/commands/misc/lock.rst
versioning/lockfiles/bundle.rst
versioning/lockfiles/ci.rst
versioning/lockfiles/introduction.rst

Docs for: https://github.com/conan-io/conan/pull/8726 and https://github.com/conan-io/conan/pull/8021

Docs for lockfiles features from 1.35

---

howtos/header_only.rst
reference/build_helpers/cmake.rst
reference/build_helpers/meson.rst
reference/env_vars.rst

Docs for: https://github.com/conan-io/conan/pull/8687

Docs for automatically handle CONAN_RUN_TESTS environment variable

---

reference/conanfile/tools/cmake.rst

Docs for conan-io/conan#8655 and conan-io/conan#8625

Add docs for CMAKE_SH and data in cmakedeps

---

versioning/lockfiles/bundle.rst

* Update lockfile bundle docs for 1.34.1
* Remove erroneous colon

Update develop with master

---

reference/conanfile/tools/cmake.rst
reference/conanfile/tools/microsoft.rst
reference/config_files/global_conf.rst

Docs for: https://github.com/conan-io/conan/pull/8692

Docs for rename 'tools.microsoft:msbuild_verbosity' to 'tools.microsoft.msbuild:verbosity'

---

reference/conanfile/tools/cmake.rst
reference/conanfile/tools/gnu.rst
reference/conanfile/tools/meson.rst
reference/config_files/global_conf.rst

Docs for: https://github.com/conan-io/conan/pull/8665

Docs for more fine-grained control (using [conf]) for build parallelization

---

reference/conanfile/tools/microsoft.rst

Docs for https://github.com/conan-io/conan/pull/8733

docs for new msbuilddeps transitivity

---

reference/conanfile/attributes.rst

Docs for: https://github.com/conan-io/conan/pull/8727

Add docs for alternative way of setting properties that depend on generator specific features

---

reference/conanfile/methods.rst

New features should show which Conan version is required.
Related to #2087
`generate()` is listed on 1.32 changelog: https://docs.conan.io/en/latest/changelog.html#id126

Add available since to generate feature

---

integrations/cross_platform/emscripten.rst

The https://bincrafters.jfrog.io/ is the new home.

Update Bincrafters remote URL

---

reference/conanfile/tools/files.rst

Docs for conan-io/conan#8915
Issue conan-io/conan#8897

Docs for tools.rename()

---

reference/conanfile/tools/cmake.rst

Docs for the build_context_suffix / build_context_build_modules

CMakeDeps new attributes

---

reference/conanfile/tools/cmake.rst

https://github.com/conan-io/conan/pull/9015

Doc changes for https://github.com/conan-io/conan/pull/9015

---

reference/conanfile/tools/cmake.rst

Docs for https://github.com/conan-io/conan/pull/9032

Toolchain block for XXX_DIRS

---

cheatsheet.rst
index.rst

The aim of this cheatsheet is to provide a reference for people who have already learnt Conan using some other method. It aims to quickly answer the question for such people: "how do I do xxx, again?". 
Sub-aims:
- reduce the need for memorizing common commands
- avoid more time-consuming usage of the docs where possible
- clarify the purpose of the commands and help users get a better intuition of their context.
It collates the information in the three [JFrog Academy tutorials](https://academy.jfrog.com/path/conan).
See https://github.com/conan-io/docs/issues/1726 for related discussion.
Thanks to @claremacrae and @solvingj for their contributions.

Add conan v1 cheatsheet

---

mastering/policies.rst

Also, show explicitly in the example that more than one build exclusion can be specified.
Relates to:
https://github.com/conan-io/docs/pull/2023 , https://github.com/conan-io/conan/pull/8483 
See discussion in: https://cpplang.slack.com/archives/C41CWV9HA/p1623072231189500 and https://cpplang.slack.com/archives/C41CWV9HA/p1623072667191400

Correct --build=! examples to show that --build didn't work, while --build=* did

---

uploading_packages/running_your_server.rst

This an update for running `conan_server` with explanation about the newly added custom server path feature [#9099](https://github.com/conan-io/conan/pull/9099)
Feel free to fix my grammar and spelling, since English is not my first language :)

[feature] Updated server docs with custom server path

---

reference/conanfile/tools/layout.rst

Docs for https://github.com/conan-io/conan/pull/9057

cmake_layout

---

versioning/revisions.rst

Docs for https://github.com/conan-io/conan/pull/9058

allow explicit revision update

---

reference/conanfile.rst
reference/conanfile/dependencies.rst
reference/conanfile/tools/cmake.rst

Docs for 
https://github.com/conan-io/conan/pull/9148
https://github.com/conan-io/conan/pull/9062

dependencies first draft

---

faq/troubleshooting.rst
versioning/introduction.rst

The current link: https://docs.conan.io/en/latest/faq/troubleshooting.html#error-incompatible-requirements-obtained-in-different-evaluations-of-requirements shows a bad markdown link to section in docs. This PR uses `:refs:` feature to avoid that situation.

Fix bad link on FAQ

---

reference/conanfile/attributes.rst

Markdown syntax was used which does not work in `.rst` files.

Fix some links

---

devtools/create_installer_packages.rst
mastering/conditional.rst
reference/conanfile/methods.rst
reference/tools.rst
systems_cross_building/cross_building.rst

The current documentation shows `ConanInvalidConfiguration` associated mainly to `configure` method. However, since Conan 1.32, the new method `validate` has been used for validation, which is well reflected on CCI.
As this is not clear in Docs, users still can [get confused](https://github.com/conan-io/conan-center-index/pull/6468#discussion_r678351314) about the correct usage.
This PR replaces `configure` by `validate` when assuming `ConanInvalidConfiguration` and `check_min_cppstd`. The difference between both is well explained [here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#validate), so I believe this PR is clear enough in terms of need.

Use validate instead of configure

---

integrations/cross_platform/android.rst

Android integration guide is out-of-date because original [repository](https://github.com/bincrafters/conan-android_ndk_installer) is archived and the package `android_ndk_installer` does not exist anymore.
This PR updates Android integration guide with up-to-date information for `android-ndk`, which I believe is the replacement package for `android_ndk_installer`.

updte android integration guide with `android-ndk`

---

reference/commands/creator/export.rst

Going through the docs, I found an unusual sentence formation in the file export.rst. This is my first contribution to any open source project ever!

sentence formation - grammar

---

versioning/lockfiles/configurations.rst

This PR adds a note to the base lockfiles page re: what was learned in https://github.com/conan-io/conan/issues/9446#issuecomment-904846681.
Specifically, this PR attempts to clarify the following:
1. In Conan 1.X, base lockfiles, if used in a separate build/host profile configuration, must also use separate build and host profiles.
2. The profiles used to create the base lockfile should match the widest possible set of requirements to maximize its applicability to all desired build/host profile combinations that will be in the generated lockfiles.
This is a first draft; comments are certainly welcome.

lockfiles/configurations: Add build/host profile note (conan-io/conan #9446)

---

reference/config_files/settings.yml.rst

Related to https://github.com/conan-io/conan/pull/9502

Add Clang 13 

---

reference/generators/premake.rst

Docs for https://github.com/conan-io/conan/pull/9371

Premake docs for 9371

---

mastering/virtualenv.rst
reference/commands/consumer/get.rst
reference/commands/consumer/search.rst
reference/commands/misc/inspect.rst
reference/env_vars.rst
uploading_packages/remotes.rst

Docs for https://github.com/conan-io/conan/pull/9401

Remove conan-center default remote

---

reference/conanfile/tools/files.rst

Docs for https://github.com/conan-io/conan/pull/9361

Document changes in patches

---

reference/commands/consumer/install.rst

Docs for https://github.com/conan-io/conan/pull/9316/files

docs for &: as option specifier of consumer

---

reference/config_files/global_conf.rst
reference/profiles.rst

Docs for https://github.com/conan-io/conan/pull/9468
Would need https://github.com/conan-io/conan/pull/9526 to be merged, but not strictly necessary.

docs for default profiles conf

---

extending/template_system/command_new.rst
reference/conanfile/tools/layout.rst

The new `cmake_lib` predefined is used on Documentation, but there is no reference about `cmake_exe`.
Let's make predefined templates more visible.

Add explanation about cmake_lib and cmake_exe

---

creating_packages/getting_started.rst
reference/conanfile/methods.rst
reference/conanfile/tools/cmake/cmake.rst
reference/conanfile/tools/cmake/cmaketoolchain.rst

`conantoolchain.cmake` is actually `conan_toolchain.cmake`.

Fix typo in Conan toolchain filename

---

howtos/sanitizers.rst

It's deceptive to think that using only `CXXFLAGS` / `CFLAGS` to configure Address Sanitizer would work without linking to Address Sanitizer using `LDFLAGS` in this example. I've just added `LDFLAGS` to make the example functional.

Add LDFLAGS variable to Address Sanitizer example

---

reference/conanfile/tools/env/environment.rst
reference/conanfile/tools/env/virtualbuildenv.rst
reference/conanfile/tools/env/virtualrunenv.rst
reference/conanfile/tools/microsoft.rst

Docs for https://github.com/conan-io/conan/pull/9543/files

multi-config env

---

versioning/lockfiles/ci.rst

We got burned by this as we had set `self.info.requires["MyOtherLib"].minor_mode()` in `package_id()` implementations of several of our packages to deal our lack of semver, and then later changed our config to a more agressive `[general]` `default_package_id_mode`=`package_version_mode` but found some expected package rebuilds weren't happening.
Related: https://github.com/conan-io/conan/issues/4640

Update ci.rst to with a warning about packages that set their own package ID mode overriding the default

---

installation.rst

Should we change references to `$HOME/.conan` to `$HOME/.conan2`?

Installation chapter, with references to python 2 removed

---

faq/troubleshooting.rst

As Bintray has been deprecated and people may complain (we expect not), let's document about it, so at least we don't need to repeat same message on Slack or Conan issues.

Add Troubeshooting about bintray burndown

---

reference/conanfile/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/10026
I am realizing, however, that the interface to add blocks can be greatly simplified. I'll probably try that in 1.44.

fix import of CMakeToolchainBlock

---

reference/conanfile/tools/cmake/cmake.rst
reference/conanfile/tools/meson.rst
reference/config_files/global_conf.rst
reference/profiles.rst

Docs for https://github.com/conan-io/conan/pull/10068

new build jobs docs

---

reference/config_files/settings.yml.rst

Docs for https://github.com/conan-io/conan/pull/10067/

adding os=baremetal brief description

---

conan_v2.rst
devtools/build_requires.rst
reference/conanfile/dependencies.rst

Docs for https://github.com/conan-io/conan/pull/10027

test_requires and some general 2.0 info

---

reference/conanfile/tools/cmake/cmakedeps.rst

Looks like we missed to document this for 1.42

Document cmake_target_aliases

---

using_packages/workflows.rst

The existing command `git clone git@github.com:conan-io/examples` 
gave me an error: 
$ git clone git@github.com:conan-io/examples
Cloning into 'examples'...
`The authenticity of host 'github.com (140.82.121.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
`

updating the git link

---

reference/conanfile/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/10178/files

Multiple user toolchains

---

reference/conanfile/tools/gnu/pkgconfigdeps.rst

Docs for https://github.com/conan-io/conan/pull/10192
Apparently this is the only change that needs to be done in the docs @spaceim

remove rpaths references in AutotoolsDeps and PkgConfigDeps

---

reference/generators/text.rst

The docs specify that the name of the section for include directries is include_dirs[_XXX], but in fact it is includedirs[_XXX]

Fix name of include directories sections

---

reference/config_files/settings.yml.rst

https://github.com/conan-io/conan/pull/9504
https://github.com/conan-io/conan/blame/5ae30ef788539cb00d54389e5bc7c8762e43ee1a/conans/client/conf/detect.py#L231

settings.yml doc: msvc is autodetected as of conan 1.40.0

---

reference/conanfile/tools/microsoft.rst

Available since Conan 1.35.0 and now stated to appear in Conan Center Index, not still not documented.
closes #2362

Add tools.microsoft.msvc_runtime_flag

---

conan_v2.rst

Not really for 1.45, but can be merged anytime after https://github.com/conan-io/conan/pull/10394

self.cpp_info.builddirs defaults

---

conf.py
reference/conanfile/tools/intel.rst

```
(line  278) broken    https://conan.bintray.com/ - HTTPSConnectionPool(host='[conan.bintray.com](http://conan.bintray.com/)', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
(line   26) broken    https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html#gs.cgeofk - Anchor 'gs.cgeofk' not found
```

Fix broken links in documentation

---

cheatsheet.rst

s/os_build=Linus/os_build=Linux/

Fix typo in cheatsheet

---

reference/config_files/settings.yml.rst

Prevents the YAML linter from complaining

Adjust spaces around comments in settings.yml

---

conan_v2.rst
reference/conanfile/tools/gnu/pkgconfigdeps.rst
reference/generators/pkg_config.rst

Docs for https://github.com/conan-io/conan/pull/10633

[PkgConfigDeps] Component versions

---

reference/conanfile/methods.rst

The `self.cpp` documentation refers to `self.info` in one sentence.

Fix typo in self.cpp documentation.

---

reference/conanfile/tools/apple.rst

Docs for: https://github.com/conan-io/conan/pull/10906

Docs for xcodetoolchain global flags

---

reference/conanfile/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/10856

Docs for fix cross-build vars in CMakeToolchain

---

howtos/run_conan_in_docker.rst
systems_cross_building/cross_building.rst

- Legacy images are mostly outdated
- Cross-building is no longer supported. We don't use on Conan Center.
- Docker images -ubuntu16.04 (a.k.a. modern) are replacing all legacy images
closes #2498

Document only modern Docker images from CDT

---

tutorial/creating_packages/getting_started.rst

The command line as is produces this error:
```
conan new: error: unrecognized arguments: --template=cmake_lib
```
I had to read the code to figure out what the problem was. In particular, the command `conan new cmake_lib` produces a cryptic error form Jinja. It would be good to have a better error output from the command as well.

Fix CLI example for creating a new package from a template

---

reference/conanfile/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/10985

[CMakeToolchain] Adding configuration about new Apple flags

---

reference/build_helpers/cmake.rst

Fixes: https://github.com/conan-io/docs/issues/2513

Fix typo error for os_version in cmake.rst

---

developing_packages/package_layout.rst
reference/conanfile/attributes.rst
reference/conanfile/methods.rst
reference/conanfile/tools/files/patches.rst

Docs for https://github.com/conan-io/conan/pull/11055
_Coming from the original Conan PR https://github.com/conan-io/conan/pull/11055:_
> Changelog: Fix: Renamed self.base_source_folder to self.export_source_folder. That variable was introduced to reference the folder where the export_sources are. Currently, they are copied to the source folder but might be changed in the future to avoid copying them, so self.export_source_folder will always point to the exports_sources.

Renamed all the base_source_folder -> export_sources_folder

---

reference/conanfile/tools/env/virtualrunenv.rst

Docs for https://github.com/conan-io/docs/issues/2465

Example for conanrun

---

.ci/test.jenkins

For some reason the spelling step needs the colorama dependency that looks like can't be mocked for autodoc. Let's fix this for the moment and investigate in the future.

Fix ci spelling step

---

migrating_to_2.0/recipes.rst
reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/11471

New cppinfo defaults for components and root cpp_info when 2.0 mode

---

reference/conanfile/tools/cmake/cmake_layout.rst

https://github.com/conan-io/conan/pull/11391

cmake_layout new values

---

reference/conanfile/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/11503/files

Documented cache_variables in CMakeToolchain

---

reference/conanfile/tools/files/basic.rst

https://github.com/conan-io/conan/pull/11443/files

'rm' tool from conan.tools.files

---

reference/conanfile/tools/build.rst

https://github.com/conan-io/conan/pull/11446/files

cppstd ported tools

---

reference/conanfile/tools/files/downloads.rst

Docs for https://github.com/conan-io/conan/pull/11569
Ability for `conan.tools.files.get()`  and `conan.tools.files.download()` to retrieve files from the local filesystem referenced with a `file:///` URI.

Add file:/// handling in download tool

---

reference/conanfile/tools/build.rst

Docs for: https://github.com/conan-io/conan/pull/11667
Documents the changes made for the cgroupv2 support in the `cpu_count()` function.

[bug] get_cpus is not supporting cgroup2 #11635

---

reference/conanfile/tools/system/package_manager.rst

Docs for:
- https://github.com/conan-io/conan/pull/11712
- https://github.com/conan-io/conan/pull/11654

Update changes with system.package_manager

---

videos.rst

Add video entry related to Diego's presentation about Conan 2.0 at ACCU 2022.
Preview:

[videos] ACCU 2022: Advanced Dependencies Model in Conan 2.0

---

reference/conanfile/tools/meson/mesontoolchain.rst

Docs for https://github.com/conan-io/conan/pull/11632 https://github.com/conan-io/conan/pull/11618

MesonToolchain improvements

---

reference/conanfile/tools/meson.rst
reference/conanfile/tools/meson/mesondeps.rst

Docs for https://github.com/conan-io/conan/pull/11557

[generator] MesonDeps

---

reference/conanfile/tools/gnu/autotoolstoolchain.rst

https://github.com/conan-io/conan/pull/11678

Docs for 11678 (AutotoolsToolchain)

---

reference/conanfile/tools/microsoft.rst

Docs for https://github.com/conan-io/conan/pull/11669

components support for MSBuildDeps

---

migrating_to_2.0/recipes.rst
reference/conanfile/methods.rst

https://github.com/conan-io/conan/pull/11580

Docs for 11580 - validate_build()

---

migrating_to_2.0/properties.rst
migrating_to_2.0/recipes.rst
reference/conanfile/tools/cmake/cmakedeps.rst

https://github.com/conan-io/conan/pull/11673

Docs for 11673

---

developing_packages/package_layout.rst

Docs for https://github.com/conan-io/conan/pull/11556/

layout folders.subproject new feature

---

reference/tools.rst

related to https://github.com/conan-io/conan/pull/11527

Document the new behavior of `collect_libs()` with symlinks

---

reference/conanfile/tools/files/basic.rst

examples use it but it's missing from the signature

add conanfile parameter to the new mkdir tool

---

reference/conanfile/tools/files/patches.rst

Docs for: https://github.com/conan-io/conan/pull/11911

Add export_conandata_patches docs

---

reference/tools.rst

The fix should also help users to understand that `tools.get()` can be
used for any zipped archive (including tarballs), not only `.zip` files.

Align tools.get() docstring with conan.tools.files.get()

---

reference/config_files/global_conf.rst

Docs for: https://github.com/conan-io/conan/pull/12087

Update conan config list docs

---

reference/conanfile/tools/cmake/cmaketoolchain.rst

- Put cache_variables first
- Some clarifications and favor cache_variables use
Related to: https://github.com/conan-io/conan/pull/12034

Update docs about CMakeToolchain variables and cache_variables

---

reference/conanfile/tools/apple.rst

Docs for: https://github.com/conan-io/conan/pull/12319

Docs about XCRun settings_target argument

---

reference/conanfile/tools/build.rst

Docs for https://github.com/conan-io/conan/pull/12269

Added stdcpp_library reference

---

reference/conanfile/attributes.rst
reference/conanfile/tools/apple.rst
reference/conanfile/tools/microsoft.rst
reference/conanfile/tools/scm/git.rst

- `rm_safe()` method in `conanfile.settings` & `conanfile.options` since 1.53.0
- `conan.tools.apple.is_apple_os()` function since 1.51.3
- `conan.tools.apple.to_apple_arch()` function since 1.52.0
- `conan.tools.apple.XCRun` class since 1.53.0
- `targets` optional argument of `conan.tools.microsoft.MSBuild.build()` method since 1.52.0
- `run()` method of `conan.tools.scm.Git` class since 1.53.0

Document min conan version of few classes, methods, functions & arguments

---

reference/conanfile/tools/cmake/cmakedeps.rst

Docs for https://github.com/conan-io/conan/pull/12049
(This is merely a clarification for convenience, this is standard CMake behaviour)

Add docs for how to map mismatching build types

---

reference/conanfile/tools/gnu/autotoolstoolchain.rst

Docs for https://github.com/conan-io/conan/pull/12620

Document AutotoolsToolchain prefix argument

---

reference/conanfile/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/12513

[CMakeToolchain] PKG_CONFIG_PATH and PKG_CONFIG_EXECUTABLE

---

tutorial/consuming_packages/build_simple_cmake_project.rst
tutorial/consuming_packages/different_configurations.rst
tutorial/creating_packages/add_dependencies_to_packages.rst
tutorial/creating_packages/build_packages.rst
tutorial/creating_packages/configure_options_settings.rst
tutorial/creating_packages/create_your_first_package.rst
tutorial/creating_packages/package_method.rst
tutorial/creating_packages/preparing_the_build.rst

Explain at the beginning that we will use c++11 so that we don't have to write it several times in the tutorial...
Goes with: https://github.com/conan-io/examples2/pull/51

Update 2.0 docs to not use -s compiler.cppstd=gnu11 in some commands

---

reference/commands.rst

Links for docs on `conan config` and `conan graph` currently point to `conan cache`.

Fix incorrect links in commands.rst

---

reference/commands.rst
reference/commands/build.rst
reference/commands/create.rst
reference/commands/export.rst
reference/commands/graph/build_order.rst
reference/commands/graph/info.rst
reference/commands/install.rst
reference/commands/lock/create.rst
reference/commands/test.rst

For https://github.com/conan-io/conan/pull/12808
Some of the commands did not have docs yet. For those, I've added a basic file with only the result of calling `--help` in each of them and adding a short description afterwards.

Add docs for `--no-remotes` flag

---

reference/conanfile/tools/cmake/cmake.rst

Docs for https://github.com/conan-io/conan/pull/12762

CMake install --component argument docs

---

reference/commands.rst
reference/commands/new.rst

For https://github.com/conan-io/conan/pull/12802 and https://github.com/conan-io/conan/pull/12830
Focuses in `conan new basic` as that's what I implemented in the first linked PR, but also updates the available definitions for the rest of the templates

Add documentation for `conan new`

---

integrations/cross_platform/android.rst

Host and build profiles were mixed up in the android example

Typo fix: mixed up profiles

---

migrating_to_2.0/recipes.rst

The `package_type` attribute is getting popular in CCI: https://github.com/conan-io/conan-center-index/search?q=package_type  But it's not documented in Conan 1.x migration guide, so we need to point to Conan 2.x docs as reference.
closes #2790
Preview:

Add package_type to the migration guide

---

conf.py
requirements.txt

The changelog of 1.7.9 -> 1.8.6 does not look like it affects us much.
I've checked our extra dependencies, and all seem to support/be supported by this version.
The change is motivated because of the idea that having search engines return outdated documentation is not great. This can be somewhat alleviated by adding a `<link rel="canonical" href="https://docs.conan.io/en/latest/">` tag to the HTML doc, which will ask crawlers to prefer to serve results from `https://docs.conan.io/en/latest/`. Note that this is not a redirect for the users, nor mandatory for the crawlers to follow. It's interesting to point out that this is how both the official Python and Sphinx's docs do things.
For Sphinx to be able to generate that tag, we needed to be on 1.8.
After investigating, I found that 1.8.6 …

Bump sphinx to 1.8.6 for canonical url

---

examples/cross_build/android/android_studio.rst
examples/tools/meson/mesontoolchain/build_simple_meson_project.rst
tutorial/consuming_packages/build_simple_cmake_project.rst
tutorial/consuming_packages/cross_building_with_conan.rst
tutorial/consuming_packages/different_configurations.rst
tutorial/consuming_packages/intro_to_versioning.rst
tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst
tutorial/consuming_packages/use_tools_as_conan_packages.rst
tutorial/creating_packages/add_dependencies_to_packages.rst
tutorial/creating_packages/build_packages.rst
tutorial/creating_packages/configure_options_settings.rst
tutorial/creating_packages/define_package_information.rst
tutorial/creating_packages/other_types_of_packages/header_only_packages.rst
tutorial/creating_packages/package_method.rst
tutorial/creating_packages/preparing_the_build.rst
tutorial/creating_packages/test_conan_packages.rst

This: https://github.com/conan-io/examples2/pull/60 is green, so we could use conancenter as remote in the conan 2.0 docs instead of the temporal free-tier instance

Use Conan Center as remote for Conan 2.0 docs

---

reference/commands/profile.rst

Sub-commands should not appear at the first level

[commands] conan profile sub-commands

---

reference/conanfile/tools/cmake/cmake_layout.rst

This error was removed in https://github.com/conan-io/conan/pull/12829/files

Remove error warning for build_folder_vars conf

---

reference/commands/list.rst

related to: 
https://github.com/conan-io/conan/issues/13021
https://github.com/conan-io/conan/issues/13022
it needs some sort of disclaimer that `--format html` may work differently from `--format json` in some circumstances, e.g. showing a different amount of packages.

add note about `conan list --format=html`

---

reference/conanfile/tools/microsoft.rst

Related to https://github.com/conan-io/conan/pull/13041

Add new msvs_toolset

---

auto.sh

* Avoid launching `make html` till any change is done.
* Added `--drop` to avoid multiple instances of `watchdog` being launched (don't try to change between develop2 -> develop while the watchdog process runs in parallel without this parameter...)

[watchdog] Improved `auto.sh`

---

.ci/publish.jenkins

This should reduce the number of concurrent tasks to generate the different branches of the docs and may serve as a temporary fix until we have a smarter way of publishing the docs

Reduce the number of parallel task when generating docs

---

examples/conanfile/layout/third_party_libraries.rst
reference/commands.rst
reference/commands/build.rst
reference/commands/download.rst
reference/commands/editable.rst
reference/commands/export-pkg.rst
reference/commands/source.rst
reference/commands/test.rst
tutorial/creating_packages/add_dependencies_to_packages.rst
tutorial/creating_packages/build_packages.rst
tutorial/creating_packages/define_package_information.rst
tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.rst
tutorial/creating_packages/preparing_the_build.rst
tutorial/developing_packages/local_package_development_flow.rst

And also placeholders for some missing commands
Examples: https://github.com/conan-io/examples2/pull/72

Tutorial for local flow

---

reference/env_vars.rst

Docs for: https://github.com/conan-io/conan/pull/13039

Add docu for CONAN_DISABLE_STRICT_MODE env var (#13039)

---

examples/config_files/settings/settings_user.rst
reference/extensions/profile_plugin.rst

Examples: https://github.com/conan-io/examples2/pull/70

Added `settings_user.yml` example

---

common/experimental_warning.rst
reference/config_files/profiles.rst
reference/config_files/settings.rst
reference/config_files/system_tools_warning.rst
reference/extensions/python_api/ConanAPI.rst
reference/extensions/python_api/ConfigAPI.rst
reference/extensions/python_api/DownloadAPI.rst
reference/extensions/python_api/ExportAPI.rst
reference/extensions/python_api/GraphAPI.rst
reference/extensions/python_api/InstallAPI.rst
reference/extensions/python_api/ListAPI.rst
reference/extensions/python_api/NewAPI.rst
reference/extensions/python_api/ProfilesAPI.rst
reference/extensions/python_api/RemotesAPI.rst
reference/extensions/python_api/RemoveAPI.rst
reference/extensions/python_api/SearchAPI.rst
reference/extensions/python_api/UploadAPI.rst
reference/extensions/python_api/api_warning.rst
tutorial/consuming_packages/use_tools_as_conan_packages.rst

Docs for https://github.com/conan-io/conan/pull/10166

[profiles] Added `[system_tools]`

---

reference/commands/build.rst
reference/commands/cache.rst
reference/commands/config.rst
reference/commands/create.rst
reference/commands/download.rst
reference/commands/editable.rst
reference/commands/export-pkg.rst
reference/commands/export.rst
reference/commands/graph/build_order.rst
reference/commands/graph/build_order_merge.rst
reference/commands/graph/info.rst
reference/commands/inspect.rst
reference/commands/install.rst
reference/commands/list.rst
reference/commands/lock/add.rst
reference/commands/lock/create.rst
reference/commands/lock/merge.rst
reference/commands/new.rst
reference/commands/profile.rst
reference/commands/remote.rst
reference/commands/remove.rst
reference/commands/search.rst
reference/commands/source.rst
reference/commands/test.rst
reference/commands/upload.rst

This includes changes from https://github.com/conan-io/conan/pull/13179
Also fixes some of the typos in the commands reference (Although I plan to improve the actual wording tomorrow, so stay tuned for that)
The most contentious thing this PR does is to get all --help output from an 80-char terminal window. I've done this so that the user does not need to scroll to see the whole output, which could happen for long lines. I've put forth the idea to remove the max-width limit on the content of the docs so that the pages could fill the whole screen and then we wouldn't need to squeeze the output like this, but meanwhile, I think that this reads ok, but I open to using a different one if anyone feels too strongly against this :)

Update commands help for v2

---

reference/config_files/profiles.rst
tutorial/consuming_packages/build_simple_cmake_project.rst

Docs for https://github.com/conan-io/conan/pull/13185

New cppstd for apple-clang

---

reference/commands/remote.rst

Fix command conan remote

---

reference/commands/build.rst
reference/commands/cache.rst
reference/commands/config.rst
reference/commands/create.rst
reference/commands/download.rst
reference/commands/editable.rst
reference/commands/export-pkg.rst
reference/commands/export.rst
reference/commands/graph/build_order.rst
reference/commands/graph/build_order_merge.rst
reference/commands/graph/info.rst
reference/commands/inspect.rst
reference/commands/install.rst
reference/commands/list.rst
reference/commands/lock/add.rst
reference/commands/lock/create.rst
reference/commands/lock/merge.rst
reference/commands/new.rst
reference/commands/profile.rst
reference/commands/remote.rst
reference/commands/remove.rst
reference/commands/search.rst
reference/commands/source.rst
reference/commands/test.rst
reference/commands/upload.rst

Docs for https://github.com/conan-io/conan/pull/13287

Remove --logger

---

reference/conanfile/methods/package_info.rst

From https://github.com/conan-io/conan/issues/13327, to clarify that it is not necessary to define components as a dict

fix component definitions

---

examples/extensions/deployers/sources/custom_deployer_sources.rst

While looking to the docs to find something for conan-extensions, I found this missing space that broke the code style

Quick typo fix

---

.ci/scripts/create_redirects.py
.ci/scripts/prepare_gh_pages.py

Closes: https://github.com/conan-io/docs/issues/3084
Now redirects are like this:
```html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="1; url=https://docs.conan.io/1/integrations/build_system/qmake.html">
<link rel="canonical" href="https://docs.conan.io/1/integrations/build_system/qmake.html">
</head>
</html>
```

Use absolute links for redirects in docs publishing

---

_themes/conan/__init__.py
conf.py

This should fix the sitemap links under the latest version, but still we have to fix those for other branches 
Partially will fix: https://github.com/conan-io/docs/issues/3100

Fix sitemap for master/latest version

---

reference/conanfile/methods/test.rst

An extra space meant the link was not being properly generated

Fix wrong ref link in test method reference

---

reference/commands/remove.rst

Docs for https://github.com/conan-io/conan/pull/13505

Docs for conan remove *#!latest

---

reference/commands/cache.rst

Docs for https://github.com/conan-io/conan/pull/13581

Add documentation for `conan cache clean`

---

reference/commands/config.rst
reference/tools/cmake/cmaketoolchain.rst

Docs for: https://github.com/conan-io/conan/pull/13459

Add docs for tools.android:cmake_legacy_toolchain

---

reference/commands/remove.rst

For https://github.com/conan-io/conan/issues/13595

Add documentation about using --package-query to remove only specific packages

---

reference/conanfile/attributes/binary_model.inc

With whitespace it fails silently in conan 2.0.4 (but fails with `option ' xxx' doesn't exist` in conan 1).

Remove space in requirements options

---

tutorial/creating_packages/other_types_of_packages/header_only_packages.rst

Set libdirs and bindirs as empty in header only packages to align with the Conan Center Index recommendations.
Goes with: https://github.com/conan-io/examples2/pull/91

Set libdirs and bindirs as empty in header only packages

---

reference/commands/config.rst
reference/config_files/global_conf.rst

For https://github.com/conan-io/docs/issues/3176, this conf was removed in 2.0.3 as buggy (required doubled profile definition, super confusing for users)

remove legacy tools.files.download:download_cache conf

---

reference/config_files/profiles.rst

Add the `profile_name` based on the original need, creating a generic profile that uses its own file name to define its settings.
Related to https://github.com/conan-io/conan/pull/13721

[profile] Add profile_name attribute to Jinja context

---

migrating_to_2.0/properties.rst

I stole these verbatim from https://github.com/conan-io/conan-center-index/blob/6e151164ceaf0c5ba56ee39feb2e0931b094520f/docs/v2_migration.md
Since they were missing

1.x: migration guide for build_modules and pkg_config_names

---

reference/extensions.rst
reference/extensions/custom_generators.rst

https://github.com/conan-io/conan/pull/13718

Document custom generators in Conan 2.0

---

reference/config_files/global_conf.rst

Created a conf section to explain some of the more involved confs. This is a work in progress, submitted now not to block the release of 2.0.5. Once merged, will open more PRs targeting the live release until we're happy with its contents
For https://github.com/conan-io/conan/pull/13706

Start work on global conf extra info section

---

reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/13562

scm_folder docs

---

reference/conanfile/attributes/binary_model.inc
reference/config_files/settings.rst

Docs for https://github.com/conan-io/conan/pull/13796

Added `possible_values()`

---

examples.rst
examples/graph.rst
examples/graph/tool_requires/different_options.rst
examples/graph/tool_requires/different_versions.rst

Docs for https://github.com/conan-io/conan/pull/13529

tool-requires with different options and versions

---

reference/conanfile/methods/build_requirements.rst

Docs for https://github.com/conan-io/conan/pull/13712

`<host_version>` syntax

---

reference/commands/config.rst
reference/tools/cmake/cmake.rst

Docs for https://github.com/conan-io/conan/pull/13940

Add tools.cmake:cmake_program docs

---

reference/tools/files/packaging.rst

Close https://github.com/conan-io/docs/issues/3251

autopackager deprecation

---

migrating_to_2.0/commands.rst

I noticed there was a dead link trying to help someone 
I also put in some links for the "WIP documentation" and linked the blog post since that covered more commands and has extra information.

v2 migration fix dead links + reference new blog post

---

reference/tools.rst
reference/tools/cpp_info.rst

Docs for https://github.com/conan-io/conan/pull/14101

CppInfo(self)/aggregate new public interface

---

examples/commands/pkglists.rst
reference/commands/download.rst
reference/commands/remove.rst
reference/commands/upload.rst

Docs for https://github.com/conan-io/conan/pull/14082

remove pkg-lists

---

examples/extensions/deployers/dev/development_deploy.rst
examples/extensions/deployers/sources/custom_deployer_sources.rst
reference/commands/graph/info.rst
reference/commands/install.rst
reference/extensions/deployers.rst

For https://github.com/conan-io/conan/pull/13757

Add `--deployer-folder` docs

---

reference/commands/config.rst
reference/conanfile/methods/package_info.rst
reference/config_files/global_conf.rst
reference/config_files/profiles.rst
reference/tools/apple/xcodebuild.rst
reference/tools/cmake/cmake.rst
reference/tools/meson/meson.rst
reference/tools/microsoft/msbuild.rst

For https://github.com/conan-io/conan/pull/13729

Add verbosity docs

---

reference/build_helpers/cmake.rst
reference/conanfile/tools/cmake/cmake.rst

Fixes #14166: Add strip docs to cmake.install

Fixes #14166: Add strip docs to cmake.install

---

reference/commands/cache.rst

Docs for https://github.com/conan-io/conan/pull/14199

update cache path docs

---

reference/tools/cmake/cmakedeps.rst

Docs for https://github.com/conan-io/conan/pull/14176

cmake version compat

---

reference/conanfile/methods/config_options.rst
reference/conanfile/methods/configure.rst
reference/conanfile/methods/package_id.rst
reference/tools/cpp_info.rst

Docs for https://github.com/conan-io/conan/pull/14194

Document options managed automatically

---

reference/extensions/package_signing.rst

Docs for https://github.com/conan-io/conan/pull/14331

docs for pkg-sign verify

---

examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets.rst

The link to the sources for this part pointed to the `local_flow_cmake_presets` directory which isn't the correct one here.

Update extend_own_cmake_presets.rst to specify correct directory

---

reference/commands/config.rst
reference/config_files/global_conf.rst
reference/tools/system/package_manager.rst

Docs for: https://github.com/conan-io/conan/pull/14382

Added mention to apk package manager

---

reference/tools/cmake/cmake.rst

I noticed there was no mentioning of this configuration in the docs. This commit fixes that.
Implemented on https://github.com/conan-io/conan/commit/cc02d498c456f0fe6c90eb88494047357b537540

cmake: Add mentioning of tools.cmake:install strip

---

reference/tools/files/patches.rst

Docs for https://github.com/conan-io/conan/pull/14576

add patch_user

---

reference/commands/editable.rst

For https://github.com/conan-io/conan/pull/14413 and https://github.com/conan-io/conan/pull/14599

Add `conan editable add` remote args

---

reference/commands/list.rst

Had no idea where to put this... I finally mentioned this in the conan list docs that I think it could have more visibility there....
Docs for https://github.com/conan-io/conan/pull/14338

Add docs for no user/channel pattern matches

---

reference/conanfile/attributes/binary_model.inc

Docs for https://github.com/conan-io/conan/pull/14340

Docs for default_build_options

---

examples/extensions.rst
examples/extensions/deployers/sources/custom_deployer_sources.rst

For https://github.com/conan-io/conan/pull/14466

Add mention to `tools.graph:skip_binaries`

---

reference/commands/config.rst
reference/extensions/deployers.rst

Docs for https://github.com/conan-io/conan/pull/14461

deployer skip_symlinks

---

reference/commands/config.rst
reference/config_files/global_conf.rst

https://github.com/conan-io/conan/pull/14508
https://github.com/conan-io/conan/pull/14466
Among others

Add missing confs

---

examples/tools/cmake/cmake.rst
examples/tools/cmake/cmake_toolchain/inject_cmake_variables.rst

Docs for https://github.com/conan-io/conan/pull/14563
Example: https://github.com/conan-io/examples2/pull/114

example for injecting cmake variables

---

reference/config_files.rst
reference/config_files/credentials.rst

https://github.com/conan-io/conan/pull/14392

docs for credentials.json

---

tutorial/consuming_packages/different_configurations.rst

Just a brief note about the package id in the consuming packages tutorial.
There was already a note in the creating packages tutorial here: https://docs.conan.io/2/tutorial/creating_packages/configure_options_settings.html#conan-packages-binary-compatibility-the-package-id

Add a note about the package ID in the consuming packages tutorial

---

creating_packages/getting_started.rst

Summary:
Typo and framer updates.
- Fix parenthesis mismatch
- Split some run-on sentences
Try to explain the motivation, what are you trying to do, what is the pain it tries to solve:
The motivation with this MR is to primarily add a closing parenthesis `)` character to the documentation. While fixing this, I decided to also make some other nearby minor adjustments and improvements to the documentation to improve readability. 
Please let me know if there is any other changes, updates or improvements I should make. 
Please let me know if there is a different workflow that I should follow for contributing changes like this. 
:smile:

[suggestion] Update getting_started.rst

---

integrations/build_system/scons.rst
reference/conanfile/tools.rst
reference/conanfile/tools/scons.rst
reference/generators/scons.rst

Docs for: https://github.com/conan-io/conan/pull/14713

Add sconsdeps docs

---

reference/conanfile/methods/package_id.rst

Docs for https://github.com/conan-io/conan/pull/14621

Docs for allow regex pattern for conf tools.info.package_id:confs

---

reference/commands/build.rst

Docs for https://github.com/conan-io/conan/pull/14737

conan build reference

---

reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/14731

docs for CMakeToolchain blocks select() and iteration

---

reference/commands/profile.rst

Docs for https://github.com/conan-io/conan/pull/14743

Docs for profile show --format=json

---

reference/tools/meson/mesontoolchain.rst

Docs for https://github.com/conan-io/conan/pull/14692

MesonToolchain and Conan options 

---

reference/tools/system/package_manager.rst

picked from: https://github.com/conan-io/docs/pull/3392 (some part of the original PR will be completed by autodoc)

Add to docs explanation about the option 'host_tool' in install()

---

reference/conanfile/attributes/metadata.inc

https://spdx.dev/ is ok, but it redirects to https://spdx.org/licenses/ for the license list

Fix SPDX license list link

---

reference/tools/system/package_manager.rst

Mentions the apt-get package manager is used by default on Linux Mint as well.
Supports PR made here: https://github.com/conan-io/conan/pull/15026

Update package_manager.rst for linuxmint

---

tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst

An update to the tutorial for #3428 to build in the folder build/Debug instead of build when the cmake_layout is used on linux.

Build in build/Debug folder on linux when using a layout

---

tutorial/creating_packages/add_dependencies_to_packages.rst

Changed the max compiler version from 14 to 23 (latest) to avoid failures with some configurations using versions newer than 14.
Change also made in the examples2 repository: https://github.com/conan-io/examples2/pull/120

Updated max C++ compiler version

---

reference/conanfile/methods/source.rst

docs for https://github.com/conan-io/conan/pull/15004

add note about tools.build:download_source=True and editable

---

reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/14932

conf is read-only

---

reference/conanfile/attributes/requirements.inc
tutorial/versioning/version_ranges.rst

Docs for https://github.com/conan-io/conan/pull/14814

fix prereleases

---

reference/tools/cmake/cmakedeps.rst
reference/tools/gnu/pkgconfigdeps.rst

Referenced to https://github.com/conan-io/conan/pull/14808

add doc to cmakedeps listening to component_version property

---

reference/tools/env/virtualbuildenv.rst
reference/tools/env/virtualrunenv.rst
tutorial/consuming_packages/different_configurations.rst
tutorial/consuming_packages/use_tools_as_conan_packages.rst

Added notes to help Powershell users in the beginning of the tutorial:
- The first time the conan virtual env is used, there's a note so powershell users can create the correct conanbuild file and run it.
- When the profile is introduced there's a note so users can add the powershell conf.
Possible alternatives: 
- Modifying the profile directly on the [first page](https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html), adding another note after it talks about changing the compiler in the profile.
- Reducing the explanation around Powershell and including just some comments in the code blocks.
Let me know what you think and which solution fits best :)

Added tutorial instructions for Powershell users

---

knowledge/faq.rst
reference/commands/graph.rst
reference/commands/graph/explain.rst

Docs for https://github.com/conan-io/conan/pull/14694

Conan graph explain docs

---

reference/conanfile/methods/set_name.rst
reference/conanfile/methods/set_version.rst

Docs for https://github.com/conan-io/conan/pull/15211

set_version and set_name flexibility

---

reference/conanfile/running_and_output.rst

For https://github.com/conan-io/conan/pull/15121

`stderr` argument in Conanfile's `run` method docs

---

reference/commands/config.rst
reference/config_files/global_conf.rst
reference/tools/cmake/cmaketoolchain.rst
reference/tools/microsoft/msbuildtoolchain.rst
reference/tools/microsoft/vcvars.rst

Docs for https://github.com/conan-io/conan/pull/15272

winsdk_version

---

reference/conanfile/attributes/binary_model.inc
reference/conanfile/methods/package_id.rst
tutorial/creating_packages/configure_options_settings.rst
tutorial/creating_packages/other_types_of_packages/header_only_packages.rst

Docs for https://github.com/conan-io/conan/pull/15285

clarify info.clear() behavior

---

reference/conanfile/attributes/sources.inc

Just documenting the opt-out attribute here.
Maybe we can add an example to show the usage of tool requires in the source method?
Docs for https://github.com/conan-io/conan/pull/15153

Docs for source_buildenv

---

reference/commands/lock.rst
reference/commands/lock/remove.rst

Docs for https://github.com/conan-io/conan/pull/15284

lock remove

---

reference/config_files/profiles.rst

Docs for https://github.com/conan-io/conan/pull/15418

Update detect_default_compiler and detect_libcxx docs

---

reference/tools/env/virtualrunenv.rst

This commit adds a short note that settings.os must be set properly for LD_LIBRARY_PATH etc. to appear.

Add note about settings.os requirement for VirtualRunEnv

---

reference/commands/download.rst

Change `downlaod` -> `download`

Fix minor spelling error

---

.ci/scripts/generate_documentation.py

Will prevent errors while generating docs with newer theme versions for the branches that have the language set to None. 
Needed for this: https://github.com/conan-io/docs/pull/3518

Replace language None in doc branches

---

common/config_list.inc
reference/conanfile/attributes.rst

Docs for https://github.com/conan-io/conan/pull/15457
Also docstrings in https://github.com/conan-io/conan/pull/15555

git excluded

---

reference/extensions/python_requires.rst

Docs for https://github.com/conan-io/conan/pull/15485

python_requires test_package

---

reference/commands/remote.rst

Probably needs more, but no idea what to put some sentences about it
For https://github.com/conan-io/conan/pull/15464

Add `--allowed-packages` to conan remote commands

---

reference/commands/list.rst

Docs for https://github.com/conan-io/conan/pull/15262

`conan list` timestamp for compact format

---

common/config_list.inc
reference/commands/upload.rst

For https://github.com/conan-io/conan/pull/15360

Add note about `core.upload:parallel`

---

reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/15447

Add docs for cmakeExecutable

---

reference/conanfile/attributes/binary_model.inc

Docs for https://github.com/conan-io/conan/pull/15453

python_package_id mode

---

tutorial/developing_packages/editable_packages.rst

Docs for https://github.com/conan-io/conan/pull/15300

cascade+editable builds

---

reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/15545

Add docs for compile_definitions with no value

---

reference/config_files/global_conf.rst

closes https://github.com/conan-io/docs/issues/3469

Fix: Add global.conf description section

---

tutorial/consuming_packages/build_simple_cmake_project.rst
tutorial/consuming_packages/different_configurations.rst
tutorial/creating_packages/add_dependencies_to_packages.rst
tutorial/creating_packages/build_packages.rst
tutorial/creating_packages/configure_options_settings.rst
tutorial/creating_packages/create_your_first_package.rst
tutorial/creating_packages/preparing_the_build.rst

This pull request mostly corrects typos and adds missing words in the sections about consuming and creating packages.  It also restructures some paragraphs where I, as a native English speaker could see two or three possible meanings for the original or found the original difficult to understand.  If I have still misunderstood perhaps this can serve to show how and where the original could be improved.

Conan Tutorial Docs

---

reference/conanfile/methods/deploy.rst

- the deploy method does nothing by default
- the example is denoted as an example and not the default implementation
- a few typos
- order of sentences and example

Clarify deploy() docs

---

reference/commands/install.rst
tutorial/versioning/version_ranges.rst

For https://github.com/conan-io/conan/pull/15652

Add notes about `--update`

---

reference/tools/build.rst

The method will be documented by the docustring present in the current PR https://github.com/conan-io/conan/pull/15710
In the current commit https://github.com/conan-io/conan/pull/15710/commits/bfbbd77df37e83346736eff1b0a48ed437c3d88f it shows:

Document conan.tools.build.cppstd_flag

---

reference/binary_model/extending.rst
reference/conanfile/methods/package_info.rst
reference/config_files/profiles.rst
tutorial/consuming_packages/cross_building_with_conan.rst
tutorial/consuming_packages/different_configurations.rst
tutorial/consuming_packages/the_flexibility_of_conanfile_py.rst
tutorial/consuming_packages/use_tools_as_conan_packages.rst
tutorial/creating_packages/build_packages.rst
tutorial/creating_packages/configure_options_settings.rst
tutorial/creating_packages/create_your_first_package.rst
tutorial/creating_packages/handle_sources_in_packages.rst
tutorial/creating_packages/other_types_of_packages/tool_requires_packages.rst
tutorial/creating_packages/package_method.rst
tutorial/creating_packages/preparing_the_build.rst
tutorial/versioning/lockfiles.rst

These are some minor issues that I found while fixing a few of the ones that @ErniGH reported when reading the tutorial

Clean up some of the docs

---

reference/tools/files/basic.rst

For https://github.com/conan-io/conan/pull/15829

Improve trim_conandata() docs

---

reference/conanfile/methods/layout.rst
reference/tools/cmake/cmake_layout.rst
reference/tools/cmake/cmaketoolchain.rst

For https://github.com/conan-io/conan/pull/15705

Add docs for name/version being allowed in `build_folder_vars` conf

---

reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/15830

Document CMAKE_VS_DEBUGGER_ENVIRONMENT behaviour

---

reference/conanfile/attributes/binary_model.inc
reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/15775

Add docs for universal binaries support in CMakeToolchain

---

reference/tools/gnu/pkgconfigdeps.rst

Docs for https://github.com/conan-io/conan/pull/15813. (MesonToolchain explanation is covered by the docstring)

[PkgConfigDeps][MesonToolchain] Added build context folder mechanism

---

reference/tools/cmake/cmake_layout.rst

Docs for https://github.com/conan-io/conan/pull/15767

cmake_layout and new confs

---

reference/commands/config.rst
whatsnew.rst

Docs for https://github.com/conan-io/conan/pull/15748

conan config install-pkg

---

reference/commands/list.rst

For https://github.com/conan-io/conan/pull/15697

Documentation for filtering on conan list

---

reference/extensions/deployers.rst

@memsharded says:
> The direct_deploy is intended to deploy one package, without having to deploy its dependencies. Mostly for convenient extraction of some files inside a given package. So the files won't collide with other package files when deployed. The pkg name has been respected, but it could have been dropped too.
This matches the current implementation which, unlike the full deployer, doesn't use `dep.ref.version`:
https://github.com/conan-io/conan/blob/38188da5d8a3f5b0038934f29d67b8a03e0f3531/conan/internal/deploy.py#L118

direct_deploy doesn't include version in path

---

reference/commands/version.rst

https://github.com/conan-io/conan/pull/16102

New docs for `conan version`

---

reference/conanfile/methods/configure.rst

For https://github.com/conan-io/conan/pull/16105

Remove safe wildcard

---

README.md
reference/tools/meson/mesontoolchain.rst
requirements.txt

Add documentation for subproject in meson (https://github.com/conan-io/conan/pull/15916)
Add missing requirement in requirements.txt
Add missing information about host package required.
Slip windows and Linux export command on separate line for better readability.

Add subproject_options documentation

---

reference/config_files/profiles.rst

Docs for https://github.com/conan-io/conan/pull/16092

detect compilers

---

reference/conanfile/methods/export.rst
reference/conanfile/methods/export_sources.rst

Docs for https://github.com/conan-io/conan/pull/16034

exports conf

---

reference/tools/meson/mesontoolchain.rst

Docs for https://github.com/conan-io/conan/pull/15919

MesonToolchain and native context

---

tutorial/conan_repositories/setting_up_conan_remotes/artifactory/artifactory_ce_cpp.rst

While the bintray.io domain still works, it is not the current domain. I have extracted the new one from the `.env` file of the following download:
https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/cpp/ce/docker/jfrog-artifactory-cpp-ce/7.63.12/jfrog-artifactory-cpp-ce-7.63.12-compose.tar.gz
Also the URLs of the help pages changed.

Update Artifactory CE URLs

---

examples/cross_build/toolchain_packages.rst

https://github.com/conan-io/examples2/pull/146

add url to a new example for cross-compile

---

reference/runners/docker.rst

The documentation only refers `conan create` command when using the new Docker runner feature, but don't mention `conan install`. As you know, people can build packages using `conan install --build`. When using a profile with runner configured and running `conan install --build`, Conan will build the package only consuming the profile, but not using Docker, neither notifying with a warning.
This PR adds a note in the documentation to make it clear. The current output:

Add note about not supporting Docker runner with Conan install command

---

reference/tools/cmake/cmakedeps.rst

Docu for PR: https://github.com/conan-io/conan/pull/16231
Add new CMakeDeps property that allows defining different prefixes for creating CMake variables in the config files.

Add CMakeDeps property to create additional CMake variables with different prefixes

---

reference/commands/graph/explain.rst
reference/config_files/profiles.rst
tutorial/consuming_packages/different_configurations.rst

We keep getting reports of users doing `-o shared=True` and expecting the dependencies to be shared, that only applies to the consumer.
I will try to add a warning in the client side too.

options patterns clarifications

---

creating_packages/package_tools.rst

The Conan Package Tools should be avoided and will be marked as deprecated soon.
Meanwhile, users reading Conan 1.x could have a different understanding about the project, because it's listed in the official Conan documentation and shows how to use.
This PR removes all mentions of CPT from Conan 1.x documentation. The Conan 2.x does not have any reference already.

Remove CPT from Conan 1.x docs

---

reference/config_files/global_conf.rst

I am trying to use `Xcode` CMake generator as default, but `Unix Makefiles` CMake generator for zlib package.
The old example config (`zlib:tools.cmake...`) didn't work for me using Conan client 1.64.1 on MacOS. Conan kept using the Xcode generator for build.
I had to use the new example pattern using star sign for the version of the zlib package (`zlib/*:tools.cmake...`).
This the `global.conf` that works for me:
```
tools.cmake.cmaketoolchain:generator=Xcode
zlib/*:tools.cmake.cmaketoolchain:generator=Unix Makefiles
```
So I think the documentation should be updated for other users to not have to deal with this issue.
I am using Conan 1 and don't know how this behaves in Conan 2.
I guess it might also be a bug in the Conan client? Not sure...

Fix global config zlib example pattern

---

reference/config_files/profiles.rst

Docs for https://github.com/conan-io/conan/pull/16355

api sdk_version

---

devops.rst
devops/vendoring.rst

Docs for https://github.com/conan-io/conan/pull/16073
Please note this doesn't aim to be final, there will be a blog post, and more complete examples, just the minimal placeholder for adventurous users.

vendor=True feature

---

reference/conanfile/attributes.rst
reference/conanfile/attributes/binary_model.inc
reference/conanfile/methods/configure.rst
reference/extensions/binary_compatibility.rst
reference/extensions/profile_plugin.rst
reference/tools/build.rst

Docs for https://github.com/conan-io/conan/pull/16028

languages and cstd support

---

reference/commands/consumer/config.rst

Passing an argument to "--args" as a separate string generates:
conan config install: error: argument -a/--args: expected one argument
if the argument looks like a separate option. Which pretty much anything you want to pass to "git clone" will.

fix syntax of `conan config install --args` example

---

reference/config_files/profiles.rst

The actual [replace-requires](https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires) usage in the profile shows `zlib/1.2.123: zlib/*`, which does not work. My guess is "replace zlib/1.2.123 by latest version available", but then we need to use `[*]` instead.
Related to the PR #3495
/cc @RubenRBS

Fix replace requires for zlib in profile

---

reference/tools/cmake/cmaketoolchain.rst

For https://github.com/conan-io/conan/pull/16481

Documented usage of force option on tools.cmake.cmaketoolchain:extra_variables

---

reference/extensions/custom_generators.rst

Close https://github.com/conan-io/docs/issues/3780

fix custom generators

---

reference/commands/lock.rst
reference/commands/lock/add.rst
reference/commands/lock/remove.rst
reference/commands/lock/update.rst

Docs for https://github.com/memsharded/docs/pull/new/feature/conan_lock_update

conan lock update comand

---

reference/config_files/source_credentials.rst

Docs for https://github.com/conan-io/conan/pull/16425

clarify source_credentials scope

---

reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/16563

CMake enabled blocks

---

knowledge/guidelines.rst

Closes https://github.com/conan-io/docs/issues/3629

Order of arguments good practise

---

conf.py

Avoids situations like this in the current [`conan download`](https://docs.conan.io/2.5/reference/commands/download.html#conan-download) link

Execute Conan before creating docs to avoid migration issues

---

tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.rst

There was a mismatch between the version provided in the 'conan new ...' command and the rest of the documentation, including the 'conan test ...' command.

Fix version mismatch in package_prebuilt_binaries.rst

---

reference/tools/cmake/cmake_layout.rst
reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/16633

build_folder_vars consts

---

examples/tools/scm/git/capture_scm/git_capture_scm.rst

Docs for https://github.com/conan-io/conan/pull/16597

Git core.scm:local_url conf

---

reference/tools/gnu/makedeps.rst

Belongs to conan PR conan-io/conan/pull/16613

Add property feature to MakeDeps

---

reference/conanfile_txt.rst

I used this page as reference for version ranges, it took me a while to realize it is the only page in the documentation using a comma instead of a space to define a version range. I looked for `,<` in the documentation and this seems to be the only location with the wrong syntax.

Fix version range syntax in conanfile_txt.rst

---

examples/cross_build.rst
examples/cross_build/tricore.rst

Docs for https://github.com/conan-io/conan/pull/16317

docs for tricore

---

conf.py
examples/cross_build/android/android_studio.rst
reference/conanfile/methods/finalize.rst
requirements.txt

Newer versions of Android Studio, by default select `kotlin` as the `Build configuration language`.
This PR introduces a new sphinex plugin which supports code tabs, used to display both configurations:
- Groovy 
- Kotlin

Update Android Studio documentation

---

reference/config_files/credentials.rst
reference/config_files/remotes.rst
reference/config_files/source_credentials.rst
reference/extensions.rst
reference/extensions/authorization_plugins.rst

related to: https://github.com/conan-io/conan/pull/16942

Adding documentation for the new  auth plugin

---

_templates/layout.html
conf.py

Changelog: Feature: Use the env variable `ENABLE_COOKIES_BANNER=false` to disable the cookies banner locally.
Close: https://github.com/conan-io/docs/issues/3844

[cookies] Enable/Disable banner in localhost

---

reference/conanfile/methods/source.rst
reference/tools/files/basic.rst
reference/tools/files/downloads.rst

Docs for https://github.com/conan-io/conan/pull/16918

tar extract filters

---

reference/conan_server.rst

The "inside" port goes on the ~left~ right.

Wrong port order in partial docker example

---

reference/extensions/custom_generators.rst

For https://github.com/conan-io/conan/pull/17129

Add custom generators thru tool_requires docs

---

reference/commands/new.rst

Docs for https://github.com/conan-io/conan/pull/17186

conan new default name/version args

---

bo.json
reference/commands/graph/build_order.rst
reference/commands/graph/build_order_merge.rst

Docs for https://github.com/conan-io/conan/pull/17102/files

new profile args in build-order files

---

README.md
changelog.rst
common/conancenter_frozen.inc
conf.py
devops/using_conancenter.rst
reference/config_files/remotes.rst
tutorial/conan_repositories/conan_center.rst

Docs for https://github.com/conan-io/conan/pull/17284

Add docs for center2

---

tutorial/consuming_packages/different_configurations.rst

It should emphasize the next line with the Debug message not the version one.

Emphasize correct line in tutorial

---

_themes/conan_theme/layout.html

Force conan1 deprecation banner to be in top position

---

reference/config_files/global_conf.rst

I copied example blindly and was getting
> ERROR: [conf] Either 'core.cache.storage_path' does not exist in configuration list or the conf format introduced is not valid. Run 'conan config list' to see all the available confs.

fix core.cache examples

---

reference/commands/list.rst
tutorial/versioning/versions.rst

Docs for https://github.com/conan-io/conan/pull/17300

conan list args

---

reference/commands/config.rst

Docs for https://github.com/conan-io/conan/pull/17217

conan config install-pkg with profile, settings

---

devops/backup_sources/sources_backup.rst

Closes https://github.com/conan-io/docs/issues/3940

Improve wording for backup sources conf setup

---

reference/tools/env/envvars.rst
reference/tools/env/virtualbuildenv.rst
reference/tools/env/virtualrunenv.rst
tutorial/consuming_packages/use_tools_as_conan_packages.rst

Docs for https://github.com/conan-io/conan/pull/17416

Docs for new powershell conf

---

reference/commands/create.rst
reference/commands/install.rst

Docs for https://github.com/conan-io/conan/pull/17637

--build=compatible and other --build docs

---

reference/extensions/authorization_plugins.rst
reference/extensions/python_api/RemotesAPI.rst

First sketch for Remote docs

---

incubating.rst

Docs for https://github.com/conan-io/conan/pull/17538

workspace build command

---

reference/tools/cmake/cmaketoolchain.rst

Docs for https://github.com/conan-io/conan/pull/17613

Docs for tools.cmake.cmaketoolchain:user_presets

---

examples/tools.rst
examples/tools/system/package_manager.rst
reference/tools/gnu/pkgconfig.rst

Hello!
This PR is related to https://github.com/conan-io/examples2/pull/177
closes #3974 
Current overview based on the commit f64f1f45

[examples] Add how to package a system package using Conan

---

tutorial/creating_packages/configure_options_settings.rst

copied the note from `configure()` reference

add note about `languages = "C"` since v2.4

---

ci_tutorial/packages_pipeline/multi_configuration.rst

This one is quite important to fix, because one might also think that `ai` was meant here.

Correct type-o in documentation

---

incubating.rst

Docs for https://github.com/conan-io/conan/pull/17887

workspace install args

---

reference/extensions/hooks.rst

Related to https://github.com/conan-io/conan/pull/17856

[feature] Add pre_validate post_validate hooks in reference

---

reference/tools/files/basic.rst

Related to https://github.com/conan-io/conan/pull/17800
It requires Conan develop2 branch to be generated.
Preview - Docs commit [2985991](https://github.com/conan-io/docs/pull/4038/commits/29859916a1c613cbd96f405d8d16dd65ec1e9c06) + Conan commit [63e193b](https://github.com/conan-io/conan/pull/18038/commits/63e193bd8b4e2f592f36f7738583513d16523541)

[reference] Add tools.files.chmod description and reference

---

integrations.rst
integrations/community.rst

Close https://github.com/conan-io/docs/issues/4014
cc @awakecoding @markfinal

new integrations-community section

---

reference/conanfile/attributes/binary_model.inc

Close https://github.com/conan-io/docs/issues/4020

add semver_mode

---

reference/extensions/hooks.rst

This hook came up in https://github.com/conan-io/conan/issues/18165, and I noticed that it has not yet been documented.

Document post_build_fail hook

---

reference/tools/gnu/autotoolstoolchain.rst

Hello! This PR is related to https://github.com/conan-io/conan/pull/18333
I just added a note to illustrate that configure arguments can be extended via Conan conf. 
Page preview - Commit ae275a4e

AutotoolsToolchain: Add note about the new conf tools.gnu:configure_args 

---

.ci/test.jenkins

It's failing because of the rate limit. We may have a separate job to check links from time to time.

Disable linkcheck when testing

---

reference/tools/cmake/cmake.rst
reference/tools/meson/meson.rst

Hello! 
This PR is related to https://github.com/conan-io/conan/pull/18429.
It replaces `tools.cmake:install_strip` by `tools.build:install_strip`, and add the configuration reference in Meson too.

Document config tools.build:install_strip

---

reference/tools/files/patches.rst

Hello!
The `apply_conandata_patches` is used in `source()`, and mostly the documentation points there too:
- https://docs.conan.io/2/examples/tools/files/patches/patch_sources.html#patching-using-apply-conandata-patches-tool
- https://docs.conan.io/2/reference/conanfile/methods/export_sources.html#export-sources

Use apply_conandata_patches in source for patching

---

reference/commands/audit.rst

For https://github.com/conan-io/conan/pull/18437/files
Also fixes the audit commands being leaked into the toc

Add sbom and lockfile references to audit list

---

examples/graph/requires/consume_cmake_macro.rst

The app needs CMakeDeps to work, otherwise it won't find the macro.

Fix CMake macro packaged in a dependency example

---

reference/conanfile/methods/build_id.rst

After a question around the `build_id()` method at https://github.com/conan-io/conan/issues/3106#issuecomment-3032986369, I was reviewing this section of the documentation and found that it is not properly explained and in some cases the concept of the build ID can lead to confusion, so I decided to improve it.
Main additions:
- Better structure.
- Reword the use cases
- Explain the default behavior of the build folder and how the build_id() modifies this.
- Better illustrate the example.
- Add the conan commands needed to create the package (and reuse the build folder).
- Improve the explanation of the conditional build ID.

Improve reference for the build_id() method

---

reference/tools/system/package_manager.rst

Docs for https://github.com/conan-io/conan/pull/18517

how to install system package with version added

---

examples/extensions/commands/clean/custom_command_clean_revisions.rst

This PR is based on the example2 update: https://github.com/conan-io/examples2/pull/193
As it requires Conan 2.21.0 to follow the ListAPI update, this PR targets the develop2 branch.
I added a warning to remind users about using Conan 2.21.0 (too much?). Otherwise, they will have some Python error when trying to use it with older Conan versions. 
Preview [eb48af6](https://github.com/conan-io/docs/pull/4242/commits/eb48af6fc73401e4bd1bbd89d6afacf0ed07c08c)

[examples] Update Conan clean section according to Conan Example2

---

security/audit.rst

For https://github.com/conan-io/conan/pull/18976

Docs for conan audit context filter

---

reference/tools/env/environment.rst
reference/tools/env/envvars.rst
reference/tools/env/virtualbuildenv.rst
reference/tools/env/virtualrunenv.rst

Docs for https://github.com/conan-io/conan/pull/18266

dotenv new feature

---

reference/tools/cmake/cmaketoolchain.rst
reference/tools/gnu/autotoolstoolchain.rst

Docs for https://github.com/conan-io/conan/pull/18992

Add docs for support for universal binaries to AutotoolsToolchain and GnuToolchain

---

devops/using_conancenter.rst
reference/config_files/remotes.rst
security/guidelines.rst

For https://github.com/conan-io/conan/pull/18896

Docs for recipes_only

---

reference/tools/system.rst
reference/tools/system/pip_manager.rst
reference/tools/system/pipenv.rst

Docs for https://github.com/conan-io/conan/pull/18923

PipEnv docs added

---

changelog.rst
conf.py

Conan 2.21.0 docs
